[walls_interior_house_12_100]
pos = [
    0,
    228,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_39]
pos = [
    272,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_40]
pos = [
    276,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_41]
pos = [
    68,
    228,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_42]
pos = [
    344,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_43]
pos = [
    136,
    228,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_44]
pos = [
    340,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_45]
pos = [
    408,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_46]
pos = [
    884,
    660,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_47]
pos = [
    680,
    887,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_48]
pos = [
    684,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_49]
pos = [
    476,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_50]
pos = [
    752,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_51]
pos = [
    544,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_52]
pos = [
    820,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_53]
pos = [
    680,
    684,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_54]
pos = [
    748,
    684,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_55]
pos = [
    612,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_56]
pos = [
    888,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_57]
pos = [
    684,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_58]
pos = [
    956,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_59]
pos = [
    752,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_60]
pos = [
    820,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_61]
pos = [
    888,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_62]
pos = [
    956,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_63]
pos = [
    0,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_64]
pos = [
    68,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_65]
pos = [
    136,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_66]
pos = [
    204,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_67]
pos = [
    0,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_68]
pos = [
    412,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_69]
pos = [
    272,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_70]
pos = [
    884,
    456,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_71]
pos = [
    68,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_72]
pos = [
    204,
    228,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_73]
pos = [
    480,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_74]
pos = [
    548,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_75]
pos = [
    616,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_76]
pos = [
    340,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_77]
pos = [
    136,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_78]
pos = [
    884,
    703,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_79]
pos = [
    952,
    659,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_80]
pos = [
    408,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_81]
pos = [
    204,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_82]
pos = [
    476,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_83]
pos = [
    272,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_84]
pos = [
    544,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_85]
pos = [
    952,
    456,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_86]
pos = [
    816,
    684,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_87]
pos = [
    340,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_88]
pos = [
    612,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_89]
pos = [
    408,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_90]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_91]
pos = [
    476,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_92]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_93]
pos = [
    544,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_94]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_95]
pos = [
    612,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_96]
pos = [
    0,
    0,
]
size = [
    67,
    226,
]

[walls_interior_house_12_97]
pos = [
    69,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_98]
pos = [
    138,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_99]
pos = [
    207,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]
