[location_community_medical_01_211]
pos = [
    508,
    0,
]
size = [
    112,
    238,
]
frame_offset = [
    2,
    11,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_212]
pos = [
    843,
    166,
]
size = [
    102,
    232,
]
frame_offset = [
    6,
    17,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_213]
pos = [
    256,
    121,
]
size = [
    124,
    126,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_214]
pos = [
    382,
    199,
]
size = [
    114,
    120,
]
frame_offset = [
    6,
    134,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_218]
pos = [
    0,
    687,
]
size = [
    100,
    55,
]
frame_offset = [
    20,
    18,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_219]
pos = [
    840,
    511,
]
size = [
    70,
    29,
]
frame_offset = [
    8,
    49,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_220]
pos = [
    119,
    447,
]
size = [
    114,
    61,
]
frame_offset = [
    9,
    12,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_221]
pos = [
    469,
    853,
]
size = [
    69,
    32,
]
frame_offset = [
    3,
    41,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_224]
pos = [
    119,
    331,
]
size = [
    115,
    114,
]
frame_offset = [
    8,
    139,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_225]
pos = [
    256,
    0,
]
size = [
    125,
    119,
]
frame_offset = [
    0,
    133,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_226]
pos = [
    303,
    741,
]
size = [
    90,
    230,
]
frame_offset = [
    34,
    13,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_227]
pos = [
    734,
    0,
]
size = [
    107,
    241,
]
frame_offset = [
    15,
    2,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_228]
pos = [
    0,
    451,
]
size = [
    100,
    234,
]
frame_offset = [
    18,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_229]
pos = [
    246,
    249,
]
size = [
    115,
    245,
]
frame_offset = [
    9,
    7,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_230]
pos = [
    203,
    665,
]
size = [
    98,
    214,
]
frame_offset = [
    2,
    38,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_232]
pos = [
    101,
    794,
]
size = [
    97,
    177,
]
frame_offset = [
    25,
    47,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_233]
pos = [
    128,
    171,
]
size = [
    116,
    158,
]
frame_offset = [
    12,
    88,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_234]
pos = [
    977,
    652,
]
size = [
    43,
    181,
]
frame_offset = [
    0,
    53,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_235]
pos = [
    753,
    845,
]
size = [
    44,
    176,
]
frame_offset = [
    81,
    60,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_236]
pos = [
    0,
    0,
]
size = [
    126,
    157,
]
frame_offset = [
    0,
    90,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_237]
pos = [
    383,
    0,
]
size = [
    123,
    197,
]
frame_offset = [
    5,
    27,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_238]
pos = [
    601,
    512,
]
size = [
    89,
    253,
]
frame_offset = [
    0,
    1,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_239]
pos = [
    711,
    246,
]
size = [
    102,
    253,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_240]
pos = [
    0,
    866,
]
size = [
    98,
    141,
]
frame_offset = [
    24,
    87,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_241]
pos = [
    0,
    216,
]
size = [
    117,
    233,
]
frame_offset = [
    3,
    5,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_242]
pos = [
    692,
    677,
]
size = [
    68,
    166,
]
frame_offset = [
    1,
    37,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_246]
pos = [
    498,
    240,
]
size = [
    106,
    253,
]
frame_offset = [
    20,
    1,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_247]
pos = [
    406,
    504,
]
size = [
    97,
    251,
]
frame_offset = [
    25,
    3,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_54]
pos = [
    821,
    668,
]
size = [
    52,
    69,
]
frame_offset = [
    14,
    57,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_55]
pos = [
    649,
    845,
]
size = [
    52,
    69,
]
frame_offset = [
    58,
    57,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_80]
pos = [
    539,
    887,
]
size = [
    38,
    99,
]
frame_offset = [
    86,
    117,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_81]
pos = [
    912,
    858,
]
size = [
    40,
    99,
]
frame_offset = [
    60,
    104,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_82]
pos = [
    870,
    922,
]
size = [
    38,
    98,
]
frame_offset = [
    28,
    103,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_on_83]
pos = [
    870,
    820,
]
size = [
    40,
    100,
]
frame_offset = [
    2,
    115,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_0]
pos = [
    821,
    739,
]
size = [
    47,
    206,
]
frame_offset = [
    81,
    38,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_1]
pos = [
    875,
    656,
]
size = [
    51,
    162,
]
frame_offset = [
    64,
    70,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_10]
pos = [
    260,
    973,
]
size = [
    72,
    42,
]
frame_offset = [
    54,
    39,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_11]
pos = [
    947,
    166,
]
size = [
    72,
    168,
]
frame_offset = [
    54,
    39,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_12]
pos = [
    505,
    688,
]
size = [
    72,
    163,
]
frame_offset = [
    54,
    37,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_13]
pos = [
    766,
    668,
]
size = [
    53,
    163,
]
frame_offset = [
    11,
    70,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_14]
pos = [
    928,
    652,
]
size = [
    47,
    204,
]
frame_offset = [
    0,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_16]
pos = [
    305,
    504,
]
size = [
    99,
    119,
]
frame_offset = [
    13,
    128,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_17]
pos = [
    843,
    0,
]
size = [
    103,
    164,
]
frame_offset = [
    8,
    85,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_18]
pos = [
    606,
    347,
]
size = [
    102,
    163,
]
frame_offset = [
    16,
    86,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_19]
pos = [
    0,
    744,
]
size = [
    99,
    120,
]
frame_offset = [
    14,
    127,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_2]
pos = [
    692,
    512,
]
size = [
    72,
    163,
]
frame_offset = [
    0,
    37,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_20]
pos = [
    505,
    495,
]
size = [
    94,
    149,
]
frame_offset = [
    29,
    102,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_21]
pos = [
    622,
    117,
]
size = [
    107,
    127,
]
frame_offset = [
    10,
    98,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_22]
pos = [
    305,
    625,
]
size = [
    95,
    114,
]
frame_offset = [
    0,
    136,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_23]
pos = [
    840,
    542,
]
size = [
    65,
    112,
]
frame_offset = [
    62,
    127,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_24]
pos = [
    128,
    85,
]
size = [
    126,
    41,
]
frame_offset = [
    0,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_25]
pos = [
    469,
    757,
]
size = [
    34,
    17,
]
frame_offset = [
    46,
    239,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_26]
pos = [
    182,
    973,
]
size = [
    76,
    41,
]
frame_offset = [
    50,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_27]
pos = [
    334,
    973,
]
size = [
    72,
    40,
]
frame_offset = [
    0,
    216,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_28]
pos = [
    200,
    924,
]
size = [
    80,
    40,
]
frame_offset = [
    0,
    216,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_29]
pos = [
    100,
    973,
]
size = [
    80,
    41,
]
frame_offset = [
    46,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_3]
pos = [
    395,
    757,
]
size = [
    72,
    168,
]
frame_offset = [
    0,
    39,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_30]
pos = [
    204,
    510,
]
size = [
    99,
    153,
]
frame_offset = [
    17,
    96,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_31]
pos = [
    606,
    246,
]
size = [
    103,
    99,
]
frame_offset = [
    12,
    152,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_32]
pos = [
    128,
    128,
]
size = [
    126,
    41,
]
frame_offset = [
    0,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_33]
pos = [
    469,
    776,
]
size = [
    34,
    17,
]
frame_offset = [
    46,
    239,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_34]
pos = [
    948,
    123,
]
size = [
    74,
    41,
]
frame_offset = [
    52,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_35]
pos = [
    395,
    927,
]
size = [
    72,
    40,
]
frame_offset = [
    0,
    216,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_36]
pos = [
    505,
    646,
]
size = [
    80,
    40,
]
frame_offset = [
    0,
    216,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_37]
pos = [
    200,
    881,
]
size = [
    80,
    41,
]
frame_offset = [
    46,
    215,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_38]
pos = [
    919,
    400,
]
size = [
    101,
    96,
]
frame_offset = [
    15,
    154,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_39]
pos = [
    102,
    640,
]
size = [
    99,
    152,
]
frame_offset = [
    12,
    96,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_4]
pos = [
    947,
    336,
]
size = [
    72,
    42,
]
frame_offset = [
    0,
    39,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_40]
pos = [
    703,
    845,
]
size = [
    48,
    91,
]
frame_offset = [
    78,
    155,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_41]
pos = [
    363,
    392,
]
size = [
    106,
    110,
]
frame_offset = [
    19,
    145,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_42]
pos = [
    128,
    0,
]
size = [
    126,
    83,
]
frame_offset = [
    0,
    156,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_43]
pos = [
    363,
    321,
]
size = [
    108,
    69,
]
frame_offset = [
    20,
    140,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_44]
pos = [
    0,
    159,
]
size = [
    126,
    55,
]
frame_offset = [
    0,
    167,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_45]
pos = [
    815,
    400,
]
size = [
    102,
    109,
]
frame_offset = [
    4,
    146,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_46]
pos = [
    649,
    916,
]
size = [
    47,
    94,
]
frame_offset = [
    0,
    156,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_47]
pos = [
    469,
    887,
]
size = [
    68,
    71,
]
frame_offset = [
    38,
    140,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_48]
pos = [
    622,
    0,
]
size = [
    110,
    115,
]
frame_offset = [
    10,
    78,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_49]
pos = [
    766,
    511,
]
size = [
    72,
    155,
]
frame_offset = [
    51,
    97,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_50]
pos = [
    102,
    510,
]
size = [
    100,
    128,
]
frame_offset = [
    0,
    103,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_51]
pos = [
    948,
    0,
]
size = [
    74,
    121,
]
frame_offset = [
    42,
    61,
]
frame_size = [
    128,
    256,
]

[location_community_park_01_52]
pos = [
    919,
    498,
]
size = [
    64,
    152,
]
frame_offset = [
    34,
    92,
]
frame_size = [
    128,
    256,
]

[location_community_police_01_0]
pos = [
    579,
    767,
]
size = [
    68,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]
