[vegetation_farming_dying_01b_10]
pos = [
    0,
    875,
]
size = [
    105,
    64,
]
frame_offset = [
    14,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_11]
pos = [
    107,
    488,
]
size = [
    105,
    143,
]
frame_offset = [
    14,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_12]
pos = [
    354,
    437,
]
size = [
    105,
    111,
]
frame_offset = [
    14,
    139,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_13]
pos = [
    0,
    734,
]
size = [
    105,
    139,
]
frame_offset = [
    14,
    111,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_14]
pos = [
    107,
    633,
]
size = [
    105,
    139,
]
frame_offset = [
    14,
    111,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_15]
pos = [
    214,
    504,
]
size = [
    105,
    131,
]
frame_offset = [
    14,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_16]
pos = [
    521,
    925,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_17]
pos = [
    915,
    564,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_18]
pos = [
    813,
    529,
]
size = [
    100,
    72,
]
frame_offset = [
    14,
    177,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_19]
pos = [
    316,
    912,
]
size = [
    101,
    103,
]
frame_offset = [
    13,
    146,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_20]
pos = [
    609,
    0,
]
size = [
    111,
    134,
]
frame_offset = [
    6,
    115,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_21]
pos = [
    0,
    198,
]
size = [
    117,
    152,
]
frame_offset = [
    1,
    97,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_22]
pos = [
    119,
    199,
]
size = [
    117,
    151,
]
frame_offset = [
    1,
    98,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_23]
pos = [
    355,
    305,
]
size = [
    114,
    130,
]
frame_offset = [
    4,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_24]
pos = [
    632,
    849,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_25]
pos = [
    321,
    727,
]
size = [
    102,
    61,
]
frame_offset = [
    12,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_26]
pos = [
    670,
    607,
]
size = [
    100,
    79,
]
frame_offset = [
    14,
    171,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_27]
pos = [
    813,
    425,
]
size = [
    101,
    102,
]
frame_offset = [
    14,
    148,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_28]
pos = [
    213,
    835,
]
size = [
    101,
    156,
]
frame_offset = [
    13,
    94,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_29]
pos = [
    710,
    386,
]
size = [
    101,
    219,
]
frame_offset = [
    13,
    31,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_30]
pos = [
    567,
    497,
]
size = [
    101,
    220,
]
frame_offset = [
    14,
    30,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_31]
pos = [
    828,
    310,
]
size = [
    101,
    113,
]
frame_offset = [
    13,
    137,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_32]
pos = [
    214,
    709,
]
size = [
    105,
    53,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_33]
pos = [
    107,
    774,
]
size = [
    105,
    55,
]
frame_offset = [
    13,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_34]
pos = [
    833,
    221,
]
size = [
    106,
    87,
]
frame_offset = [
    13,
    162,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_35]
pos = [
    722,
    126,
]
size = [
    109,
    113,
]
frame_offset = [
    13,
    136,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_36]
pos = [
    374,
    0,
]
size = [
    119,
    179,
]
frame_offset = [
    7,
    70,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_37]
pos = [
    0,
    0,
]
size = [
    124,
    196,
]
frame_offset = [
    3,
    53,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_38]
pos = [
    126,
    0,
]
size = [
    123,
    197,
]
frame_offset = [
    4,
    52,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_39]
pos = [
    251,
    0,
]
size = [
    121,
    173,
]
frame_offset = [
    4,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_40]
pos = [
    735,
    731,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_41]
pos = [
    772,
    671,
]
size = [
    100,
    58,
]
frame_offset = [
    14,
    191,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_42]
pos = [
    734,
    788,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_43]
pos = [
    772,
    607,
]
size = [
    100,
    62,
]
frame_offset = [
    14,
    187,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_44]
pos = [
    530,
    719,
]
size = [
    101,
    57,
]
frame_offset = [
    13,
    192,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_45]
pos = [
    582,
    428,
]
size = [
    102,
    67,
]
frame_offset = [
    12,
    185,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_46]
pos = [
    214,
    764,
]
size = [
    103,
    69,
]
frame_offset = [
    11,
    183,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_47]
pos = [
    633,
    719,
]
size = [
    100,
    65,
]
frame_offset = [
    14,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_48]
pos = [
    874,
    621,
]
size = [
    100,
    55,
]
frame_offset = [
    16,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_49]
pos = [
    525,
    862,
]
size = [
    100,
    61,
]
frame_offset = [
    16,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_50]
pos = [
    422,
    831,
]
size = [
    101,
    87,
]
frame_offset = [
    15,
    162,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_51]
pos = [
    107,
    902,
]
size = [
    102,
    114,
]
frame_offset = [
    14,
    135,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_52]
pos = [
    720,
    241,
]
size = [
    106,
    143,
]
frame_offset = [
    11,
    106,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_53]
pos = [
    428,
    550,
]
size = [
    103,
    159,
]
frame_offset = [
    13,
    90,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_54]
pos = [
    609,
    136,
]
size = [
    109,
    150,
]
frame_offset = [
    12,
    99,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_55]
pos = [
    471,
    317,
]
size = [
    109,
    142,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_56]
pos = [
    836,
    800,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_57]
pos = [
    729,
    918,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_58]
pos = [
    734,
    845,
]
size = [
    97,
    71,
]
frame_offset = [
    19,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_59]
pos = [
    237,
    417,
]
size = [
    115,
    85,
]
frame_offset = [
    5,
    170,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_6]
pos = [
    495,
    0,
]
size = [
    112,
    173,
]
frame_offset = [
    8,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_60]
pos = [
    238,
    305,
]
size = [
    115,
    110,
]
frame_offset = [
    6,
    145,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_61]
pos = [
    370,
    181,
]
size = [
    115,
    115,
]
frame_offset = [
    6,
    140,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_62]
pos = [
    834,
    0,
]
size = [
    109,
    114,
]
frame_offset = [
    12,
    141,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_63]
pos = [
    834,
    116,
]
size = [
    108,
    103,
]
frame_offset = [
    12,
    152,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_64]
pos = [
    627,
    906,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_65]
pos = [
    916,
    501,
]
size = [
    100,
    61,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_66]
pos = [
    419,
    920,
]
size = [
    100,
    66,
]
frame_offset = [
    14,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_67]
pos = [
    530,
    778,
]
size = [
    100,
    82,
]
frame_offset = [
    14,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_68]
pos = [
    321,
    607,
]
size = [
    104,
    118,
]
frame_offset = [
    10,
    132,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_69]
pos = [
    0,
    352,
]
size = [
    117,
    128,
]
frame_offset = [
    3,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_7]
pos = [
    487,
    181,
]
size = [
    111,
    134,
]
frame_offset = [
    8,
    116,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_70]
pos = [
    251,
    175,
]
size = [
    117,
    128,
]
frame_offset = [
    3,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_71]
pos = [
    722,
    0,
]
size = [
    110,
    124,
]
frame_offset = [
    7,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_72]
pos = [
    833,
    860,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_73]
pos = [
    828,
    920,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_74]
pos = [
    623,
    963,
]
size = [
    97,
    59,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_75]
pos = [
    837,
    735,
]
size = [
    97,
    63,
]
frame_offset = [
    19,
    193,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_76]
pos = [
    0,
    941,
]
size = [
    104,
    67,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_77]
pos = [
    107,
    831,
]
size = [
    104,
    69,
]
frame_offset = [
    12,
    187,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_78]
pos = [
    214,
    637,
]
size = [
    105,
    70,
]
frame_offset = [
    11,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_79]
pos = [
    461,
    461,
]
size = [
    104,
    70,
]
frame_offset = [
    12,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_8]
pos = [
    0,
    482,
]
size = [
    105,
    250,
]
frame_offset = [
    14,
    0,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_80]
pos = [
    874,
    678,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_81]
pos = [
    632,
    786,
]
size = [
    100,
    61,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_82]
pos = [
    916,
    425,
]
size = [
    100,
    74,
]
frame_offset = [
    14,
    182,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_83]
pos = [
    427,
    711,
]
size = [
    101,
    118,
]
frame_offset = [
    14,
    138,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_84]
pos = [
    319,
    790,
]
size = [
    101,
    120,
]
frame_offset = [
    13,
    136,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_85]
pos = [
    600,
    288,
]
size = [
    108,
    138,
]
frame_offset = [
    12,
    118,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_86]
pos = [
    119,
    352,
]
size = [
    116,
    134,
]
frame_offset = [
    7,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_dying_01b_9]
pos = [
    321,
    550,
]
size = [
    105,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]
