[signs_one-off_06_120]
pos = [
    701,
    0,
]
size = [
    71,
    68,
]
frame_offset = [
    54,
    143,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_121]
pos = [
    528,
    848,
]
size = [
    62,
    174,
]
frame_offset = [
    43,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_122]
pos = [
    726,
    617,
]
size = [
    63,
    145,
]
frame_offset = [
    41,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_123]
pos = [
    804,
    542,
]
size = [
    63,
    180,
]
frame_offset = [
    40,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_124]
pos = [
    713,
    871,
]
size = [
    54,
    151,
]
frame_offset = [
    39,
    62,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_125]
pos = [
    620,
    180,
]
size = [
    64,
    164,
]
frame_offset = [
    9,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_126]
pos = [
    972,
    0,
]
size = [
    50,
    134,
]
frame_offset = [
    9,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_128]
pos = [
    528,
    779,
]
size = [
    64,
    67,
]
frame_offset = [
    0,
    178,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_129]
pos = [
    660,
    600,
]
size = [
    64,
    70,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_130]
pos = [
    66,
    956,
]
size = [
    64,
    66,
]
frame_offset = [
    0,
    178,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_131]
pos = [
    804,
    470,
]
size = [
    64,
    70,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_132]
pos = [
    396,
    945,
]
size = [
    64,
    63,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_133]
pos = [
    660,
    672,
]
size = [
    64,
    66,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_134]
pos = [
    462,
    864,
]
size = [
    64,
    67,
]
frame_offset = [
    0,
    178,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_135]
pos = [
    620,
    0,
]
size = [
    79,
    71,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_136]
pos = [
    777,
    804,
]
size = [
    54,
    60,
]
frame_offset = [
    10,
    184,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_137]
pos = [
    895,
    429,
]
size = [
    64,
    66,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_138]
pos = [
    873,
    888,
]
size = [
    19,
    93,
]
frame_offset = [
    45,
    69,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_139]
pos = [
    132,
    476,
]
size = [
    64,
    126,
]
frame_offset = [
    0,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_140]
pos = [
    396,
    484,
]
size = [
    64,
    111,
]
frame_offset = [
    0,
    44,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_141]
pos = [
    66,
    614,
]
size = [
    64,
    119,
]
frame_offset = [
    0,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_142]
pos = [
    0,
    616,
]
size = [
    64,
    126,
]
frame_offset = [
    0,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_143]
pos = [
    972,
    136,
]
size = [
    50,
    83,
]
frame_offset = [
    46,
    52,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_144]
pos = [
    264,
    594,
]
size = [
    64,
    112,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_145]
pos = [
    132,
    604,
]
size = [
    64,
    118,
]
frame_offset = [
    0,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_146]
pos = [
    472,
    375,
]
size = [
    64,
    133,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_147]
pos = [
    0,
    481,
]
size = [
    64,
    133,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_148]
pos = [
    66,
    481,
]
size = [
    64,
    131,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_149]
pos = [
    66,
    735,
]
size = [
    64,
    113,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_150]
pos = [
    0,
    744,
]
size = [
    64,
    116,
]
frame_offset = [
    0,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_151]
pos = [
    472,
    243,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_152]
pos = [
    592,
    965,
]
size = [
    46,
    54,
]
frame_offset = [
    78,
    75,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_153]
pos = [
    870,
    497,
]
size = [
    62,
    67,
]
frame_offset = [
    60,
    61,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_154]
pos = [
    330,
    965,
]
size = [
    46,
    55,
]
frame_offset = [
    78,
    74,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_155]
pos = [
    594,
    734,
]
size = [
    64,
    67,
]
frame_offset = [
    60,
    62,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_156]
pos = [
    651,
    894,
]
size = [
    54,
    62,
]
frame_offset = [
    60,
    62,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_157]
pos = [
    848,
    736,
]
size = [
    53,
    150,
]
frame_offset = [
    20,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_158]
pos = [
    840,
    0,
]
size = [
    64,
    162,
]
frame_offset = [
    9,
    40,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_159]
pos = [
    606,
    346,
]
size = [
    64,
    145,
]
frame_offset = [
    9,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_160]
pos = [
    506,
    0,
]
size = [
    112,
    231,
]
frame_offset = [
    5,
    23,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_161]
pos = [
    357,
    243,
]
size = [
    113,
    239,
]
frame_offset = [
    7,
    15,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_162]
pos = [
    386,
    0,
]
size = [
    118,
    241,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_163]
pos = [
    129,
    0,
]
size = [
    127,
    235,
]
frame_offset = [
    0,
    20,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_164]
pos = [
    0,
    0,
]
size = [
    127,
    236,
]
frame_offset = [
    0,
    18,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_165]
pos = [
    120,
    238,
]
size = [
    117,
    236,
]
frame_offset = [
    0,
    18,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_166]
pos = [
    0,
    238,
]
size = [
    118,
    241,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_167]
pos = [
    239,
    238,
]
size = [
    116,
    235,
]
frame_offset = [
    0,
    20,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_168]
pos = [
    462,
    510,
]
size = [
    64,
    95,
]
frame_offset = [
    32,
    104,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_169]
pos = [
    396,
    597,
]
size = [
    64,
    95,
]
frame_offset = [
    32,
    104,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_170]
pos = [
    198,
    823,
]
size = [
    64,
    95,
]
frame_offset = [
    32,
    104,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_171]
pos = [
    330,
    704,
]
size = [
    64,
    94,
]
frame_offset = [
    32,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_172]
pos = [
    528,
    522,
]
size = [
    64,
    94,
]
frame_offset = [
    32,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_173]
pos = [
    462,
    607,
]
size = [
    64,
    94,
]
frame_offset = [
    32,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_174]
pos = [
    869,
    649,
]
size = [
    55,
    85,
]
frame_offset = [
    32,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_175]
pos = [
    258,
    0,
]
size = [
    126,
    236,
]
frame_offset = [
    1,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_176]
pos = [
    903,
    764,
]
size = [
    52,
    75,
]
frame_offset = [
    72,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_177]
pos = [
    752,
    332,
]
size = [
    64,
    136,
]
frame_offset = [
    60,
    60,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_178]
pos = [
    829,
    310,
]
size = [
    64,
    136,
]
frame_offset = [
    60,
    60,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_179]
pos = [
    906,
    0,
]
size = [
    64,
    147,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_180]
pos = [
    686,
    279,
]
size = [
    64,
    144,
]
frame_offset = [
    60,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_181]
pos = [
    719,
    764,
]
size = [
    56,
    105,
]
frame_offset = [
    60,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_184]
pos = [
    769,
    871,
]
size = [
    52,
    105,
]
frame_offset = [
    18,
    124,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_185]
pos = [
    330,
    484,
]
size = [
    64,
    113,
]
frame_offset = [
    6,
    116,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_186]
pos = [
    132,
    724,
]
size = [
    64,
    113,
]
frame_offset = [
    6,
    116,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_187]
pos = [
    620,
    73,
]
size = [
    75,
    105,
]
frame_offset = [
    6,
    116,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_188]
pos = [
    869,
    566,
]
size = [
    57,
    81,
]
frame_offset = [
    9,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_189]
pos = [
    672,
    425,
]
size = [
    64,
    89,
]
frame_offset = [
    2,
    118,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_190]
pos = [
    264,
    806,
]
size = [
    64,
    91,
]
frame_offset = [
    2,
    118,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_191]
pos = [
    592,
    886,
]
size = [
    57,
    77,
]
frame_offset = [
    2,
    132,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_192]
pos = [
    957,
    764,
]
size = [
    51,
    66,
]
frame_offset = [
    73,
    40,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_193]
pos = [
    528,
    705,
]
size = [
    64,
    72,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_194]
pos = [
    736,
    545,
]
size = [
    64,
    70,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_195]
pos = [
    396,
    872,
]
size = [
    64,
    71,
]
frame_offset = [
    60,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_196]
pos = [
    462,
    790,
]
size = [
    64,
    72,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_197]
pos = [
    594,
    585,
]
size = [
    64,
    73,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_198]
pos = [
    594,
    660,
]
size = [
    64,
    72,
]
frame_offset = [
    60,
    35,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_199]
pos = [
    654,
    824,
]
size = [
    57,
    68,
]
frame_offset = [
    60,
    35,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_200]
pos = [
    972,
    302,
]
size = [
    49,
    72,
]
frame_offset = [
    17,
    79,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_201]
pos = [
    396,
    694,
]
size = [
    64,
    90,
]
frame_offset = [
    2,
    74,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_202]
pos = [
    198,
    920,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    76,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_203]
pos = [
    330,
    800,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    76,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_204]
pos = [
    791,
    724,
]
size = [
    55,
    78,
]
frame_offset = [
    2,
    85,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_205]
pos = [
    330,
    890,
]
size = [
    64,
    73,
]
frame_offset = [
    60,
    80,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_206]
pos = [
    132,
    941,
]
size = [
    64,
    80,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_207]
pos = [
    985,
    605,
]
size = [
    34,
    63,
]
frame_offset = [
    60,
    74,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_208]
pos = [
    903,
    841,
]
size = [
    46,
    114,
]
frame_offset = [
    20,
    50,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_209]
pos = [
    774,
    0,
]
size = [
    64,
    182,
]
frame_offset = [
    2,
    22,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_210]
pos = [
    697,
    73,
]
size = [
    64,
    204,
]
frame_offset = [
    2,
    22,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_211]
pos = [
    540,
    233,
]
size = [
    64,
    182,
]
frame_offset = [
    2,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_212]
pos = [
    957,
    832,
]
size = [
    43,
    110,
]
frame_offset = [
    2,
    86,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_213]
pos = [
    934,
    497,
]
size = [
    21,
    58,
]
frame_offset = [
    103,
    95,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_214]
pos = [
    670,
    516,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    72,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_215]
pos = [
    738,
    470,
]
size = [
    64,
    73,
]
frame_offset = [
    60,
    81,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_216]
pos = [
    594,
    803,
]
size = [
    58,
    81,
]
frame_offset = [
    8,
    130,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_217]
pos = [
    528,
    618,
]
size = [
    64,
    85,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_218]
pos = [
    396,
    786,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_219]
pos = [
    462,
    933,
]
size = [
    59,
    62,
]
frame_offset = [
    2,
    150,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_220]
pos = [
    985,
    535,
]
size = [
    36,
    68,
]
frame_offset = [
    30,
    129,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_221]
pos = [
    264,
    899,
]
size = [
    64,
    85,
]
frame_offset = [
    2,
    129,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_222]
pos = [
    462,
    703,
]
size = [
    64,
    85,
]
frame_offset = [
    2,
    129,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_223]
pos = [
    981,
    683,
]
size = [
    40,
    66,
]
frame_offset = [
    2,
    148,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_224]
pos = [
    823,
    888,
]
size = [
    48,
    128,
]
frame_offset = [
    76,
    71,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_225]
pos = [
    763,
    184,
]
size = [
    64,
    146,
]
frame_offset = [
    60,
    54,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_226]
pos = [
    840,
    164,
]
size = [
    64,
    144,
]
frame_offset = [
    60,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_227]
pos = [
    660,
    740,
]
size = [
    57,
    82,
]
frame_offset = [
    60,
    110,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_228]
pos = [
    928,
    566,
]
size = [
    55,
    115,
]
frame_offset = [
    11,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_229]
pos = [
    906,
    149,
]
size = [
    64,
    140,
]
frame_offset = [
    2,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_230]
pos = [
    906,
    291,
]
size = [
    64,
    136,
]
frame_offset = [
    2,
    67,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_231]
pos = [
    972,
    221,
]
size = [
    50,
    79,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_232]
pos = [
    651,
    958,
]
size = [
    15,
    61,
]
frame_offset = [
    103,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_233]
pos = [
    604,
    493,
]
size = [
    64,
    90,
]
frame_offset = [
    54,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_234]
pos = [
    132,
    839,
]
size = [
    64,
    100,
]
frame_offset = [
    54,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_235]
pos = [
    198,
    599,
]
size = [
    64,
    116,
]
frame_offset = [
    54,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_236]
pos = [
    264,
    475,
]
size = [
    64,
    117,
]
frame_offset = [
    54,
    83,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_237]
pos = [
    0,
    862,
]
size = [
    64,
    112,
]
frame_offset = [
    54,
    86,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_238]
pos = [
    264,
    708,
]
size = [
    64,
    96,
]
frame_offset = [
    54,
    99,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_239]
pos = [
    926,
    683,
]
size = [
    53,
    79,
]
frame_offset = [
    54,
    108,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_240]
pos = [
    961,
    429,
]
size = [
    61,
    104,
]
frame_offset = [
    42,
    96,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_241]
pos = [
    198,
    476,
]
size = [
    64,
    121,
]
frame_offset = [
    39,
    74,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_242]
pos = [
    330,
    599,
]
size = [
    64,
    103,
]
frame_offset = [
    39,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_243]
pos = [
    538,
    417,
]
size = [
    64,
    103,
]
frame_offset = [
    39,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_244]
pos = [
    198,
    717,
]
size = [
    64,
    104,
]
frame_offset = [
    39,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_06_245]
pos = [
    66,
    850,
]
size = [
    64,
    104,
]
frame_offset = [
    39,
    92,
]
frame_size = [
    128,
    256,
]
