[walls_commercial_02_80]
pos = [
    636,
    0,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_81]
pos = [
    512,
    186,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_82]
pos = [
    272,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_83]
pos = [
    564,
    457,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_84]
pos = [
    340,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_85]
pos = [
    700,
    457,
]
size = [
    66,
    201,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_86]
pos = [
    768,
    456,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_87]
pos = [
    632,
    457,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_0]
pos = [
    705,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_1]
pos = [
    909,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_10]
pos = [
    773,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_11]
pos = [
    841,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_12]
pos = [
    0,
    925,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_13]
pos = [
    611,
    685,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_14]
pos = [
    126,
    228,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_15]
pos = [
    498,
    344,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_16]
pos = [
    580,
    229,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_17]
pos = [
    648,
    229,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_18]
pos = [
    0,
    0,
]
size = [
    126,
    226,
]

[walls_commercial_03_19]
pos = [
    977,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_2]
pos = [
    128,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_20]
pos = [
    476,
    871,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_21]
pos = [
    903,
    456,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_22]
pos = [
    0,
    376,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_23]
pos = [
    476,
    507,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_24]
pos = [
    716,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_25]
pos = [
    784,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_26]
pos = [
    852,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_27]
pos = [
    920,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_28]
pos = [
    700,
    660,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_29]
pos = [
    544,
    831,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_3]
pos = [
    993,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_30]
pos = [
    126,
    321,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_31]
pos = [
    484,
    507,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_32]
pos = [
    0,
    469,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_33]
pos = [
    68,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_34]
pos = [
    256,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_35]
pos = [
    985,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_36]
pos = [
    611,
    779,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_37]
pos = [
    766,
    660,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_38]
pos = [
    250,
    228,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_39]
pos = [
    1009,
    0,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_4]
pos = [
    544,
    685,
]
size = [
    65,
    144,
]
frame_offset = [
    1,
    82,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_40]
pos = [
    136,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_41]
pos = [
    0,
    697,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_42]
pos = [
    204,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_43]
pos = [
    272,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_44]
pos = [
    836,
    602,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_45]
pos = [
    903,
    550,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_46]
pos = [
    124,
    414,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_47]
pos = [
    476,
    571,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_48]
pos = [
    68,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_49]
pos = [
    340,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_5]
pos = [
    836,
    456,
]
size = [
    65,
    144,
]
frame_offset = [
    60,
    82,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_50]
pos = [
    384,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_51]
pos = [
    1001,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_52]
pos = [
    677,
    754,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_53]
pos = [
    542,
    925,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_54]
pos = [
    250,
    321,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_55]
pos = [
    484,
    571,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_56]
pos = [
    136,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_57]
pos = [
    408,
    507,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_58]
pos = [
    496,
    415,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_59]
pos = [
    204,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_6]
pos = [
    0,
    228,
]
size = [
    124,
    146,
]
frame_offset = [
    1,
    82,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_60]
pos = [
    610,
    873,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_61]
pos = [
    743,
    754,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_62]
pos = [
    374,
    228,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_63]
pos = [
    1009,
    64,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_64]
pos = [
    677,
    848,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_65]
pos = [
    832,
    696,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_66]
pos = [
    248,
    414,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_67]
pos = [
    1009,
    128,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_68]
pos = [
    902,
    644,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_69]
pos = [
    743,
    848,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_7]
pos = [
    498,
    228,
]
size = [
    6,
    114,
]
frame_offset = [
    60,
    82,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_70]
pos = [
    374,
    321,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_71]
pos = [
    988,
    198,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_72]
pos = [
    809,
    790,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_73]
pos = [
    898,
    738,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_74]
pos = [
    372,
    414,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_75]
pos = [
    996,
    198,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_76]
pos = [
    809,
    884,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_77]
pos = [
    875,
    832,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_78]
pos = [
    512,
    0,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_79]
pos = [
    1009,
    192,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_8]
pos = [
    476,
    643,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_80]
pos = [
    941,
    832,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_81]
pos = [
    875,
    926,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_82]
pos = [
    512,
    93,
]
size = [
    122,
    91,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_83]
pos = [
    988,
    262,
]
size = [
    6,
    62,
]
frame_offset = [
    60,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_84]
pos = [
    941,
    926,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[walls_commercial_03_9]
pos = [
    408,
    735,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
