[roofs_03_102]
pos = [
    904,
    476,
]
size = [
    97,
    80,
]
frame_offset = [
    31,
    48,
]
frame_size = [
    128,
    256,
]

[roofs_03_103]
pos = [
    514,
    871,
]
size = [
    97,
    80,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[roofs_03_104]
pos = [
    776,
    589,
]
size = [
    124,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_03_105]
pos = [
    778,
    394,
]
size = [
    124,
    193,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_03_106]
pos = [
    260,
    195,
]
size = [
    128,
    132,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[roofs_03_107]
pos = [
    260,
    329,
]
size = [
    128,
    132,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_03_108]
pos = [
    650,
    394,
]
size = [
    126,
    132,
]
frame_offset = [
    2,
    59,
]
frame_size = [
    128,
    256,
]

[roofs_03_109]
pos = [
    520,
    597,
]
size = [
    125,
    133,
]
frame_offset = [
    2,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_03_110]
pos = [
    517,
    732,
]
size = [
    124,
    137,
]
frame_offset = [
    0,
    54,
]
frame_size = [
    128,
    256,
]

[roofs_03_111]
pos = [
    776,
    720,
]
size = [
    122,
    136,
]
frame_offset = [
    2,
    120,
]
frame_size = [
    128,
    256,
]

[roofs_03_121]
pos = [
    5,
    988,
]
size = [
    1,
    2,
]
frame_offset = [
    127,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_03_62]
pos = [
    0,
    258,
]
size = [
    128,
    208,
]
frame_offset = [
    0,
    17,
]
frame_size = [
    128,
    256,
]

[roofs_03_63]
pos = [
    313,
    957,
]
size = [
    51,
    41,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_03_65]
pos = [
    0,
    988,
]
size = [
    3,
    1,
]
frame_offset = [
    62,
    255,
]
frame_size = [
    128,
    256,
]

[roofs_03_70]
pos = [
    902,
    640,
]
size = [
    97,
    80,
]
frame_offset = [
    31,
    48,
]
frame_size = [
    128,
    256,
]

[roofs_03_71]
pos = [
    900,
    722,
]
size = [
    97,
    80,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[roofs_03_72]
pos = [
    647,
    723,
]
size = [
    124,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_03_73]
pos = [
    650,
    528,
]
size = [
    124,
    193,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_03_74]
pos = [
    390,
    0,
]
size = [
    128,
    132,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[roofs_03_75]
pos = [
    520,
    0,
]
size = [
    128,
    132,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_03_76]
pos = [
    260,
    823,
]
size = [
    126,
    132,
]
frame_offset = [
    2,
    59,
]
frame_size = [
    128,
    256,
]

[roofs_03_77]
pos = [
    390,
    727,
]
size = [
    125,
    133,
]
frame_offset = [
    2,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_03_78]
pos = [
    388,
    862,
]
size = [
    124,
    137,
]
frame_offset = [
    0,
    54,
]
frame_size = [
    128,
    256,
]

[roofs_03_79]
pos = [
    643,
    854,
]
size = [
    122,
    136,
]
frame_offset = [
    2,
    120,
]
frame_size = [
    128,
    256,
]

[roofs_03_89]
pos = [
    0,
    994,
]
size = [
    1,
    2,
]
frame_offset = [
    127,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_03_97]
pos = [
    0,
    991,
]
size = [
    3,
    1,
]
frame_offset = [
    62,
    255,
]
frame_size = [
    128,
    256,
]

[roofs_04_0]
pos = [
    0,
    468,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_1]
pos = [
    520,
    134,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_04_10]
pos = [
    130,
    405,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_11]
pos = [
    0,
    598,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_12]
pos = [
    260,
    0,
]
size = [
    128,
    193,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_04_13]
pos = [
    130,
    535,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_14]
pos = [
    904,
    558,
]
size = [
    97,
    80,
]
frame_offset = [
    31,
    112,
]
frame_size = [
    128,
    256,
]

[roofs_04_15]
pos = [
    904,
    393,
]
size = [
    97,
    81,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[roofs_04_16]
pos = [
    910,
    227,
]
size = [
    90,
    72,
]
frame_offset = [
    38,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_17]
pos = [
    910,
    301,
]
size = [
    90,
    72,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_2]
pos = [
    0,
    0,
]
size = [
    128,
    256,
]

[roofs_04_20]
pos = [
    130,
    895,
]
size = [
    128,
    72,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_21]
pos = [
    910,
    0,
]
size = [
    90,
    225,
]
frame_offset = [
    38,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_24]
pos = [
    390,
    527,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_04_25]
pos = [
    520,
    396,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_04_26]
pos = [
    130,
    795,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    30,
]
frame_size = [
    128,
    256,
]

[roofs_04_27]
pos = [
    260,
    723,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    30,
]
frame_size = [
    128,
    256,
]

[roofs_04_28]
pos = [
    520,
    497,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_04_29]
pos = [
    390,
    627,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_04_3]
pos = [
    130,
    665,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_30]
pos = [
    130,
    0,
]
size = [
    128,
    208,
]
frame_offset = [
    0,
    17,
]
frame_size = [
    128,
    256,
]

[roofs_04_31]
pos = [
    260,
    957,
]
size = [
    51,
    41,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_04_32]
pos = [
    260,
    463,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_33]
pos = [
    390,
    266,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_04_34]
pos = [
    0,
    728,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_35]
pos = [
    390,
    397,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_36]
pos = [
    780,
    0,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_04_37]
pos = [
    650,
    132,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_04_38]
pos = [
    767,
    858,
]
size = [
    90,
    72,
]
frame_offset = [
    38,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_39]
pos = [
    767,
    932,
]
size = [
    90,
    72,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_4]
pos = [
    780,
    131,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_04_40]
pos = [
    390,
    134,
]
size = [
    128,
    130,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_04_41]
pos = [
    520,
    265,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_04_42]
pos = [
    260,
    593,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_43]
pos = [
    0,
    858,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_04_44]
pos = [
    130,
    210,
]
size = [
    128,
    193,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_04_5]
pos = [
    650,
    263,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_04_6]
pos = [
    900,
    804,
]
size = [
    90,
    72,
]
frame_offset = [
    38,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_7]
pos = [
    859,
    878,
]
size = [
    90,
    72,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_04_8]
pos = [
    650,
    0,
]
size = [
    128,
    130,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_04_9]
pos = [
    780,
    262,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]
