[food_01_100]
pos = [
    80,
    553,
]
size = [
    77,
    107,
]
frame_offset = [
    46,
    70,
]
frame_size = [
    128,
    256,
]

[food_01_101]
pos = [
    834,
    552,
]
size = [
    61,
    102,
]
frame_offset = [
    14,
    75,
]
frame_size = [
    128,
    256,
]

[food_01_102]
pos = [
    0,
    845,
]
size = [
    75,
    106,
]
frame_offset = [
    45,
    54,
]
frame_size = [
    128,
    256,
]

[food_01_103]
pos = [
    496,
    546,
]
size = [
    71,
    111,
]
frame_offset = [
    3,
    50,
]
frame_size = [
    128,
    256,
]

[food_01_60]
pos = [
    633,
    242,
]
size = [
    81,
    107,
]
frame_offset = [
    17,
    98,
]
frame_size = [
    128,
    256,
]

[food_01_61]
pos = [
    471,
    659,
]
size = [
    67,
    186,
]
frame_offset = [
    22,
    26,
]
frame_size = [
    128,
    256,
]

[food_01_62]
pos = [
    825,
    937,
]
size = [
    40,
    81,
]
frame_offset = [
    34,
    118,
]
frame_size = [
    128,
    256,
]

[food_01_63]
pos = [
    869,
    898,
]
size = [
    40,
    81,
]
frame_offset = [
    52,
    118,
]
frame_size = [
    128,
    256,
]

[food_01_64]
pos = [
    912,
    0,
]
size = [
    80,
    139,
]
frame_offset = [
    29,
    91,
]
frame_size = [
    128,
    256,
]

[food_01_65]
pos = [
    381,
    835,
]
size = [
    64,
    139,
]
frame_offset = [
    24,
    91,
]
frame_size = [
    128,
    256,
]

[food_01_66]
pos = [
    607,
    569,
]
size = [
    64,
    140,
]
frame_offset = [
    38,
    90,
]
frame_size = [
    128,
    256,
]

[food_01_67]
pos = [
    743,
    172,
]
size = [
    80,
    139,
]
frame_offset = [
    17,
    91,
]
frame_size = [
    128,
    256,
]

[food_01_68]
pos = [
    829,
    0,
]
size = [
    81,
    134,
]
frame_offset = [
    30,
    95,
]
frame_size = [
    128,
    256,
]

[food_01_69]
pos = [
    673,
    597,
]
size = [
    64,
    126,
]
frame_offset = [
    24,
    96,
]
frame_size = [
    128,
    256,
]

[food_01_70]
pos = [
    769,
    509,
]
size = [
    63,
    126,
]
frame_offset = [
    39,
    96,
]
frame_size = [
    128,
    256,
]

[food_01_71]
pos = [
    0,
    600,
]
size = [
    77,
    134,
]
frame_offset = [
    19,
    95,
]
frame_size = [
    128,
    256,
]

[food_01_72]
pos = [
    156,
    770,
]
size = [
    74,
    45,
]
frame_offset = [
    22,
    167,
]
frame_size = [
    128,
    256,
]

[food_01_73]
pos = [
    358,
    425,
]
size = [
    80,
    44,
]
frame_offset = [
    22,
    168,
]
frame_size = [
    128,
    256,
]

[food_01_74]
pos = [
    152,
    968,
]
size = [
    66,
    53,
]
frame_offset = [
    16,
    159,
]
frame_size = [
    128,
    256,
]

[food_01_75]
pos = [
    225,
    954,
]
size = [
    66,
    53,
]
frame_offset = [
    44,
    159,
]
frame_size = [
    128,
    256,
]

[food_01_76]
pos = [
    440,
    425,
]
size = [
    80,
    44,
]
frame_offset = [
    24,
    168,
]
frame_size = [
    128,
    256,
]

[food_01_77]
pos = [
    237,
    693,
]
size = [
    74,
    45,
]
frame_offset = [
    30,
    167,
]
frame_size = [
    128,
    256,
]

[food_01_78]
pos = [
    322,
    676,
]
size = [
    71,
    121,
]
frame_offset = [
    47,
    45,
]
frame_size = [
    128,
    256,
]

[food_01_79]
pos = [
    230,
    831,
]
size = [
    69,
    121,
]
frame_offset = [
    10,
    45,
]
frame_size = [
    128,
    256,
]

[food_01_80]
pos = [
    293,
    954,
]
size = [
    62,
    41,
]
frame_offset = [
    22,
    171,
]
frame_size = [
    128,
    256,
]

[food_01_81]
pos = [
    507,
    981,
]
size = [
    41,
    36,
]
frame_offset = [
    22,
    168,
]
frame_size = [
    128,
    256,
]

[food_01_82]
pos = [
    447,
    973,
]
size = [
    58,
    47,
]
frame_offset = [
    24,
    164,
]
frame_size = [
    128,
    256,
]

[food_01_83]
pos = [
    604,
    837,
]
size = [
    58,
    47,
]
frame_offset = [
    44,
    164,
]
frame_size = [
    128,
    256,
]

[food_01_84]
pos = [
    550,
    981,
]
size = [
    41,
    36,
]
frame_offset = [
    63,
    168,
]
frame_size = [
    128,
    256,
]

[food_01_85]
pos = [
    834,
    509,
]
size = [
    62,
    41,
]
frame_offset = [
    42,
    171,
]
frame_size = [
    128,
    256,
]

[food_01_86]
pos = [
    702,
    476,
]
size = [
    65,
    119,
]
frame_offset = [
    50,
    47,
]
frame_size = [
    128,
    256,
]

[food_01_87]
pos = [
    540,
    659,
]
size = [
    65,
    119,
]
frame_offset = [
    11,
    47,
]
frame_size = [
    128,
    256,
]

[food_01_88]
pos = [
    986,
    365,
]
size = [
    26,
    112,
]
frame_offset = [
    47,
    111,
]
frame_size = [
    128,
    256,
]

[food_01_89]
pos = [
    901,
    777,
]
size = [
    41,
    119,
]
frame_offset = [
    19,
    97,
]
frame_size = [
    128,
    256,
]

[food_01_90]
pos = [
    782,
    901,
]
size = [
    41,
    119,
]
frame_offset = [
    68,
    98,
]
frame_size = [
    128,
    256,
]

[food_01_91]
pos = [
    995,
    694,
]
size = [
    26,
    112,
]
frame_offset = [
    55,
    112,
]
frame_size = [
    128,
    256,
]

[food_01_92]
pos = [
    624,
    886,
]
size = [
    26,
    103,
]
frame_offset = [
    47,
    112,
]
frame_size = [
    128,
    256,
]

[food_01_93]
pos = [
    782,
    782,
]
size = [
    43,
    117,
]
frame_offset = [
    19,
    99,
]
frame_size = [
    128,
    256,
]

[food_01_94]
pos = [
    950,
    694,
]
size = [
    43,
    117,
]
frame_offset = [
    66,
    100,
]
frame_size = [
    128,
    256,
]

[food_01_95]
pos = [
    986,
    813,
]
size = [
    26,
    103,
]
frame_offset = [
    55,
    113,
]
frame_size = [
    128,
    256,
]

[food_01_96]
pos = [
    166,
    499,
]
size = [
    77,
    107,
]
frame_offset = [
    46,
    70,
]
frame_size = [
    128,
    256,
]

[food_01_97]
pos = [
    0,
    736,
]
size = [
    77,
    107,
]
frame_offset = [
    3,
    70,
]
frame_size = [
    128,
    256,
]

[food_01_98]
pos = [
    911,
    141,
]
size = [
    79,
    111,
]
frame_offset = [
    44,
    50,
]
frame_size = [
    128,
    256,
]

[food_01_99]
pos = [
    716,
    313,
]
size = [
    79,
    111,
]
frame_offset = [
    3,
    50,
]
frame_size = [
    128,
    256,
]

[food_02_0]
pos = [
    90,
    376,
]
size = [
    85,
    114,
]
frame_offset = [
    24,
    126,
]
frame_size = [
    128,
    256,
]

[food_02_1]
pos = [
    291,
    210,
]
size = [
    85,
    114,
]
frame_offset = [
    17,
    126,
]
frame_size = [
    128,
    256,
]

[food_02_10]
pos = [
    184,
    233,
]
size = [
    85,
    219,
]
frame_offset = [
    23,
    1,
]
frame_size = [
    128,
    256,
]

[food_02_11]
pos = [
    378,
    236,
]
size = [
    85,
    95,
]
frame_offset = [
    18,
    125,
]
frame_size = [
    128,
    256,
]

[food_02_12]
pos = [
    825,
    244,
]
size = [
    79,
    106,
]
frame_offset = [
    26,
    132,
]
frame_size = [
    128,
    256,
]

[food_02_13]
pos = [
    421,
    546,
]
size = [
    73,
    94,
]
frame_offset = [
    28,
    143,
]
frame_size = [
    128,
    256,
]

[food_02_16]
pos = [
    631,
    472,
]
size = [
    69,
    95,
]
frame_offset = [
    29,
    143,
]
frame_size = [
    128,
    256,
]

[food_02_17]
pos = [
    906,
    304,
]
size = [
    78,
    206,
]
frame_offset = [
    22,
    32,
]
frame_size = [
    128,
    256,
]

[food_02_18]
pos = [
    358,
    333,
]
size = [
    85,
    90,
]
frame_offset = [
    23,
    130,
]
frame_size = [
    128,
    256,
]

[food_02_19]
pos = [
    486,
    0,
]
size = [
    85,
    88,
]
frame_offset = [
    18,
    132,
]
frame_size = [
    128,
    256,
]

[food_02_2]
pos = [
    573,
    0,
]
size = [
    84,
    130,
]
frame_offset = [
    24,
    126,
]
frame_size = [
    128,
    256,
]

[food_02_20]
pos = [
    79,
    662,
]
size = [
    77,
    105,
]
frame_offset = [
    26,
    133,
]
frame_size = [
    128,
    256,
]

[food_02_21]
pos = [
    237,
    740,
]
size = [
    72,
    89,
]
frame_offset = [
    24,
    143,
]
frame_size = [
    128,
    256,
]

[food_02_24]
pos = [
    79,
    801,
]
size = [
    74,
    73,
]
frame_offset = [
    32,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_25]
pos = [
    959,
    512,
]
size = [
    55,
    180,
]
frame_offset = [
    35,
    32,
]
frame_size = [
    128,
    256,
]

[food_02_26]
pos = [
    512,
    912,
]
size = [
    55,
    67,
]
frame_offset = [
    36,
    145,
]
frame_size = [
    128,
    256,
]

[food_02_27]
pos = [
    421,
    471,
]
size = [
    74,
    73,
]
frame_offset = [
    20,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_28]
pos = [
    398,
    642,
]
size = [
    71,
    65,
]
frame_offset = [
    32,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_29]
pos = [
    569,
    912,
]
size = [
    53,
    52,
]
frame_offset = [
    35,
    153,
]
frame_size = [
    128,
    256,
]

[food_02_3]
pos = [
    271,
    326,
]
size = [
    85,
    113,
]
frame_offset = [
    17,
    126,
]
frame_size = [
    128,
    256,
]

[food_02_30]
pos = [
    853,
    656,
]
size = [
    47,
    67,
]
frame_offset = [
    38,
    145,
]
frame_size = [
    128,
    256,
]

[food_02_31]
pos = [
    322,
    601,
]
size = [
    74,
    73,
]
frame_offset = [
    20,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_32]
pos = [
    0,
    405,
]
size = [
    87,
    56,
]
frame_offset = [
    17,
    128,
]
frame_size = [
    128,
    256,
]

[food_02_33]
pos = [
    0,
    344,
]
size = [
    88,
    59,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[food_02_34]
pos = [
    263,
    475,
]
size = [
    79,
    33,
]
frame_offset = [
    19,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_35]
pos = [
    271,
    441,
]
size = [
    81,
    32,
]
frame_offset = [
    25,
    140,
]
frame_size = [
    128,
    256,
]

[food_02_36]
pos = [
    90,
    317,
]
size = [
    86,
    57,
]
frame_offset = [
    18,
    128,
]
frame_size = [
    128,
    256,
]

[food_02_37]
pos = [
    86,
    492,
]
size = [
    78,
    59,
]
frame_offset = [
    32,
    125,
]
frame_size = [
    128,
    256,
]

[food_02_38]
pos = [
    0,
    953,
]
size = [
    74,
    33,
]
frame_offset = [
    19,
    139,
]
frame_size = [
    128,
    256,
]

[food_02_39]
pos = [
    79,
    769,
]
size = [
    75,
    30,
]
frame_offset = [
    31,
    142,
]
frame_size = [
    128,
    256,
]

[food_02_40]
pos = [
    0,
    508,
]
size = [
    78,
    90,
]
frame_offset = [
    24,
    127,
]
frame_size = [
    128,
    256,
]

[food_02_41]
pos = [
    659,
    0,
]
size = [
    84,
    89,
]
frame_offset = [
    19,
    127,
]
frame_size = [
    128,
    256,
]

[food_02_42]
pos = [
    291,
    117,
]
size = [
    89,
    91,
]
frame_offset = [
    23,
    138,
]
frame_size = [
    128,
    256,
]

[food_02_43]
pos = [
    549,
    242,
]
size = [
    82,
    87,
]
frame_offset = [
    20,
    134,
]
frame_size = [
    128,
    256,
]

[food_02_44]
pos = [
    245,
    510,
]
size = [
    77,
    89,
]
frame_offset = [
    24,
    128,
]
frame_size = [
    128,
    256,
]

[food_02_45]
pos = [
    108,
    0,
]
size = [
    102,
    88,
]
frame_offset = [
    23,
    127,
]
frame_size = [
    128,
    256,
]

[food_02_46]
pos = [
    0,
    0,
]
size = [
    106,
    116,
]
frame_offset = [
    6,
    113,
]
frame_size = [
    128,
    256,
]

[food_02_47]
pos = [
    245,
    601,
]
size = [
    75,
    90,
]
frame_offset = [
    20,
    134,
]
frame_size = [
    128,
    256,
]

[food_02_48]
pos = [
    304,
    0,
]
size = [
    89,
    114,
]
frame_offset = [
    27,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_49]
pos = [
    108,
    90,
]
size = [
    90,
    115,
]
frame_offset = [
    22,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_50]
pos = [
    447,
    847,
]
size = [
    63,
    124,
]
frame_offset = [
    25,
    93,
]
frame_size = [
    128,
    256,
]

[food_02_51]
pos = [
    607,
    711,
]
size = [
    63,
    124,
]
frame_offset = [
    38,
    93,
]
frame_size = [
    128,
    256,
]

[food_02_52]
pos = [
    212,
    0,
]
size = [
    90,
    115,
]
frame_offset = [
    14,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_53]
pos = [
    200,
    117,
]
size = [
    89,
    114,
]
frame_offset = [
    10,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_54]
pos = [
    712,
    932,
]
size = [
    40,
    86,
]
frame_offset = [
    35,
    112,
]
frame_size = [
    128,
    256,
]

[food_02_55]
pos = [
    827,
    849,
]
size = [
    40,
    86,
]
frame_offset = [
    51,
    112,
]
frame_size = [
    128,
    256,
]

[food_02_56]
pos = [
    382,
    116,
]
size = [
    88,
    118,
]
frame_offset = [
    27,
    93,
]
frame_size = [
    128,
    256,
]

[food_02_57]
pos = [
    631,
    351,
]
size = [
    79,
    119,
]
frame_offset = [
    32,
    95,
]
frame_size = [
    128,
    256,
]

[food_02_58]
pos = [
    395,
    709,
]
size = [
    68,
    124,
]
frame_offset = [
    26,
    93,
]
frame_size = [
    128,
    256,
]

[food_02_59]
pos = [
    800,
    656,
]
size = [
    51,
    124,
]
frame_offset = [
    38,
    93,
]
frame_size = [
    128,
    256,
]

[food_02_60]
pos = [
    0,
    118,
]
size = [
    92,
    113,
]
frame_offset = [
    12,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_61]
pos = [
    395,
    0,
]
size = [
    89,
    114,
]
frame_offset = [
    10,
    97,
]
frame_size = [
    128,
    256,
]

[food_02_62]
pos = [
    944,
    813,
]
size = [
    40,
    86,
]
frame_offset = [
    35,
    112,
]
frame_size = [
    128,
    256,
]

[food_02_63]
pos = [
    569,
    541,
]
size = [
    31,
    83,
]
frame_offset = [
    51,
    115,
]
frame_size = [
    128,
    256,
]

[food_02_64]
pos = [
    465,
    240,
]
size = [
    82,
    170,
]
frame_offset = [
    28,
    61,
]
frame_size = [
    128,
    256,
]

[food_02_65]
pos = [
    739,
    637,
]
size = [
    59,
    139,
]
frame_offset = [
    28,
    91,
]
frame_size = [
    128,
    256,
]

[food_02_66]
pos = [
    898,
    512,
]
size = [
    59,
    139,
]
frame_offset = [
    39,
    91,
]
frame_size = [
    128,
    256,
]

[food_02_67]
pos = [
    745,
    0,
]
size = [
    82,
    170,
]
frame_offset = [
    16,
    61,
]
frame_size = [
    128,
    256,
]

[food_02_68]
pos = [
    797,
    352,
]
size = [
    78,
    155,
]
frame_offset = [
    33,
    61,
]
frame_size = [
    128,
    256,
]

[food_02_69]
pos = [
    540,
    780,
]
size = [
    62,
    130,
]
frame_offset = [
    29,
    91,
]
frame_size = [
    128,
    256,
]

[food_02_70]
pos = [
    672,
    725,
]
size = [
    60,
    138,
]
frame_offset = [
    37,
    92,
]
frame_size = [
    128,
    256,
]

[food_02_71]
pos = [
    549,
    331,
]
size = [
    80,
    164,
]
frame_offset = [
    16,
    61,
]
frame_size = [
    128,
    256,
]

[food_02_72]
pos = [
    712,
    426,
]
size = [
    79,
    48,
]
frame_offset = [
    21,
    165,
]
frame_size = [
    128,
    256,
]

[food_02_73]
pos = [
    0,
    463,
]
size = [
    84,
    43,
]
frame_offset = [
    18,
    168,
]
frame_size = [
    128,
    256,
]

[food_02_74]
pos = [
    497,
    497,
]
size = [
    65,
    42,
]
frame_offset = [
    18,
    169,
]
frame_size = [
    128,
    256,
]

[food_02_75]
pos = [
    564,
    497,
]
size = [
    65,
    42,
]
frame_offset = [
    43,
    169,
]
frame_size = [
    128,
    256,
]

[food_02_76]
pos = [
    177,
    454,
]
size = [
    84,
    43,
]
frame_offset = [
    24,
    168,
]
frame_size = [
    128,
    256,
]

[food_02_77]
pos = [
    906,
    254,
]
size = [
    79,
    48,
]
frame_offset = [
    26,
    165,
]
frame_size = [
    128,
    256,
]

[food_02_78]
pos = [
    344,
    475,
]
size = [
    75,
    112,
]
frame_offset = [
    44,
    51,
]
frame_size = [
    128,
    256,
]

[food_02_79]
pos = [
    77,
    876,
]
size = [
    73,
    112,
]
frame_offset = [
    9,
    51,
]
frame_size = [
    128,
    256,
]

[food_02_8]
pos = [
    155,
    817,
]
size = [
    73,
    94,
]
frame_offset = [
    25,
    143,
]
frame_size = [
    128,
    256,
]

[food_02_80]
pos = [
    159,
    608,
]
size = [
    77,
    45,
]
frame_offset = [
    21,
    165,
]
frame_size = [
    128,
    256,
]

[food_02_81]
pos = [
    659,
    91,
]
size = [
    82,
    140,
]
frame_offset = [
    20,
    73,
]
frame_size = [
    128,
    256,
]

[food_02_82]
pos = [
    357,
    976,
]
size = [
    60,
    41,
]
frame_offset = [
    23,
    170,
]
frame_size = [
    128,
    256,
]

[food_02_83]
pos = [
    301,
    912,
]
size = [
    64,
    38,
]
frame_offset = [
    44,
    170,
]
frame_size = [
    128,
    256,
]

[food_02_84]
pos = [
    472,
    201,
]
size = [
    84,
    37,
]
frame_offset = [
    24,
    169,
]
frame_size = [
    128,
    256,
]

[food_02_85]
pos = [
    152,
    913,
]
size = [
    71,
    53,
]
frame_offset = [
    26,
    160,
]
frame_size = [
    128,
    256,
]

[food_02_86]
pos = [
    159,
    655,
]
size = [
    76,
    113,
]
frame_offset = [
    45,
    51,
]
frame_size = [
    128,
    256,
]

[food_02_87]
pos = [
    311,
    799,
]
size = [
    68,
    111,
]
frame_offset = [
    12,
    51,
]
frame_size = [
    128,
    256,
]

[food_02_88]
pos = [
    992,
    141,
]
size = [
    29,
    109,
]
frame_offset = [
    46,
    113,
]
frame_size = [
    128,
    256,
]

[food_02_89]
pos = [
    902,
    653,
]
size = [
    46,
    122,
]
frame_offset = [
    17,
    95,
]
frame_size = [
    128,
    256,
]

[food_02_9]
pos = [
    829,
    136,
]
size = [
    80,
    106,
]
frame_offset = [
    21,
    132,
]
frame_size = [
    128,
    256,
]

[food_02_90]
pos = [
    734,
    778,
]
size = [
    46,
    152,
]
frame_offset = [
    65,
    96,
]
frame_size = [
    128,
    256,
]

[food_02_91]
pos = [
    987,
    254,
]
size = [
    29,
    109,
]
frame_offset = [
    53,
    114,
]
frame_size = [
    128,
    256,
]

[food_02_92]
pos = [
    994,
    0,
]
size = [
    28,
    107,
]
frame_offset = [
    47,
    113,
]
frame_size = [
    128,
    256,
]

[food_02_93]
pos = [
    853,
    725,
]
size = [
    46,
    122,
]
frame_offset = [
    17,
    95,
]
frame_size = [
    128,
    256,
]

[food_02_94]
pos = [
    664,
    865,
]
size = [
    46,
    152,
]
frame_offset = [
    65,
    96,
]
frame_size = [
    128,
    256,
]

[food_02_95]
pos = [
    877,
    352,
]
size = [
    27,
    106,
]
frame_offset = [
    53,
    117,
]
frame_size = [
    128,
    256,
]

[food_02_96]
pos = [
    0,
    233,
]
size = [
    88,
    109,
]
frame_offset = [
    38,
    68,
]
frame_size = [
    128,
    256,
]

[food_02_97]
pos = [
    94,
    207,
]
size = [
    88,
    108,
]
frame_offset = [
    0,
    69,
]
frame_size = [
    128,
    256,
]

[food_02_98]
pos = [
    486,
    90,
]
size = [
    84,
    109,
]
frame_offset = [
    44,
    52,
]
frame_size = [
    128,
    256,
]

[food_02_99]
pos = [
    572,
    132,
]
size = [
    83,
    108,
]
frame_offset = [
    0,
    52,
]
frame_size = [
    128,
    256,
]
