[location_community_church_small_01_100]
pos = [
    0,
    0,
]
size = [
    122,
    126,
]
frame_offset = [
    0,
    121,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_101]
pos = [
    123,
    209,
]
size = [
    89,
    113,
]
frame_offset = [
    0,
    135,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_102]
pos = [
    0,
    934,
]
size = [
    43,
    38,
]
frame_offset = [
    23,
    10,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_103]
pos = [
    66,
    682,
]
size = [
    64,
    53,
]
frame_offset = [
    2,
    10,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_104]
pos = [
    258,
    292,
]
size = [
    40,
    38,
]
frame_offset = [
    26,
    162,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_105]
pos = [
    136,
    666,
]
size = [
    64,
    48,
]
frame_offset = [
    2,
    163,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_106]
pos = [
    385,
    396,
]
size = [
    64,
    52,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_107]
pos = [
    338,
    459,
]
size = [
    64,
    49,
]
frame_offset = [
    2,
    165,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_108]
pos = [
    272,
    514,
]
size = [
    64,
    52,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_109]
pos = [
    258,
    332,
]
size = [
    35,
    35,
]
frame_offset = [
    2,
    178,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_110]
pos = [
    272,
    459,
]
size = [
    64,
    53,
]
frame_offset = [
    2,
    10,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_111]
pos = [
    0,
    974,
]
size = [
    41,
    34,
]
frame_offset = [
    2,
    26,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_112]
pos = [
    402,
    696,
]
size = [
    62,
    182,
]
frame_offset = [
    2,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_113]
pos = [
    791,
    456,
]
size = [
    62,
    181,
]
frame_offset = [
    62,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_114]
pos = [
    534,
    575,
]
size = [
    62,
    182,
]
frame_offset = [
    2,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_115]
pos = [
    598,
    679,
]
size = [
    62,
    181,
]
frame_offset = [
    62,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_116]
pos = [
    663,
    456,
]
size = [
    62,
    182,
]
frame_offset = [
    2,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_117]
pos = [
    530,
    759,
]
size = [
    62,
    181,
]
frame_offset = [
    62,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_118]
pos = [
    466,
    696,
]
size = [
    62,
    182,
]
frame_offset = [
    2,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_119]
pos = [
    663,
    640,
]
size = [
    62,
    181,
]
frame_offset = [
    62,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_120]
pos = [
    338,
    510,
]
size = [
    63,
    119,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_121]
pos = [
    403,
    580,
]
size = [
    63,
    114,
]
frame_offset = [
    61,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_122]
pos = [
    132,
    716,
]
size = [
    63,
    119,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_123]
pos = [
    131,
    837,
]
size = [
    63,
    115,
]
frame_offset = [
    61,
    3,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_124]
pos = [
    404,
    459,
]
size = [
    63,
    119,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_125]
pos = [
    197,
    787,
]
size = [
    63,
    114,
]
frame_offset = [
    61,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_126]
pos = [
    202,
    666,
]
size = [
    63,
    119,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_127]
pos = [
    534,
    459,
]
size = [
    63,
    114,
]
frame_offset = [
    61,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_128]
pos = [
    536,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_129]
pos = [
    604,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_130]
pos = [
    672,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_131]
pos = [
    460,
    231,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_132]
pos = [
    740,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_133]
pos = [
    528,
    231,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_134]
pos = [
    808,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_135]
pos = [
    596,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_136]
pos = [
    876,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_137]
pos = [
    664,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_138]
pos = [
    944,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_139]
pos = [
    732,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_140]
pos = [
    800,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_141]
pos = [
    868,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_142]
pos = [
    936,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_143]
pos = [
    0,
    454,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_144]
pos = [
    68,
    454,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_145]
pos = [
    136,
    438,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_146]
pos = [
    204,
    437,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_67]
pos = [
    791,
    639,
]
size = [
    54,
    181,
]
frame_offset = [
    26,
    47,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_68]
pos = [
    771,
    836,
]
size = [
    51,
    179,
]
frame_offset = [
    16,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_69]
pos = [
    902,
    681,
]
size = [
    52,
    179,
]
frame_offset = [
    59,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_70]
pos = [
    662,
    823,
]
size = [
    53,
    189,
]
frame_offset = [
    16,
    63,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_71]
pos = [
    717,
    836,
]
size = [
    52,
    182,
]
frame_offset = [
    58,
    62,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_72]
pos = [
    727,
    456,
]
size = [
    62,
    182,
]
frame_offset = [
    2,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_73]
pos = [
    855,
    456,
]
size = [
    62,
    181,
]
frame_offset = [
    62,
    40,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_74]
pos = [
    300,
    229,
]
size = [
    83,
    228,
]
frame_offset = [
    41,
    20,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_75]
pos = [
    599,
    456,
]
size = [
    62,
    221,
]
frame_offset = [
    60,
    6,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_76]
pos = [
    0,
    682,
]
size = [
    64,
    250,
]
frame_offset = [
    56,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_77]
pos = [
    272,
    568,
]
size = [
    63,
    208,
]
frame_offset = [
    57,
    21,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_78]
pos = [
    262,
    787,
]
size = [
    62,
    225,
]
frame_offset = [
    58,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_79]
pos = [
    847,
    639,
]
size = [
    53,
    221,
]
frame_offset = [
    36,
    15,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_80]
pos = [
    469,
    459,
]
size = [
    63,
    119,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_81]
pos = [
    468,
    580,
]
size = [
    63,
    114,
]
frame_offset = [
    61,
    4,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_82]
pos = [
    337,
    631,
]
size = [
    63,
    119,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_83]
pos = [
    93,
    256,
]
size = [
    18,
    33,
]
frame_offset = [
    74,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_84]
pos = [
    919,
    456,
]
size = [
    60,
    223,
]
frame_offset = [
    6,
    6,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_85]
pos = [
    337,
    752,
]
size = [
    62,
    206,
]
frame_offset = [
    5,
    23,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_86]
pos = [
    727,
    640,
]
size = [
    61,
    194,
]
frame_offset = [
    6,
    6,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_87]
pos = [
    463,
    0,
]
size = [
    71,
    229,
]
frame_offset = [
    26,
    16,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_88]
pos = [
    401,
    880,
]
size = [
    57,
    130,
]
frame_offset = [
    35,
    122,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_89]
pos = [
    247,
    0,
]
size = [
    111,
    198,
]
frame_offset = [
    17,
    58,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_90]
pos = [
    385,
    229,
]
size = [
    73,
    165,
]
frame_offset = [
    36,
    82,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_91]
pos = [
    0,
    371,
]
size = [
    84,
    81,
]
frame_offset = [
    26,
    163,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_92]
pos = [
    214,
    209,
]
size = [
    84,
    81,
]
frame_offset = [
    17,
    164,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_93]
pos = [
    0,
    256,
]
size = [
    91,
    113,
]
frame_offset = [
    35,
    133,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_94]
pos = [
    0,
    128,
]
size = [
    121,
    126,
]
frame_offset = [
    5,
    120,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_95]
pos = [
    177,
    324,
]
size = [
    79,
    111,
]
frame_offset = [
    7,
    120,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_96]
pos = [
    66,
    737,
]
size = [
    63,
    222,
]
frame_offset = [
    29,
    34,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_97]
pos = [
    360,
    0,
]
size = [
    101,
    227,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_98]
pos = [
    124,
    0,
]
size = [
    121,
    207,
]
frame_offset = [
    0,
    33,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_99]
pos = [
    93,
    324,
]
size = [
    82,
    112,
]
frame_offset = [
    38,
    121,
]
frame_size = [
    128,
    256,
]
