[furniture_tables_high_01_44]
pos = [
    852,
    481,
]
size = [
    104,
    117,
]
frame_offset = [
    19,
    136,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_45]
pos = [
    611,
    487,
]
size = [
    109,
    120,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_46]
pos = [
    471,
    702,
]
size = [
    109,
    120,
]
frame_offset = [
    17,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_47]
pos = [
    582,
    815,
]
size = [
    104,
    117,
]
frame_offset = [
    3,
    136,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_48]
pos = [
    237,
    730,
]
size = [
    113,
    107,
]
frame_offset = [
    13,
    143,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_49]
pos = [
    878,
    0,
]
size = [
    119,
    108,
]
frame_offset = [
    1,
    146,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_50]
pos = [
    631,
    253,
]
size = [
    119,
    108,
]
frame_offset = [
    6,
    146,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_51]
pos = [
    356,
    615,
]
size = [
    113,
    107,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_52]
pos = [
    0,
    621,
]
size = [
    117,
    112,
]
frame_offset = [
    9,
    141,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_53]
pos = [
    0,
    849,
]
size = [
    116,
    112,
]
frame_offset = [
    1,
    137,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_54]
pos = [
    119,
    607,
]
size = [
    117,
    112,
]
frame_offset = [
    9,
    137,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_55]
pos = [
    0,
    735,
]
size = [
    117,
    112,
]
frame_offset = [
    2,
    141,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_56]
pos = [
    254,
    254,
]
size = [
    122,
    111,
]
frame_offset = [
    5,
    142,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_57]
pos = [
    362,
    503,
]
size = [
    116,
    110,
]
frame_offset = [
    0,
    139,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_58]
pos = [
    243,
    494,
]
size = [
    117,
    111,
]
frame_offset = [
    9,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_59]
pos = [
    512,
    121,
]
size = [
    121,
    111,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_60]
pos = [
    622,
    363,
]
size = [
    118,
    122,
]
frame_offset = [
    10,
    133,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_61]
pos = [
    757,
    0,
]
size = [
    119,
    203,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_62]
pos = [
    378,
    254,
]
size = [
    121,
    124,
]
frame_offset = [
    7,
    127,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_01_63]
pos = [
    119,
    721,
]
size = [
    116,
    122,
]
frame_offset = [
    0,
    133,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_0]
pos = [
    635,
    127,
]
size = [
    119,
    124,
]
frame_offset = [
    7,
    132,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_1]
pos = [
    258,
    0,
]
size = [
    125,
    125,
]
frame_offset = [
    0,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_10]
pos = [
    0,
    499,
]
size = [
    117,
    120,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_11]
pos = [
    372,
    380,
]
size = [
    121,
    121,
]
frame_offset = [
    5,
    131,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_12]
pos = [
    0,
    0,
]
size = [
    127,
    126,
]
frame_offset = [
    0,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_13]
pos = [
    238,
    607,
]
size = [
    116,
    121,
]
frame_offset = [
    0,
    134,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_14]
pos = [
    512,
    0,
]
size = [
    121,
    119,
]
frame_offset = [
    3,
    132,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_15]
pos = [
    480,
    584,
]
size = [
    111,
    116,
]
frame_offset = [
    1,
    137,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_16]
pos = [
    509,
    234,
]
size = [
    120,
    114,
]
frame_offset = [
    7,
    141,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_17]
pos = [
    129,
    127,
]
size = [
    126,
    118,
]
frame_offset = [
    0,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_18]
pos = [
    125,
    367,
]
size = [
    122,
    116,
]
frame_offset = [
    1,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_19]
pos = [
    0,
    380,
]
size = [
    122,
    117,
]
frame_offset = [
    5,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_2]
pos = [
    752,
    332,
]
size = [
    118,
    120,
]
frame_offset = [
    0,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_20]
pos = [
    129,
    247,
]
size = [
    123,
    118,
]
frame_offset = [
    3,
    136,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_21]
pos = [
    501,
    350,
]
size = [
    119,
    115,
]
frame_offset = [
    1,
    139,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_22]
pos = [
    702,
    609,
]
size = [
    106,
    243,
]
frame_offset = [
    18,
    8,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_23]
pos = [
    0,
    963,
]
size = [
    110,
    53,
]
frame_offset = [
    8,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_24]
pos = [
    468,
    824,
]
size = [
    106,
    118,
]
frame_offset = [
    15,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_25]
pos = [
    384,
    127,
]
size = [
    123,
    124,
]
frame_offset = [
    0,
    129,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_26]
pos = [
    356,
    724,
]
size = [
    110,
    119,
]
frame_offset = [
    0,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_27]
pos = [
    351,
    845,
]
size = [
    108,
    120,
]
frame_offset = [
    16,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_28]
pos = [
    249,
    367,
]
size = [
    121,
    125,
]
frame_offset = [
    3,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_29]
pos = [
    593,
    609,
]
size = [
    107,
    119,
]
frame_offset = [
    3,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_3]
pos = [
    0,
    256,
]
size = [
    123,
    122,
]
frame_offset = [
    4,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_30]
pos = [
    756,
    205,
]
size = [
    118,
    125,
]
frame_offset = [
    2,
    123,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_31]
pos = [
    237,
    839,
]
size = [
    112,
    126,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_32]
pos = [
    878,
    110,
]
size = [
    118,
    123,
]
frame_offset = [
    7,
    133,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_33]
pos = [
    129,
    0,
]
size = [
    127,
    125,
]
frame_offset = [
    0,
    131,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_34]
pos = [
    124,
    485,
]
size = [
    117,
    120,
]
frame_offset = [
    1,
    131,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_35]
pos = [
    876,
    235,
]
size = [
    118,
    120,
]
frame_offset = [
    7,
    131,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_36]
pos = [
    0,
    128,
]
size = [
    127,
    126,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_37]
pos = [
    872,
    357,
]
size = [
    117,
    122,
]
frame_offset = [
    1,
    133,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_4]
pos = [
    257,
    127,
]
size = [
    125,
    125,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_40]
pos = [
    125,
    256,
]
size = [
    1,
    1,
]
frame_offset = [
    63,
    0,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_41]
pos = [
    125,
    259,
]
size = [
    1,
    1,
]
frame_offset = [
    64,
    0,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_5]
pos = [
    119,
    845,
]
size = [
    114,
    121,
]
frame_offset = [
    1,
    134,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_6]
pos = [
    495,
    467,
]
size = [
    114,
    115,
]
frame_offset = [
    14,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_7]
pos = [
    722,
    539,
]
size = [
    107,
    53,
]
frame_offset = [
    10,
    143,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_8]
pos = [
    635,
    0,
]
size = [
    120,
    125,
]
frame_offset = [
    7,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_tables_high_02_9]
pos = [
    385,
    0,
]
size = [
    125,
    125,
]
frame_offset = [
    2,
    129,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_0]
pos = [
    582,
    730,
]
size = [
    105,
    83,
]
frame_offset = [
    18,
    165,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_1]
pos = [
    810,
    687,
]
size = [
    102,
    84,
]
frame_offset = [
    8,
    169,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_10]
pos = [
    914,
    686,
]
size = [
    86,
    81,
]
frame_offset = [
    26,
    159,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_11]
pos = [
    676,
    939,
]
size = [
    85,
    75,
]
frame_offset = [
    0,
    172,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_12]
pos = [
    914,
    600,
]
size = [
    98,
    84,
]
frame_offset = [
    14,
    166,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_13]
pos = [
    688,
    854,
]
size = [
    98,
    83,
]
frame_offset = [
    13,
    166,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_14]
pos = [
    810,
    600,
]
size = [
    102,
    85,
]
frame_offset = [
    18,
    168,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_15]
pos = [
    742,
    454,
]
size = [
    108,
    83,
]
frame_offset = [
    3,
    165,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_16]
pos = [
    576,
    934,
]
size = [
    98,
    84,
]
frame_offset = [
    14,
    165,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_2]
pos = [
    899,
    773,
]
size = [
    76,
    65,
]
frame_offset = [
    28,
    179,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_3]
pos = [
    461,
    944,
]
size = [
    88,
    66,
]
frame_offset = [
    14,
    178,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_4]
pos = [
    839,
    936,
]
size = [
    70,
    60,
]
frame_offset = [
    40,
    188,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_5]
pos = [
    763,
    939,
]
size = [
    74,
    65,
]
frame_offset = [
    13,
    173,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_6]
pos = [
    876,
    850,
]
size = [
    74,
    64,
]
frame_offset = [
    39,
    174,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_7]
pos = [
    911,
    916,
]
size = [
    70,
    60,
]
frame_offset = [
    16,
    188,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_8]
pos = [
    810,
    773,
]
size = [
    87,
    75,
]
frame_offset = [
    41,
    172,
]
frame_size = [
    128,
    256,
]

[furniture_tables_low_01_9]
pos = [
    788,
    854,
]
size = [
    86,
    80,
]
frame_offset = [
    14,
    160,
]
frame_size = [
    128,
    256,
]
