[roofs_05_100]
pos = [
    650,
    327,
]
size = [
    128,
    86,
]
frame_offset = [
    0,
    140,
]
frame_size = [
    128,
    256,
]

[roofs_05_101]
pos = [
    130,
    859,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_102]
pos = [
    780,
    201,
]
size = [
    128,
    86,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[roofs_05_103]
pos = [
    260,
    590,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_104]
pos = [
    0,
    331,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_05_105]
pos = [
    260,
    137,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_05_106]
pos = [
    0,
    195,
]
size = [
    128,
    134,
]
frame_offset = [
    0,
    122,
]
frame_size = [
    128,
    256,
]

[roofs_05_107]
pos = [
    260,
    0,
]
size = [
    128,
    135,
]
frame_offset = [
    0,
    58,
]
frame_size = [
    128,
    256,
]

[roofs_05_108]
pos = [
    390,
    759,
]
size = [
    126,
    130,
]
frame_offset = [
    2,
    62,
]
frame_size = [
    128,
    256,
]

[roofs_05_109]
pos = [
    390,
    133,
]
size = [
    128,
    130,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_05_110]
pos = [
    648,
    675,
]
size = [
    124,
    137,
]
frame_offset = [
    0,
    55,
]
frame_size = [
    128,
    256,
]

[roofs_05_111]
pos = [
    778,
    560,
]
size = [
    124,
    137,
]
frame_offset = [
    0,
    119,
]
frame_size = [
    128,
    256,
]

[roofs_05_112]
pos = [
    390,
    495,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_113]
pos = [
    260,
    901,
]
size = [
    126,
    83,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_114]
pos = [
    260,
    760,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_115]
pos = [
    130,
    906,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[roofs_05_116]
pos = [
    520,
    527,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[roofs_05_117]
pos = [
    390,
    665,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_118]
pos = [
    650,
    231,
]
size = [
    128,
    94,
]
frame_offset = [
    0,
    116,
]
frame_size = [
    128,
    256,
]

[roofs_05_119]
pos = [
    0,
    897,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_120]
pos = [
    780,
    464,
]
size = [
    126,
    47,
]
frame_offset = [
    2,
    172,
]
frame_size = [
    128,
    256,
]

[roofs_05_121]
pos = [
    388,
    940,
]
size = [
    124,
    49,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_05_126]
pos = [
    910,
    332,
]
size = [
    89,
    79,
]
frame_offset = [
    39,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_127]
pos = [
    625,
    897,
]
size = [
    87,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_128]
pos = [
    780,
    377,
]
size = [
    128,
    85,
]
frame_offset = [
    0,
    141,
]
frame_size = [
    128,
    256,
]

[roofs_05_129]
pos = [
    0,
    464,
]
size = [
    128,
    85,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_05_130]
pos = [
    260,
    807,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_131]
pos = [
    0,
    551,
]
size = [
    128,
    85,
]
frame_offset = [
    0,
    141,
]
frame_size = [
    128,
    256,
]

[roofs_05_132]
pos = [
    650,
    415,
]
size = [
    128,
    86,
]
frame_offset = [
    0,
    140,
]
frame_size = [
    128,
    256,
]

[roofs_05_133]
pos = [
    130,
    953,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_134]
pos = [
    780,
    289,
]
size = [
    128,
    86,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[roofs_05_135]
pos = [
    130,
    774,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_136]
pos = [
    130,
    296,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_05_137]
pos = [
    260,
    270,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_05_138]
pos = [
    130,
    160,
]
size = [
    128,
    134,
]
frame_offset = [
    0,
    122,
]
frame_size = [
    128,
    256,
]

[roofs_05_38]
pos = [
    774,
    699,
]
size = [
    88,
    79,
]
frame_offset = [
    40,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_39]
pos = [
    904,
    596,
]
size = [
    88,
    66,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_40]
pos = [
    390,
    0,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_05_41]
pos = [
    520,
    0,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_05_42]
pos = [
    650,
    0,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_43]
pos = [
    520,
    133,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_05_44]
pos = [
    130,
    0,
]
size = [
    128,
    158,
]
frame_offset = [
    0,
    34,
]
frame_size = [
    128,
    256,
]

[roofs_05_45]
pos = [
    390,
    265,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_46]
pos = [
    910,
    0,
]
size = [
    98,
    158,
]
frame_offset = [
    30,
    34,
]
frame_size = [
    128,
    256,
]

[roofs_05_47]
pos = [
    518,
    893,
]
size = [
    105,
    81,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[roofs_05_51]
pos = [
    0,
    982,
]
size = [
    3,
    1,
]
frame_offset = [
    62,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_52]
pos = [
    520,
    459,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_53]
pos = [
    824,
    957,
]
size = [
    49,
    45,
]
frame_offset = [
    39,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_56]
pos = [
    260,
    403,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    157,
]
frame_size = [
    128,
    256,
]

[roofs_05_57]
pos = [
    780,
    0,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    93,
]
frame_size = [
    128,
    256,
]

[roofs_05_58]
pos = [
    650,
    130,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[roofs_05_59]
pos = [
    520,
    263,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    30,
]
frame_size = [
    128,
    256,
]

[roofs_05_60]
pos = [
    390,
    395,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_05_61]
pos = [
    780,
    101,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_05_62]
pos = [
    0,
    0,
]
size = [
    128,
    193,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_05_63]
pos = [
    625,
    965,
]
size = [
    46,
    35,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_05_64]
pos = [
    130,
    516,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    172,
]
frame_size = [
    128,
    256,
]

[roofs_05_65]
pos = [
    0,
    725,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    108,
]
frame_size = [
    128,
    256,
]

[roofs_05_66]
pos = [
    130,
    602,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    44,
]
frame_size = [
    128,
    256,
]

[roofs_05_67]
pos = [
    933,
    747,
]
size = [
    67,
    64,
]
frame_offset = [
    30,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_05_68]
pos = [
    933,
    813,
]
size = [
    66,
    81,
]
frame_offset = [
    31,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_05_69]
pos = [
    755,
    848,
]
size = [
    67,
    145,
]
frame_offset = [
    30,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_70]
pos = [
    910,
    160,
]
size = [
    98,
    84,
]
frame_offset = [
    30,
    44,
]
frame_size = [
    128,
    256,
]

[roofs_05_71]
pos = [
    906,
    513,
]
size = [
    105,
    81,
]
frame_offset = [
    0,
    47,
]
frame_size = [
    128,
    256,
]

[roofs_05_72]
pos = [
    260,
    504,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    172,
]
frame_size = [
    128,
    256,
]

[roofs_05_73]
pos = [
    0,
    811,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    108,
]
frame_size = [
    128,
    256,
]

[roofs_05_74]
pos = [
    130,
    688,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    44,
]
frame_size = [
    128,
    256,
]

[roofs_05_75]
pos = [
    864,
    699,
]
size = [
    67,
    256,
]
frame_offset = [
    30,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_76]
pos = [
    933,
    896,
]
size = [
    66,
    81,
]
frame_offset = [
    31,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_05_77]
pos = [
    933,
    664,
]
size = [
    67,
    81,
]
frame_offset = [
    30,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_05_78]
pos = [
    910,
    246,
]
size = [
    98,
    84,
]
frame_offset = [
    30,
    44,
]
frame_size = [
    128,
    256,
]

[roofs_05_79]
pos = [
    648,
    814,
]
size = [
    105,
    81,
]
frame_offset = [
    0,
    47,
]
frame_size = [
    128,
    256,
]

[roofs_05_80]
pos = [
    260,
    675,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_81]
pos = [
    650,
    590,
]
size = [
    126,
    83,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_82]
pos = [
    520,
    574,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_83]
pos = [
    520,
    621,
]
size = [
    126,
    219,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_05_84]
pos = [
    390,
    712,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[roofs_05_85]
pos = [
    778,
    513,
]
size = [
    126,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_86]
pos = [
    520,
    363,
]
size = [
    128,
    94,
]
frame_offset = [
    0,
    116,
]
frame_size = [
    128,
    256,
]

[roofs_05_87]
pos = [
    390,
    580,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_05_88]
pos = [
    390,
    891,
]
size = [
    126,
    47,
]
frame_offset = [
    2,
    172,
]
frame_size = [
    128,
    256,
]

[roofs_05_89]
pos = [
    518,
    842,
]
size = [
    124,
    49,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_05_94]
pos = [
    910,
    413,
]
size = [
    89,
    79,
]
frame_offset = [
    39,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_95]
pos = [
    774,
    780,
]
size = [
    87,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_05_96]
pos = [
    130,
    429,
]
size = [
    128,
    85,
]
frame_offset = [
    0,
    141,
]
frame_size = [
    128,
    256,
]

[roofs_05_97]
pos = [
    650,
    503,
]
size = [
    126,
    85,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_05_98]
pos = [
    260,
    854,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_05_99]
pos = [
    0,
    638,
]
size = [
    128,
    85,
]
frame_offset = [
    0,
    141,
]
frame_size = [
    128,
    256,
]
