[walls_exterior_roofs_09_100]
pos = [
    0,
    164,
]
size = [
    122,
    98,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_101]
pos = [
    688,
    228,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_104]
pos = [
    272,
    496,
]
size = [
    66,
    99,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_105]
pos = [
    923,
    228,
]
size = [
    66,
    163,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_106]
pos = [
    786,
    83,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_107]
pos = [
    506,
    0,
]
size = [
    68,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_108]
pos = [
    0,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_109]
pos = [
    404,
    360,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_110]
pos = [
    124,
    364,
]
size = [
    68,
    115,
]
frame_offset = [
    60,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_111]
pos = [
    855,
    0,
]
size = [
    67,
    51,
]
frame_offset = [
    60,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_112]
pos = [
    202,
    958,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_113]
pos = [
    68,
    879,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_114]
pos = [
    340,
    597,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_115]
pos = [
    136,
    813,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_116]
pos = [
    270,
    874,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_117]
pos = [
    334,
    360,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_118]
pos = [
    136,
    613,
]
size = [
    66,
    115,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_119]
pos = [
    0,
    878,
]
size = [
    66,
    51,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_120]
pos = [
    549,
    328,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_121]
pos = [
    716,
    0,
]
size = [
    68,
    178,
]
frame_offset = [
    60,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_122]
pos = [
    136,
    481,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_123]
pos = [
    672,
    718,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_124]
pos = [
    0,
    264,
]
size = [
    122,
    98,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_125]
pos = [
    696,
    228,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_128]
pos = [
    538,
    866,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_129]
pos = [
    474,
    673,
]
size = [
    64,
    163,
]
frame_offset = [
    2,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_130]
pos = [
    408,
    479,
]
size = [
    64,
    226,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_131]
pos = [
    204,
    730,
]
size = [
    64,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_132]
pos = [
    540,
    702,
]
size = [
    64,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_133]
pos = [
    738,
    839,
]
size = [
    64,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_134]
pos = [
    404,
    901,
]
size = [
    64,
    115,
]
frame_offset = [
    60,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_135]
pos = [
    336,
    971,
]
size = [
    64,
    51,
]
frame_offset = [
    60,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_136]
pos = [
    804,
    899,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_137]
pos = [
    753,
    491,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_138]
pos = [
    272,
    680,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_139]
pos = [
    474,
    479,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_140]
pos = [
    672,
    588,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_141]
pos = [
    936,
    801,
]
size = [
    64,
    64,
]
frame_offset = [
    60,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_142]
pos = [
    738,
    621,
]
size = [
    64,
    115,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_143]
pos = [
    470,
    968,
]
size = [
    64,
    51,
]
frame_offset = [
    2,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_144]
pos = [
    687,
    408,
]
size = [
    64,
    178,
]
frame_offset = [
    2,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_145]
pos = [
    338,
    791,
]
size = [
    64,
    178,
]
frame_offset = [
    60,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_146]
pos = [
    804,
    621,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_147]
pos = [
    606,
    832,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_148]
pos = [
    124,
    164,
]
size = [
    122,
    98,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_149]
pos = [
    704,
    228,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_152]
pos = [
    0,
    931,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_153]
pos = [
    885,
    523,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_154]
pos = [
    951,
    523,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_155]
pos = [
    604,
    933,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_156]
pos = [
    804,
    823,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_157]
pos = [
    536,
    968,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_158]
pos = [
    804,
    965,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_159]
pos = [
    936,
    725,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_39]
pos = [
    136,
    730,
]
size = [
    66,
    81,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_40]
pos = [
    784,
    311,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_41]
pos = [
    390,
    0,
]
size = [
    114,
    178,
]
frame_offset = [
    14,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_42]
pos = [
    0,
    629,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_43]
pos = [
    738,
    738,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_44]
pos = [
    0,
    364,
]
size = [
    122,
    98,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_45]
pos = [
    541,
    396,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_48]
pos = [
    672,
    920,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_49]
pos = [
    672,
    819,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_50]
pos = [
    870,
    624,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_51]
pos = [
    870,
    725,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_52]
pos = [
    738,
    939,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_53]
pos = [
    870,
    951,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_54]
pos = [
    936,
    933,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_55]
pos = [
    870,
    809,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_56]
pos = [
    340,
    496,
]
size = [
    66,
    99,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_57]
pos = [
    0,
    464,
]
size = [
    66,
    163,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_58]
pos = [
    716,
    180,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_59]
pos = [
    576,
    0,
]
size = [
    68,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_60]
pos = [
    130,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_61]
pos = [
    480,
    296,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_62]
pos = [
    194,
    364,
]
size = [
    68,
    115,
]
frame_offset = [
    60,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_63]
pos = [
    786,
    0,
]
size = [
    67,
    81,
]
frame_offset = [
    60,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_64]
pos = [
    870,
    885,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_65]
pos = [
    606,
    702,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_66]
pos = [
    540,
    508,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_67]
pos = [
    619,
    311,
]
size = [
    66,
    193,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_68]
pos = [
    819,
    491,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_69]
pos = [
    480,
    228,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_70]
pos = [
    0,
    761,
]
size = [
    66,
    115,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_71]
pos = [
    272,
    597,
]
size = [
    66,
    81,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_72]
pos = [
    854,
    281,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_73]
pos = [
    248,
    164,
]
size = [
    114,
    178,
]
frame_offset = [
    14,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_74]
pos = [
    204,
    481,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_75]
pos = [
    804,
    722,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_76]
pos = [
    124,
    264,
]
size = [
    122,
    98,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_77]
pos = [
    688,
    299,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_80]
pos = [
    68,
    778,
]
size = [
    66,
    99,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_81]
pos = [
    68,
    481,
]
size = [
    66,
    163,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_82]
pos = [
    855,
    53,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_83]
pos = [
    646,
    0,
]
size = [
    68,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_84]
pos = [
    260,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_85]
pos = [
    550,
    228,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_86]
pos = [
    264,
    344,
]
size = [
    68,
    115,
]
frame_offset = [
    60,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_87]
pos = [
    619,
    228,
]
size = [
    67,
    81,
]
frame_offset = [
    60,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_88]
pos = [
    936,
    867,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_89]
pos = [
    472,
    838,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_90]
pos = [
    606,
    508,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_91]
pos = [
    406,
    707,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_92]
pos = [
    922,
    393,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_93]
pos = [
    334,
    428,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_94]
pos = [
    204,
    613,
]
size = [
    66,
    115,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_95]
pos = [
    473,
    396,
]
size = [
    66,
    81,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_96]
pos = [
    924,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_97]
pos = [
    364,
    180,
]
size = [
    114,
    178,
]
frame_offset = [
    14,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_98]
pos = [
    68,
    646,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_09_99]
pos = [
    936,
    624,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]
