[signs_one-off_03_on_228]
pos = [
    0,
    227,
]
size = [
    64,
    207,
]
frame_offset = [
    60,
    18,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_229]
pos = [
    66,
    596,
]
size = [
    64,
    143,
]
frame_offset = [
    60,
    81,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_230]
pos = [
    812,
    180,
]
size = [
    64,
    168,
]
frame_offset = [
    60,
    53,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_231]
pos = [
    415,
    0,
]
size = [
    65,
    182,
]
frame_offset = [
    60,
    21,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_320]
pos = [
    905,
    832,
]
size = [
    36,
    93,
]
frame_offset = [
    88,
    131,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_321]
pos = [
    198,
    767,
]
size = [
    64,
    104,
]
frame_offset = [
    60,
    116,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_322]
pos = [
    600,
    570,
]
size = [
    64,
    84,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_323]
pos = [
    198,
    654,
]
size = [
    64,
    111,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_324]
pos = [
    402,
    495,
]
size = [
    64,
    108,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_325]
pos = [
    468,
    386,
]
size = [
    64,
    111,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_326]
pos = [
    0,
    865,
]
size = [
    64,
    110,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_327]
pos = [
    905,
    739,
]
size = [
    43,
    91,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_336]
pos = [
    878,
    339,
]
size = [
    64,
    148,
]
frame_offset = [
    60,
    67,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_337]
pos = [
    944,
    330,
]
size = [
    64,
    148,
]
frame_offset = [
    60,
    67,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_338]
pos = [
    132,
    510,
]
size = [
    64,
    145,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_339]
pos = [
    0,
    436,
]
size = [
    64,
    147,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_340]
pos = [
    132,
    772,
]
size = [
    64,
    107,
]
frame_offset = [
    60,
    82,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_341]
pos = [
    264,
    509,
]
size = [
    64,
    113,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_342]
pos = [
    66,
    741,
]
size = [
    64,
    112,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_343]
pos = [
    859,
    637,
]
size = [
    58,
    100,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_349]
pos = [
    589,
    918,
]
size = [
    55,
    79,
]
frame_offset = [
    11,
    129,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_350]
pos = [
    600,
    477,
]
size = [
    64,
    91,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_351]
pos = [
    264,
    833,
]
size = [
    64,
    91,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_357]
pos = [
    0,
    977,
]
size = [
    45,
    40,
]
frame_offset = [
    21,
    159,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_358]
pos = [
    198,
    967,
]
size = [
    64,
    52,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_359]
pos = [
    967,
    659,
]
size = [
    45,
    76,
]
frame_offset = [
    2,
    142,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_365]
pos = [
    66,
    961,
]
size = [
    64,
    60,
]
frame_offset = [
    2,
    153,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_366]
pos = [
    739,
    543,
]
size = [
    64,
    67,
]
frame_offset = [
    2,
    150,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_367]
pos = [
    132,
    979,
]
size = [
    29,
    33,
]
frame_offset = [
    2,
    182,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_388]
pos = [
    890,
    927,
]
size = [
    23,
    89,
]
frame_offset = [
    101,
    79,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_389]
pos = [
    680,
    0,
]
size = [
    64,
    184,
]
frame_offset = [
    60,
    44,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_390]
pos = [
    729,
    730,
]
size = [
    59,
    124,
]
frame_offset = [
    7,
    14,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_391]
pos = [
    347,
    0,
]
size = [
    66,
    135,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_392]
pos = [
    402,
    380,
]
size = [
    64,
    113,
]
frame_offset = [
    2,
    54,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_393]
pos = [
    0,
    733,
]
size = [
    64,
    130,
]
frame_offset = [
    2,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_394]
pos = [
    812,
    350,
]
size = [
    64,
    154,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_395]
pos = [
    66,
    448,
]
size = [
    64,
    146,
]
frame_offset = [
    2,
    61,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_396]
pos = [
    198,
    509,
]
size = [
    64,
    143,
]
frame_offset = [
    2,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_397]
pos = [
    0,
    585,
]
size = [
    64,
    146,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_398]
pos = [
    132,
    358,
]
size = [
    64,
    150,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_399]
pos = [
    277,
    0,
]
size = [
    68,
    129,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_416]
pos = [
    204,
    152,
]
size = [
    64,
    195,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_417]
pos = [
    277,
    131,
]
size = [
    64,
    195,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_418]
pos = [
    134,
    160,
]
size = [
    64,
    196,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_419]
pos = [
    614,
    0,
]
size = [
    64,
    191,
]
frame_offset = [
    60,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_420]
pos = [
    66,
    250,
]
size = [
    64,
    196,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_421]
pos = [
    475,
    195,
]
size = [
    64,
    189,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_422]
pos = [
    200,
    349,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_423]
pos = [
    988,
    792,
]
size = [
    32,
    126,
]
frame_offset = [
    60,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_452]
pos = [
    857,
    739,
]
size = [
    46,
    112,
]
frame_offset = [
    20,
    22,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_453]
pos = [
    534,
    386,
]
size = [
    64,
    107,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_454]
pos = [
    132,
    657,
]
size = [
    64,
    113,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_455]
pos = [
    264,
    624,
]
size = [
    64,
    109,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_469]
pos = [
    330,
    512,
]
size = [
    64,
    112,
]
frame_offset = [
    2,
    32,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_470]
pos = [
    468,
    499,
]
size = [
    64,
    97,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_471]
pos = [
    718,
    955,
]
size = [
    42,
    45,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_488]
pos = [
    848,
    853,
]
size = [
    40,
    162,
]
frame_offset = [
    26,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_489]
pos = [
    409,
    184,
]
size = [
    64,
    194,
]
frame_offset = [
    2,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_490]
pos = [
    548,
    0,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_491]
pos = [
    343,
    137,
]
size = [
    64,
    195,
]
frame_offset = [
    2,
    18,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_492]
pos = [
    541,
    195,
]
size = [
    64,
    184,
]
frame_offset = [
    2,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_493]
pos = [
    482,
    0,
]
size = [
    64,
    193,
]
frame_offset = [
    2,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_03_on_494]
pos = [
    943,
    844,
]
size = [
    30,
    163,
]
frame_offset = [
    3,
    50,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_0]
pos = [
    528,
    833,
]
size = [
    62,
    73,
]
frame_offset = [
    4,
    137,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_1]
pos = [
    330,
    916,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_10]
pos = [
    666,
    636,
]
size = [
    64,
    63,
]
frame_offset = [
    2,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_11]
pos = [
    600,
    656,
]
size = [
    64,
    71,
]
frame_offset = [
    2,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_12]
pos = [
    396,
    881,
]
size = [
    64,
    70,
]
frame_offset = [
    2,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_13]
pos = [
    950,
    792,
]
size = [
    36,
    50,
]
frame_offset = [
    2,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_14]
pos = [
    739,
    366,
]
size = [
    64,
    90,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_15]
pos = [
    600,
    729,
]
size = [
    62,
    187,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_16]
pos = [
    944,
    480,
]
size = [
    61,
    86,
]
frame_offset = [
    5,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_17]
pos = [
    919,
    659,
]
size = [
    46,
    75,
]
frame_offset = [
    2,
    112,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_18]
pos = [
    468,
    598,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_19]
pos = [
    330,
    827,
]
size = [
    64,
    87,
]
frame_offset = [
    2,
    100,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_2]
pos = [
    462,
    692,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    136,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_20]
pos = [
    607,
    379,
]
size = [
    64,
    96,
]
frame_offset = [
    2,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_21]
pos = [
    673,
    366,
]
size = [
    64,
    94,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_22]
pos = [
    264,
    926,
]
size = [
    64,
    83,
]
frame_offset = [
    2,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_23]
pos = [
    0,
    0,
]
size = [
    126,
    133,
]
frame_offset = [
    2,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_24]
pos = [
    264,
    735,
]
size = [
    64,
    96,
]
frame_offset = [
    2,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_25]
pos = [
    534,
    495,
]
size = [
    64,
    95,
]
frame_offset = [
    2,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_26]
pos = [
    396,
    605,
]
size = [
    64,
    96,
]
frame_offset = [
    2,
    92,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_27]
pos = [
    534,
    592,
]
size = [
    64,
    89,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_28]
pos = [
    67,
    160,
]
size = [
    65,
    88,
]
frame_offset = [
    1,
    9,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_29]
pos = [
    66,
    855,
]
size = [
    64,
    104,
]
frame_offset = [
    2,
    9,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_3]
pos = [
    534,
    683,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    137,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_30]
pos = [
    330,
    626,
]
size = [
    64,
    104,
]
frame_offset = [
    2,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_31]
pos = [
    726,
    856,
]
size = [
    47,
    97,
]
frame_offset = [
    2,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_32]
pos = [
    878,
    489,
]
size = [
    61,
    146,
]
frame_offset = [
    53,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_33]
pos = [
    944,
    0,
]
size = [
    64,
    172,
]
frame_offset = [
    50,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_34]
pos = [
    746,
    0,
]
size = [
    64,
    183,
]
frame_offset = [
    50,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_35]
pos = [
    128,
    0,
]
size = [
    74,
    158,
]
frame_offset = [
    50,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_36]
pos = [
    944,
    174,
]
size = [
    64,
    154,
]
frame_offset = [
    2,
    39,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_37]
pos = [
    607,
    194,
]
size = [
    64,
    183,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_38]
pos = [
    336,
    334,
]
size = [
    64,
    176,
]
frame_offset = [
    2,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_39]
pos = [
    204,
    0,
]
size = [
    71,
    150,
]
frame_offset = [
    2,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_4]
pos = [
    666,
    553,
]
size = [
    64,
    81,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_40]
pos = [
    805,
    506,
]
size = [
    63,
    96,
]
frame_offset = [
    3,
    52,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_41]
pos = [
    0,
    135,
]
size = [
    65,
    90,
]
frame_offset = [
    2,
    69,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_42]
pos = [
    673,
    462,
]
size = [
    64,
    89,
]
frame_offset = [
    60,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_43]
pos = [
    132,
    881,
]
size = [
    64,
    96,
]
frame_offset = [
    60,
    52,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_44]
pos = [
    664,
    793,
]
size = [
    60,
    76,
]
frame_offset = [
    64,
    65,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_45]
pos = [
    527,
    908,
]
size = [
    60,
    78,
]
frame_offset = [
    60,
    50,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_46]
pos = [
    796,
    704,
]
size = [
    59,
    89,
]
frame_offset = [
    7,
    52,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_47]
pos = [
    666,
    701,
]
size = [
    61,
    90,
]
frame_offset = [
    2,
    54,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_48]
pos = [
    396,
    953,
]
size = [
    47,
    51,
]
frame_offset = [
    77,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_49]
pos = [
    462,
    778,
]
size = [
    64,
    80,
]
frame_offset = [
    60,
    35,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_5]
pos = [
    396,
    796,
]
size = [
    64,
    83,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_50]
pos = [
    198,
    873,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_51]
pos = [
    396,
    703,
]
size = [
    64,
    91,
]
frame_offset = [
    60,
    27,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_52]
pos = [
    330,
    732,
]
size = [
    64,
    93,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_53]
pos = [
    445,
    953,
]
size = [
    46,
    50,
]
frame_offset = [
    60,
    58,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_54]
pos = [
    941,
    568,
]
size = [
    59,
    89,
]
frame_offset = [
    7,
    132,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_55]
pos = [
    796,
    612,
]
size = [
    61,
    90,
]
frame_offset = [
    2,
    134,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_56]
pos = [
    790,
    795,
]
size = [
    56,
    170,
]
frame_offset = [
    10,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_57]
pos = [
    812,
    0,
]
size = [
    64,
    178,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_58]
pos = [
    680,
    186,
]
size = [
    64,
    178,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_59]
pos = [
    270,
    328,
]
size = [
    64,
    179,
]
frame_offset = [
    2,
    44,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_6]
pos = [
    739,
    458,
]
size = [
    64,
    83,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_60]
pos = [
    878,
    0,
]
size = [
    64,
    177,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_61]
pos = [
    746,
    185,
]
size = [
    64,
    177,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_62]
pos = [
    878,
    179,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    64,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_63]
pos = [
    462,
    860,
]
size = [
    63,
    90,
]
frame_offset = [
    2,
    132,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_64]
pos = [
    664,
    871,
]
size = [
    52,
    137,
]
frame_offset = [
    72,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_7]
pos = [
    732,
    612,
]
size = [
    62,
    116,
]
frame_offset = [
    2,
    140,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_8]
pos = [
    950,
    737,
]
size = [
    41,
    53,
]
frame_offset = [
    25,
    7,
]
frame_size = [
    128,
    256,
]

[signs_one-off_04_9]
pos = [
    528,
    767,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    10,
]
frame_size = [
    128,
    256,
]
