[fencing_damaged_01b_104]
pos = [
    252,
    190,
]
size = [
    122,
    100,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_105]
pos = [
    0,
    420,
]
size = [
    122,
    90,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_106]
pos = [
    0,
    0,
]
size = [
    125,
    76,
]
frame_offset = [
    1,
    148,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_107]
pos = [
    252,
    132,
]
size = [
    123,
    56,
]
frame_offset = [
    2,
    170,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_108]
pos = [
    125,
    330,
]
size = [
    122,
    80,
]
frame_offset = [
    2,
    145,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_109]
pos = [
    0,
    342,
]
size = [
    123,
    76,
]
frame_offset = [
    2,
    148,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_110]
pos = [
    126,
    132,
]
size = [
    124,
    64,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_112]
pos = [
    376,
    222,
]
size = [
    98,
    44,
]
frame_offset = [
    10,
    202,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_113]
pos = [
    579,
    171,
]
size = [
    89,
    49,
]
frame_offset = [
    21,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_114]
pos = [
    451,
    293,
]
size = [
    89,
    49,
]
frame_offset = [
    16,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_115]
pos = [
    249,
    349,
]
size = [
    98,
    44,
]
frame_offset = [
    18,
    202,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_116]
pos = [
    673,
    112,
]
size = [
    85,
    62,
]
frame_offset = [
    20,
    185,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_117]
pos = [
    352,
    340,
]
size = [
    96,
    45,
]
frame_offset = [
    14,
    200,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_118]
pos = [
    352,
    292,
]
size = [
    97,
    46,
]
frame_offset = [
    16,
    200,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_119]
pos = [
    450,
    344,
]
size = [
    85,
    61,
]
frame_offset = [
    21,
    185,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_120]
pos = [
    601,
    0,
]
size = [
    93,
    55,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_121]
pos = [
    325,
    395,
]
size = [
    95,
    57,
]
frame_offset = [
    9,
    195,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_122]
pos = [
    504,
    0,
]
size = [
    95,
    57,
]
frame_offset = [
    22,
    195,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_123]
pos = [
    504,
    59,
]
size = [
    93,
    56,
]
frame_offset = [
    14,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_124]
pos = [
    125,
    412,
]
size = [
    99,
    56,
]
frame_offset = [
    9,
    193,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_125]
pos = [
    325,
    454,
]
size = [
    86,
    55,
]
frame_offset = [
    15,
    199,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_126]
pos = [
    790,
    0,
]
size = [
    86,
    55,
]
frame_offset = [
    25,
    199,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_127]
pos = [
    251,
    292,
]
size = [
    99,
    55,
]
frame_offset = [
    18,
    193,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_128]
pos = [
    484,
    185,
]
size = [
    92,
    52,
]
frame_offset = [
    15,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_129]
pos = [
    578,
    222,
]
size = [
    85,
    53,
]
frame_offset = [
    24,
    195,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_130]
pos = [
    542,
    293,
]
size = [
    83,
    53,
]
frame_offset = [
    19,
    195,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_131]
pos = [
    696,
    0,
]
size = [
    92,
    52,
]
frame_offset = [
    19,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_132]
pos = [
    484,
    132,
]
size = [
    93,
    51,
]
frame_offset = [
    20,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_133]
pos = [
    760,
    112,
]
size = [
    83,
    51,
]
frame_offset = [
    17,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_134]
pos = [
    422,
    407,
]
size = [
    83,
    52,
]
frame_offset = [
    26,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_135]
pos = [
    599,
    59,
]
size = [
    93,
    51,
]
frame_offset = [
    13,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_136]
pos = [
    68,
    710,
]
size = [
    66,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_137]
pos = [
    507,
    407,
]
size = [
    65,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_138]
pos = [
    407,
    623,
]
size = [
    65,
    121,
]
frame_offset = [
    59,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_139]
pos = [
    614,
    556,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    99,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_140]
pos = [
    480,
    540,
]
size = [
    65,
    121,
]
frame_offset = [
    2,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_141]
pos = [
    272,
    644,
]
size = [
    65,
    131,
]
frame_offset = [
    2,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_142]
pos = [
    0,
    78,
]
size = [
    124,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_143]
pos = [
    379,
    0,
]
size = [
    123,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_144]
pos = [
    136,
    662,
]
size = [
    66,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_145]
pos = [
    136,
    795,
]
size = [
    65,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_146]
pos = [
    271,
    777,
]
size = [
    65,
    121,
]
frame_offset = [
    59,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_147]
pos = [
    540,
    663,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    99,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_148]
pos = [
    547,
    540,
]
size = [
    65,
    121,
]
frame_offset = [
    2,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_149]
pos = [
    204,
    759,
]
size = [
    65,
    131,
]
frame_offset = [
    2,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_150]
pos = [
    127,
    0,
]
size = [
    124,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_151]
pos = [
    0,
    210,
]
size = [
    123,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_152]
pos = [
    272,
    511,
]
size = [
    66,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_153]
pos = [
    574,
    407,
]
size = [
    65,
    131,
]
frame_offset = [
    59,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_154]
pos = [
    203,
    892,
]
size = [
    65,
    121,
]
frame_offset = [
    59,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_155]
pos = [
    708,
    475,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    99,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_156]
pos = [
    641,
    433,
]
size = [
    65,
    121,
]
frame_offset = [
    2,
    106,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_157]
pos = [
    339,
    687,
]
size = [
    65,
    131,
]
frame_offset = [
    2,
    96,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_158]
pos = [
    253,
    0,
]
size = [
    124,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_159]
pos = [
    126,
    198,
]
size = [
    123,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_160]
pos = [
    579,
    117,
]
size = [
    92,
    52,
]
frame_offset = [
    17,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_161]
pos = [
    787,
    57,
]
size = [
    83,
    53,
]
frame_offset = [
    26,
    194,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_162]
pos = [
    670,
    176,
]
size = [
    83,
    53,
]
frame_offset = [
    21,
    194,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_163]
pos = [
    476,
    239,
]
size = [
    92,
    52,
]
frame_offset = [
    21,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_168]
pos = [
    878,
    0,
]
size = [
    82,
    45,
]
frame_offset = [
    16,
    202,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_169]
pos = [
    226,
    412,
]
size = [
    97,
    66,
]
frame_offset = [
    11,
    190,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_170]
pos = [
    537,
    348,
]
size = [
    79,
    57,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_171]
pos = [
    696,
    54,
]
size = [
    89,
    56,
]
frame_offset = [
    30,
    178,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_172]
pos = [
    377,
    132,
]
size = [
    105,
    88,
]
frame_offset = [
    5,
    137,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_01b_53]
pos = [
    136,
    470,
]
size = [
    66,
    190,
]
frame_offset = [
    0,
    36,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_0]
pos = [
    606,
    686,
]
size = [
    63,
    200,
]
frame_offset = [
    59,
    28,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_1]
pos = [
    873,
    639,
]
size = [
    61,
    195,
]
frame_offset = [
    58,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_10]
pos = [
    878,
    47,
]
size = [
    68,
    160,
]
frame_offset = [
    54,
    66,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_11]
pos = [
    671,
    807,
]
size = [
    62,
    157,
]
frame_offset = [
    58,
    71,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_12]
pos = [
    760,
    165,
]
size = [
    68,
    168,
]
frame_offset = [
    56,
    58,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_13]
pos = [
    338,
    820,
]
size = [
    64,
    178,
]
frame_offset = [
    60,
    45,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_16]
pos = [
    936,
    817,
]
size = [
    57,
    195,
]
frame_offset = [
    9,
    26,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_17]
pos = [
    830,
    209,
]
size = [
    67,
    197,
]
frame_offset = [
    6,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_18]
pos = [
    406,
    746,
]
size = [
    64,
    201,
]
frame_offset = [
    6,
    23,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_19]
pos = [
    474,
    663,
]
size = [
    64,
    208,
]
frame_offset = [
    6,
    20,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_2]
pos = [
    948,
    47,
]
size = [
    67,
    202,
]
frame_offset = [
    55,
    26,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_20]
pos = [
    0,
    512,
]
size = [
    66,
    205,
]
frame_offset = [
    4,
    21,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_21]
pos = [
    68,
    512,
]
size = [
    66,
    196,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_24]
pos = [
    809,
    613,
]
size = [
    62,
    196,
]
frame_offset = [
    4,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_25]
pos = [
    540,
    793,
]
size = [
    63,
    178,
]
frame_offset = [
    5,
    45,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_26]
pos = [
    413,
    461,
]
size = [
    65,
    160,
]
frame_offset = [
    4,
    64,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_27]
pos = [
    798,
    815,
]
size = [
    61,
    151,
]
frame_offset = [
    7,
    72,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_28]
pos = [
    204,
    480,
]
size = [
    66,
    163,
]
frame_offset = [
    5,
    60,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_29]
pos = [
    899,
    251,
]
size = [
    67,
    182,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_3]
pos = [
    805,
    408,
]
size = [
    63,
    203,
]
frame_offset = [
    58,
    25,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_4]
pos = [
    935,
    435,
]
size = [
    62,
    202,
]
frame_offset = [
    57,
    23,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_40]
pos = [
    340,
    511,
]
size = [
    65,
    174,
]
frame_offset = [
    4,
    55,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_41]
pos = [
    0,
    719,
]
size = [
    66,
    150,
]
frame_offset = [
    5,
    75,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_42]
pos = [
    472,
    873,
]
size = [
    62,
    127,
]
frame_offset = [
    7,
    97,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_43]
pos = [
    736,
    335,
]
size = [
    67,
    138,
]
frame_offset = [
    5,
    89,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_44]
pos = [
    870,
    435,
]
size = [
    63,
    163,
]
frame_offset = [
    8,
    62,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_45]
pos = [
    735,
    815,
]
size = [
    61,
    198,
]
frame_offset = [
    7,
    29,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_48]
pos = [
    745,
    613,
]
size = [
    62,
    200,
]
frame_offset = [
    59,
    26,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_49]
pos = [
    68,
    843,
]
size = [
    65,
    156,
]
frame_offset = [
    57,
    68,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_5]
pos = [
    665,
    231,
]
size = [
    69,
    200,
]
frame_offset = [
    55,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_50]
pos = [
    204,
    645,
]
size = [
    66,
    112,
]
frame_offset = [
    57,
    112,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_51]
pos = [
    0,
    871,
]
size = [
    65,
    143,
]
frame_offset = [
    59,
    85,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_8]
pos = [
    680,
    605,
]
size = [
    63,
    200,
]
frame_offset = [
    58,
    26,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_02_9]
pos = [
    936,
    639,
]
size = [
    61,
    176,
]
frame_offset = [
    57,
    48,
]
frame_size = [
    128,
    256,
]
