[location_entertainment_gallery_01_100]
pos = [
    812,
    598,
]
size = [
    57,
    131,
]
frame_offset = [
    2,
    11,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_101]
pos = [
    791,
    741,
]
size = [
    53,
    93,
]
frame_offset = [
    6,
    32,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_102]
pos = [
    0,
    947,
]
size = [
    59,
    74,
]
frame_offset = [
    4,
    37,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_103]
pos = [
    198,
    934,
]
size = [
    59,
    76,
]
frame_offset = [
    3,
    37,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_104]
pos = [
    846,
    731,
]
size = [
    51,
    99,
]
frame_offset = [
    15,
    26,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_105]
pos = [
    139,
    825,
]
size = [
    64,
    107,
]
frame_offset = [
    2,
    26,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_106]
pos = [
    774,
    388,
]
size = [
    52,
    98,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_107]
pos = [
    602,
    882,
]
size = [
    55,
    99,
]
frame_offset = [
    6,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_108]
pos = [
    476,
    921,
]
size = [
    56,
    100,
]
frame_offset = [
    6,
    33,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_109]
pos = [
    734,
    741,
]
size = [
    55,
    99,
]
frame_offset = [
    6,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_110]
pos = [
    812,
    494,
]
size = [
    59,
    102,
]
frame_offset = [
    7,
    26,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_111]
pos = [
    542,
    844,
]
size = [
    58,
    101,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_112]
pos = [
    987,
    608,
]
size = [
    27,
    81,
]
frame_offset = [
    39,
    126,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_113]
pos = [
    482,
    600,
]
size = [
    64,
    100,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_114]
pos = [
    350,
    713,
]
size = [
    64,
    101,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_115]
pos = [
    283,
    781,
]
size = [
    64,
    101,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_116]
pos = [
    914,
    817,
]
size = [
    40,
    86,
]
frame_offset = [
    2,
    140,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_117]
pos = [
    632,
    431,
]
size = [
    45,
    96,
]
frame_offset = [
    21,
    33,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_118]
pos = [
    416,
    601,
]
size = [
    64,
    106,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_119]
pos = [
    932,
    497,
]
size = [
    56,
    99,
]
frame_offset = [
    2,
    41,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_120]
pos = [
    996,
    691,
]
size = [
    26,
    134,
]
frame_offset = [
    40,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_121]
pos = [
    73,
    691,
]
size = [
    64,
    155,
]
frame_offset = [
    2,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_122]
pos = [
    284,
    496,
]
size = [
    64,
    155,
]
frame_offset = [
    2,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_123]
pos = [
    0,
    790,
]
size = [
    64,
    155,
]
frame_offset = [
    2,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_124]
pos = [
    830,
    836,
]
size = [
    40,
    143,
]
frame_offset = [
    2,
    15,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_53]
pos = [
    350,
    601,
]
size = [
    64,
    110,
]
frame_offset = [
    60,
    116,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_54]
pos = [
    423,
    486,
]
size = [
    64,
    112,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_55]
pos = [
    949,
    700,
]
size = [
    41,
    99,
]
frame_offset = [
    60,
    115,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_56]
pos = [
    724,
    842,
]
size = [
    52,
    97,
]
frame_offset = [
    72,
    43,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_57]
pos = [
    489,
    486,
]
size = [
    64,
    107,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_58]
pos = [
    679,
    271,
]
size = [
    49,
    97,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_59]
pos = [
    996,
    827,
]
size = [
    26,
    126,
]
frame_offset = [
    98,
    22,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_60]
pos = [
    357,
    454,
]
size = [
    64,
    145,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_61]
pos = [
    150,
    680,
]
size = [
    64,
    143,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_62]
pos = [
    217,
    679,
]
size = [
    64,
    143,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_63]
pos = [
    872,
    832,
]
size = [
    40,
    129,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_64]
pos = [
    667,
    787,
]
size = [
    55,
    100,
]
frame_offset = [
    69,
    35,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_65]
pos = [
    566,
    431,
]
size = [
    64,
    107,
]
frame_offset = [
    60,
    28,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_66]
pos = [
    899,
    718,
]
size = [
    48,
    97,
]
frame_offset = [
    60,
    28,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_67]
pos = [
    686,
    497,
]
size = [
    61,
    139,
]
frame_offset = [
    61,
    21,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_68]
pos = [
    534,
    947,
]
size = [
    30,
    62,
]
frame_offset = [
    94,
    164,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_69]
pos = [
    132,
    934,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_70]
pos = [
    555,
    540,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_71]
pos = [
    566,
    947,
]
size = [
    17,
    59,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_72]
pos = [
    621,
    540,
]
size = [
    63,
    105,
]
frame_offset = [
    61,
    30,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_73]
pos = [
    205,
    825,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    28,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_75]
pos = [
    413,
    826,
]
size = [
    61,
    139,
]
frame_offset = [
    3,
    25,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_76]
pos = [
    990,
    497,
]
size = [
    30,
    109,
]
frame_offset = [
    94,
    20,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_77]
pos = [
    66,
    848,
]
size = [
    64,
    126,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_78]
pos = [
    284,
    653,
]
size = [
    64,
    126,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_79]
pos = [
    999,
    372,
]
size = [
    17,
    101,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_80]
pos = [
    335,
    939,
]
size = [
    35,
    69,
]
frame_offset = [
    31,
    42,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_81]
pos = [
    372,
    939,
]
size = [
    35,
    69,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_82]
pos = [
    871,
    617,
]
size = [
    55,
    99,
]
frame_offset = [
    5,
    38,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_83]
pos = [
    932,
    598,
]
size = [
    53,
    100,
]
frame_offset = [
    13,
    32,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_84]
pos = [
    749,
    497,
]
size = [
    61,
    104,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_85]
pos = [
    873,
    497,
]
size = [
    57,
    118,
]
frame_offset = [
    8,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_86]
pos = [
    659,
    889,
]
size = [
    52,
    120,
]
frame_offset = [
    10,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_87]
pos = [
    674,
    647,
]
size = [
    58,
    138,
]
frame_offset = [
    6,
    25,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_88]
pos = [
    778,
    842,
]
size = [
    50,
    115,
]
frame_offset = [
    16,
    34,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_89]
pos = [
    607,
    761,
]
size = [
    58,
    119,
]
frame_offset = [
    2,
    38,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_90]
pos = [
    612,
    647,
]
size = [
    60,
    112,
]
frame_offset = [
    3,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_91]
pos = [
    546,
    731,
]
size = [
    59,
    111,
]
frame_offset = [
    4,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_92]
pos = [
    481,
    808,
]
size = [
    59,
    111,
]
frame_offset = [
    4,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_93]
pos = [
    349,
    816,
]
size = [
    62,
    121,
]
frame_offset = [
    3,
    30,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_94]
pos = [
    749,
    603,
]
size = [
    58,
    136,
]
frame_offset = [
    6,
    35,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_95]
pos = [
    271,
    884,
]
size = [
    62,
    117,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_96]
pos = [
    416,
    709,
]
size = [
    63,
    115,
]
frame_offset = [
    2,
    29,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_97]
pos = [
    482,
    702,
]
size = [
    62,
    104,
]
frame_offset = [
    3,
    27,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_98]
pos = [
    548,
    624,
]
size = [
    62,
    105,
]
frame_offset = [
    3,
    26,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_01_99]
pos = [
    956,
    801,
]
size = [
    38,
    127,
]
frame_offset = [
    28,
    1,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_0]
pos = [
    735,
    0,
]
size = [
    106,
    192,
]
frame_offset = [
    8,
    62,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_1]
pos = [
    243,
    202,
]
size = [
    117,
    136,
]
frame_offset = [
    5,
    118,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_10]
pos = [
    0,
    280,
]
size = [
    119,
    109,
]
frame_offset = [
    6,
    143,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_11]
pos = [
    468,
    375,
]
size = [
    96,
    109,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_12]
pos = [
    257,
    0,
]
size = [
    124,
    200,
]
frame_offset = [
    1,
    9,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_13]
pos = [
    362,
    246,
]
size = [
    113,
    100,
]
frame_offset = [
    0,
    155,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_16]
pos = [
    508,
    0,
]
size = [
    112,
    184,
]
frame_offset = [
    13,
    70,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_17]
pos = [
    926,
    207,
]
size = [
    90,
    163,
]
frame_offset = [
    38,
    26,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_18]
pos = [
    828,
    365,
]
size = [
    84,
    127,
]
frame_offset = [
    40,
    42,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_19]
pos = [
    122,
    143,
]
size = [
    119,
    126,
]
frame_offset = [
    7,
    124,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_2]
pos = [
    383,
    0,
]
size = [
    123,
    158,
]
frame_offset = [
    5,
    93,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_20]
pos = [
    241,
    340,
]
size = [
    114,
    154,
]
frame_offset = [
    12,
    98,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_21]
pos = [
    843,
    0,
]
size = [
    98,
    205,
]
frame_offset = [
    17,
    48,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_24]
pos = [
    679,
    388,
]
size = [
    93,
    107,
]
frame_offset = [
    27,
    105,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_25]
pos = [
    0,
    120,
]
size = [
    120,
    158,
]
frame_offset = [
    6,
    93,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_26]
pos = [
    730,
    194,
]
size = [
    96,
    192,
]
frame_offset = [
    30,
    62,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_27]
pos = [
    943,
    92,
]
size = [
    76,
    104,
]
frame_offset = [
    40,
    149,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_28]
pos = [
    0,
    512,
]
size = [
    74,
    97,
]
frame_offset = [
    15,
    156,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_29]
pos = [
    622,
    0,
]
size = [
    111,
    137,
]
frame_offset = [
    11,
    65,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_3]
pos = [
    129,
    0,
]
size = [
    126,
    141,
]
frame_offset = [
    0,
    79,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_30]
pos = [
    914,
    372,
]
size = [
    83,
    123,
]
frame_offset = [
    14,
    106,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_32]
pos = [
    580,
    275,
]
size = [
    97,
    154,
]
frame_offset = [
    10,
    100,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_33]
pos = [
    0,
    391,
]
size = [
    117,
    119,
]
frame_offset = [
    7,
    132,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_34]
pos = [
    0,
    0,
]
size = [
    127,
    118,
]
frame_offset = [
    1,
    133,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_35]
pos = [
    828,
    207,
]
size = [
    96,
    156,
]
frame_offset = [
    0,
    50,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_36]
pos = [
    383,
    160,
]
size = [
    116,
    84,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_37]
pos = [
    501,
    186,
]
size = [
    111,
    87,
]
frame_offset = [
    2,
    167,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_4]
pos = [
    477,
    275,
]
size = [
    101,
    98,
]
frame_offset = [
    23,
    120,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_48]
pos = [
    76,
    512,
]
size = [
    72,
    177,
]
frame_offset = [
    33,
    65,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_49]
pos = [
    217,
    498,
]
size = [
    65,
    179,
]
frame_offset = [
    30,
    63,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_5]
pos = [
    943,
    0,
]
size = [
    79,
    90,
]
frame_offset = [
    34,
    164,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_50]
pos = [
    150,
    498,
]
size = [
    65,
    180,
]
frame_offset = [
    33,
    62,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_51]
pos = [
    0,
    611,
]
size = [
    71,
    177,
]
frame_offset = [
    26,
    65,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_52]
pos = [
    122,
    271,
]
size = [
    117,
    225,
]
frame_offset = [
    6,
    28,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_8]
pos = [
    357,
    348,
]
size = [
    109,
    104,
]
frame_offset = [
    9,
    148,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_9]
pos = [
    622,
    139,
]
size = [
    106,
    130,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]
