[location_community_medical_01_129]
pos = [
    356,
    239,
]
size = [
    115,
    117,
]
frame_offset = [
    6,
    137,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_130]
pos = [
    305,
    792,
]
size = [
    90,
    207,
]
frame_offset = [
    38,
    44,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_131]
pos = [
    729,
    0,
]
size = [
    110,
    238,
]
frame_offset = [
    9,
    13,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_132]
pos = [
    615,
    244,
]
size = [
    109,
    245,
]
frame_offset = [
    9,
    1,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_133]
pos = [
    841,
    0,
]
size = [
    109,
    247,
]
frame_offset = [
    9,
    5,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_134]
pos = [
    0,
    712,
]
size = [
    105,
    236,
]
frame_offset = [
    3,
    16,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_136]
pos = [
    952,
    178,
]
size = [
    56,
    68,
]
frame_offset = [
    36,
    106,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_137]
pos = [
    397,
    901,
]
size = [
    70,
    68,
]
frame_offset = [
    23,
    106,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_138]
pos = [
    469,
    924,
]
size = [
    56,
    66,
]
frame_offset = [
    38,
    112,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_139]
pos = [
    812,
    494,
]
size = [
    69,
    66,
]
frame_offset = [
    20,
    114,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_141]
pos = [
    807,
    790,
]
size = [
    61,
    172,
]
frame_offset = [
    3,
    65,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_142]
pos = [
    729,
    240,
]
size = [
    108,
    183,
]
frame_offset = [
    11,
    49,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_143]
pos = [
    502,
    0,
]
size = [
    112,
    170,
]
frame_offset = [
    0,
    79,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_144]
pos = [
    739,
    460,
]
size = [
    71,
    215,
]
frame_offset = [
    31,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_145]
pos = [
    319,
    556,
]
size = [
    95,
    234,
]
frame_offset = [
    31,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_146]
pos = [
    947,
    249,
]
size = [
    70,
    215,
]
frame_offset = [
    32,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_147]
pos = [
    502,
    707,
]
size = [
    71,
    215,
]
frame_offset = [
    24,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_148]
pos = [
    356,
    358,
]
size = [
    104,
    196,
]
frame_offset = [
    24,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_149]
pos = [
    575,
    707,
]
size = [
    70,
    215,
]
frame_offset = [
    24,
    22,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_152]
pos = [
    839,
    249,
]
size = [
    106,
    243,
]
frame_offset = [
    0,
    1,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_153]
pos = [
    214,
    510,
]
size = [
    103,
    243,
]
frame_offset = [
    2,
    1,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_154]
pos = [
    0,
    464,
]
size = [
    105,
    246,
]
frame_offset = [
    19,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_155]
pos = [
    107,
    473,
]
size = [
    105,
    246,
]
frame_offset = [
    20,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_156]
pos = [
    527,
    924,
]
size = [
    41,
    61,
]
frame_offset = [
    62,
    61,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_157]
pos = [
    562,
    391,
]
size = [
    47,
    54,
]
frame_offset = [
    63,
    71,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_158]
pos = [
    767,
    905,
]
size = [
    33,
    58,
]
frame_offset = [
    63,
    60,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_159]
pos = [
    948,
    892,
]
size = [
    32,
    56,
]
frame_offset = [
    60,
    60,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_160]
pos = [
    693,
    935,
]
size = [
    35,
    51,
]
frame_offset = [
    26,
    68,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_161]
pos = [
    613,
    935,
]
size = [
    38,
    60,
]
frame_offset = [
    14,
    66,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_162]
pos = [
    982,
    892,
]
size = [
    32,
    56,
]
frame_offset = [
    32,
    60,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_163]
pos = [
    951,
    694,
]
size = [
    38,
    196,
]
frame_offset = [
    28,
    60,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_164]
pos = [
    510,
    599,
]
size = [
    47,
    54,
]
frame_offset = [
    14,
    71,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_165]
pos = [
    570,
    924,
]
size = [
    41,
    61,
]
frame_offset = [
    21,
    61,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_166]
pos = [
    653,
    935,
]
size = [
    38,
    60,
]
frame_offset = [
    72,
    66,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_167]
pos = [
    730,
    905,
]
size = [
    35,
    51,
]
frame_offset = [
    63,
    68,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_168]
pos = [
    647,
    707,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_169]
pos = [
    812,
    562,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_170]
pos = [
    0,
    0,
]
size = [
    126,
    226,
]

[location_community_medical_01_171]
pos = [
    715,
    704,
]
size = [
    7,
    196,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_172]
pos = [
    239,
    239,
]
size = [
    115,
    207,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_173]
pos = [
    397,
    808,
]
size = [
    81,
    91,
]
frame_offset = [
    9,
    158,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_174]
pos = [
    416,
    599,
]
size = [
    92,
    96,
]
frame_offset = [
    31,
    159,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_175]
pos = [
    416,
    697,
]
size = [
    84,
    109,
]
frame_offset = [
    15,
    133,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_176]
pos = [
    883,
    494,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_177]
pos = [
    739,
    677,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_178]
pos = [
    951,
    466,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_179]
pos = [
    880,
    722,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_180]
pos = [
    253,
    71,
]
size = [
    1,
    2,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_182]
pos = [
    952,
    0,
]
size = [
    63,
    87,
]
frame_offset = [
    62,
    81,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_183]
pos = [
    952,
    89,
]
size = [
    63,
    87,
]
frame_offset = [
    0,
    81,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_184]
pos = [
    128,
    71,
]
size = [
    123,
    77,
]
frame_offset = [
    1,
    20,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_185]
pos = [
    0,
    950,
]
size = [
    88,
    34,
]
frame_offset = [
    1,
    51,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_186]
pos = [
    128,
    150,
]
size = [
    123,
    77,
]
frame_offset = [
    2,
    20,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_187]
pos = [
    90,
    958,
]
size = [
    81,
    31,
]
frame_offset = [
    4,
    50,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_188]
pos = [
    380,
    121,
]
size = [
    120,
    116,
]
frame_offset = [
    2,
    139,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_189]
pos = [
    0,
    228,
]
size = [
    119,
    114,
]
frame_offset = [
    0,
    133,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_190]
pos = [
    380,
    0,
]
size = [
    120,
    119,
]
frame_offset = [
    6,
    130,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_191]
pos = [
    121,
    229,
]
size = [
    116,
    120,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_192]
pos = [
    562,
    491,
]
size = [
    90,
    214,
]
frame_offset = [
    33,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_193]
pos = [
    209,
    755,
]
size = [
    94,
    215,
]
frame_offset = [
    20,
    30,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_194]
pos = [
    502,
    172,
]
size = [
    111,
    217,
]
frame_offset = [
    14,
    26,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_195]
pos = [
    256,
    0,
]
size = [
    122,
    237,
]
frame_offset = [
    2,
    17,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_196]
pos = [
    462,
    391,
]
size = [
    98,
    206,
]
frame_offset = [
    2,
    48,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_197]
pos = [
    0,
    344,
]
size = [
    117,
    118,
]
frame_offset = [
    7,
    134,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_198]
pos = [
    119,
    351,
]
size = [
    115,
    120,
]
frame_offset = [
    6,
    132,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_200]
pos = [
    173,
    972,
]
size = [
    66,
    29,
]
frame_offset = [
    58,
    42,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_201]
pos = [
    236,
    448,
]
size = [
    111,
    60,
]
frame_offset = [
    8,
    12,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_202]
pos = [
    726,
    425,
]
size = [
    75,
    33,
]
frame_offset = [
    48,
    44,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_203]
pos = [
    128,
    0,
]
size = [
    126,
    69,
]
frame_offset = [
    1,
    12,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_208]
pos = [
    654,
    491,
]
size = [
    83,
    211,
]
frame_offset = [
    45,
    37,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_209]
pos = [
    616,
    0,
]
size = [
    111,
    242,
]
frame_offset = [
    14,
    6,
]
frame_size = [
    128,
    256,
]

[location_community_medical_01_210]
pos = [
    107,
    721,
]
size = [
    100,
    235,
]
frame_offset = [
    14,
    6,
]
frame_size = [
    128,
    256,
]
