[walls_interior_detailing_bathroom_03_164]
pos = [
    948,
    638,
]
size = [
    65,
    160,
]
frame_offset = [
    1,
    66,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_165]
pos = [
    408,
    684,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_166]
pos = [
    408,
    866,
]
size = [
    65,
    156,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_167]
pos = [
    743,
    820,
]
size = [
    65,
    161,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_168]
pos = [
    0,
    912,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_169]
pos = [
    67,
    912,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_170]
pos = [
    475,
    866,
]
size = [
    65,
    155,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_171]
pos = [
    680,
    456,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_172]
pos = [
    877,
    820,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_173]
pos = [
    810,
    820,
]
size = [
    65,
    157,
]
frame_offset = [
    60,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_174]
pos = [
    0,
    1012,
]
size = [
    1,
    1,
]
frame_offset = [
    1,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_175]
pos = [
    3,
    1012,
]
size = [
    1,
    1,
]
frame_offset = [
    124,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_176]
pos = [
    475,
    684,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_177]
pos = [
    747,
    456,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_178]
pos = [
    542,
    684,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_179]
pos = [
    814,
    456,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_180]
pos = [
    542,
    866,
]
size = [
    19,
    156,
]
frame_offset = [
    1,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_181]
pos = [
    1009,
    0,
]
size = [
    13,
    155,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_182]
pos = [
    1009,
    157,
]
size = [
    12,
    154,
]
frame_offset = [
    54,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_183]
pos = [
    988,
    0,
]
size = [
    19,
    157,
]
frame_offset = [
    106,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_184]
pos = [
    609,
    684,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_185]
pos = [
    680,
    638,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_186]
pos = [
    881,
    456,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_187]
pos = [
    747,
    638,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_188]
pos = [
    948,
    456,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_189]
pos = [
    814,
    638,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_190]
pos = [
    676,
    820,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_191]
pos = [
    881,
    638,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_0]
pos = [
    256,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_1]
pos = [
    784,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_10]
pos = [
    324,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_11]
pos = [
    392,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_12]
pos = [
    512,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_13]
pos = [
    580,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_14]
pos = [
    648,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_15]
pos = [
    460,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_16]
pos = [
    716,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_17]
pos = [
    528,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_18]
pos = [
    0,
    0,
]
size = [
    126,
    226,
]

[walls_interior_house_01_19]
pos = [
    1015,
    313,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_2]
pos = [
    256,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_20]
pos = [
    596,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_21]
pos = [
    852,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_22]
pos = [
    128,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_23]
pos = [
    1015,
    511,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_24]
pos = [
    664,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_25]
pos = [
    920,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_26]
pos = [
    732,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_27]
pos = [
    800,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_28]
pos = [
    868,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_29]
pos = [
    936,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_3]
pos = [
    956,
    800,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_30]
pos = [
    0,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_31]
pos = [
    68,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_32]
pos = [
    136,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_33]
pos = [
    204,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_34]
pos = [
    384,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_35]
pos = [
    1015,
    709,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_36]
pos = [
    0,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_37]
pos = [
    272,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_38]
pos = [
    0,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_39]
pos = [
    948,
    800,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_4]
pos = [
    272,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_40]
pos = [
    68,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_41]
pos = [
    340,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_42]
pos = [
    136,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_43]
pos = [
    408,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_44]
pos = [
    204,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_45]
pos = [
    476,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_5]
pos = [
    544,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_6]
pos = [
    128,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_7]
pos = [
    964,
    800,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_8]
pos = [
    340,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_01_9]
pos = [
    612,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
