[fencing_damaged_04_170]
pos = [
    955,
    0,
]
size = [
    67,
    191,
]
frame_offset = [
    1,
    14,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_171]
pos = [
    220,
    617,
]
size = [
    67,
    207,
]
frame_offset = [
    4,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_172]
pos = [
    0,
    0,
]
size = [
    128,
    228,
]

[fencing_damaged_04_173]
pos = [
    656,
    0,
]
size = [
    73,
    212,
]
frame_offset = [
    0,
    8,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_174]
pos = [
    909,
    687,
]
size = [
    60,
    192,
]
frame_offset = [
    9,
    25,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_175]
pos = [
    145,
    804,
]
size = [
    66,
    207,
]
frame_offset = [
    5,
    19,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_176]
pos = [
    130,
    118,
]
size = [
    106,
    52,
]
frame_offset = [
    20,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_177]
pos = [
    332,
    162,
]
size = [
    82,
    51,
]
frame_offset = [
    22,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_178]
pos = [
    335,
    111,
]
size = [
    83,
    49,
]
frame_offset = [
    43,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_179]
pos = [
    81,
    230,
]
size = [
    76,
    42,
]
frame_offset = [
    0,
    206,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_180]
pos = [
    249,
    0,
]
size = [
    100,
    53,
]
frame_offset = [
    0,
    203,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_181]
pos = [
    0,
    230,
]
size = [
    79,
    50,
]
frame_offset = [
    27,
    206,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_184]
pos = [
    881,
    0,
]
size = [
    72,
    209,
]
frame_offset = [
    53,
    17,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_185]
pos = [
    289,
    790,
]
size = [
    65,
    207,
]
frame_offset = [
    61,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_186]
pos = [
    376,
    642,
]
size = [
    66,
    220,
]
frame_offset = [
    62,
    7,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_187]
pos = [
    584,
    607,
]
size = [
    64,
    203,
]
frame_offset = [
    64,
    22,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_188]
pos = [
    504,
    186,
]
size = [
    73,
    206,
]
frame_offset = [
    53,
    17,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_189]
pos = [
    650,
    807,
]
size = [
    62,
    189,
]
frame_offset = [
    62,
    14,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_191]
pos = [
    81,
    274,
]
size = [
    75,
    219,
]
frame_offset = [
    53,
    6,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_192]
pos = [
    235,
    409,
]
size = [
    70,
    206,
]
frame_offset = [
    53,
    17,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_193]
pos = [
    715,
    387,
]
size = [
    65,
    199,
]
frame_offset = [
    59,
    21,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_194]
pos = [
    648,
    387,
]
size = [
    65,
    218,
]
frame_offset = [
    60,
    6,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_195]
pos = [
    151,
    587,
]
size = [
    67,
    215,
]
frame_offset = [
    61,
    10,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_200]
pos = [
    159,
    226,
]
size = [
    65,
    40,
]
frame_offset = [
    58,
    205,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_201]
pos = [
    240,
    58,
]
size = [
    98,
    51,
]
frame_offset = [
    20,
    194,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_202]
pos = [
    351,
    0,
]
size = [
    94,
    49,
]
frame_offset = [
    24,
    205,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_203]
pos = [
    340,
    55,
]
size = [
    90,
    49,
]
frame_offset = [
    2,
    199,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_204]
pos = [
    0,
    282,
]
size = [
    78,
    44,
]
frame_offset = [
    26,
    207,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_205]
pos = [
    130,
    58,
]
size = [
    108,
    58,
]
frame_offset = [
    4,
    193,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_208]
pos = [
    504,
    0,
]
size = [
    74,
    184,
]
frame_offset = [
    0,
    42,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_209]
pos = [
    954,
    341,
]
size = [
    64,
    162,
]
frame_offset = [
    10,
    59,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_210]
pos = [
    937,
    505,
]
size = [
    62,
    180,
]
frame_offset = [
    10,
    44,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_211]
pos = [
    805,
    358,
]
size = [
    64,
    207,
]
frame_offset = [
    8,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_212]
pos = [
    580,
    0,
]
size = [
    74,
    175,
]
frame_offset = [
    0,
    51,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_213]
pos = [
    955,
    193,
]
size = [
    65,
    146,
]
frame_offset = [
    10,
    83,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_214]
pos = [
    0,
    879,
]
size = [
    63,
    127,
]
frame_offset = [
    11,
    101,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_215]
pos = [
    581,
    812,
]
size = [
    62,
    208,
]
frame_offset = [
    10,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_220]
pos = [
    444,
    846,
]
size = [
    64,
    167,
]
frame_offset = [
    0,
    59,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_221]
pos = [
    420,
    106,
]
size = [
    82,
    138,
]
frame_offset = [
    0,
    91,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_222]
pos = [
    447,
    0,
]
size = [
    27,
    63,
]
frame_offset = [
    41,
    145,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_223]
pos = [
    379,
    432,
]
size = [
    67,
    208,
]
frame_offset = [
    4,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_224]
pos = [
    240,
    111,
]
size = [
    93,
    44,
]
frame_offset = [
    33,
    203,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_225]
pos = [
    130,
    172,
]
size = [
    102,
    52,
]
frame_offset = [
    18,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_226]
pos = [
    238,
    157,
]
size = [
    92,
    44,
]
frame_offset = [
    22,
    212,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_227]
pos = [
    130,
    0,
]
size = [
    117,
    56,
]
frame_offset = [
    0,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_228]
pos = [
    584,
    551,
]
size = [
    61,
    50,
]
frame_offset = [
    4,
    196,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_04_229]
pos = [
    234,
    203,
]
size = [
    86,
    35,
]
frame_offset = [
    22,
    195,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_0]
pos = [
    398,
    246,
]
size = [
    74,
    184,
]
frame_offset = [
    48,
    29,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_1]
pos = [
    716,
    769,
]
size = [
    61,
    197,
]
frame_offset = [
    58,
    34,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_10]
pos = [
    806,
    0,
]
size = [
    73,
    171,
]
frame_offset = [
    49,
    43,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_11]
pos = [
    716,
    588,
]
size = [
    63,
    179,
]
frame_offset = [
    58,
    52,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_12]
pos = [
    0,
    328,
]
size = [
    75,
    173,
]
frame_offset = [
    49,
    41,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_13]
pos = [
    213,
    826,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    36,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_16]
pos = [
    806,
    173,
]
size = [
    72,
    183,
]
frame_offset = [
    6,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_17]
pos = [
    517,
    551,
]
size = [
    65,
    198,
]
frame_offset = [
    5,
    34,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_18]
pos = [
    731,
    193,
]
size = [
    72,
    189,
]
frame_offset = [
    6,
    23,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_19]
pos = [
    448,
    630,
]
size = [
    65,
    214,
]
frame_offset = [
    5,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_2]
pos = [
    322,
    215,
]
size = [
    74,
    190,
]
frame_offset = [
    49,
    22,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_20]
pos = [
    731,
    0,
]
size = [
    73,
    191,
]
frame_offset = [
    5,
    22,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_21]
pos = [
    448,
    432,
]
size = [
    67,
    196,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_24]
pos = [
    158,
    274,
]
size = [
    75,
    184,
]
frame_offset = [
    3,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_25]
pos = [
    871,
    395,
]
size = [
    64,
    195,
]
frame_offset = [
    3,
    36,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_26]
pos = [
    235,
    240,
]
size = [
    75,
    167,
]
frame_offset = [
    3,
    48,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_27]
pos = [
    845,
    755,
]
size = [
    61,
    178,
]
frame_offset = [
    6,
    53,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_28]
pos = [
    655,
    214,
]
size = [
    73,
    171,
]
frame_offset = [
    5,
    42,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_29]
pos = [
    307,
    593,
]
size = [
    67,
    195,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_3]
pos = [
    781,
    588,
]
size = [
    62,
    212,
]
frame_offset = [
    59,
    19,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_4]
pos = [
    0,
    687,
]
size = [
    70,
    190,
]
frame_offset = [
    49,
    21,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_40]
pos = [
    579,
    354,
]
size = [
    67,
    195,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_41]
pos = [
    77,
    495,
]
size = [
    72,
    165,
]
frame_offset = [
    5,
    47,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_42]
pos = [
    845,
    592,
]
size = [
    62,
    161,
]
frame_offset = [
    7,
    70,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_43]
pos = [
    158,
    460,
]
size = [
    72,
    125,
]
frame_offset = [
    5,
    89,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_44]
pos = [
    650,
    607,
]
size = [
    64,
    198,
]
frame_offset = [
    8,
    33,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_45]
pos = [
    307,
    409,
]
size = [
    70,
    182,
]
frame_offset = [
    8,
    29,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_48]
pos = [
    880,
    211,
]
size = [
    72,
    182,
]
frame_offset = [
    49,
    29,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_49]
pos = [
    515,
    751,
]
size = [
    64,
    198,
]
frame_offset = [
    57,
    33,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_5]
pos = [
    74,
    662,
]
size = [
    69,
    197,
]
frame_offset = [
    55,
    33,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_50]
pos = [
    580,
    177,
]
size = [
    73,
    175,
]
frame_offset = [
    50,
    81,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_51]
pos = [
    72,
    861,
]
size = [
    65,
    161,
]
frame_offset = [
    59,
    70,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_8]
pos = [
    0,
    503,
]
size = [
    72,
    182,
]
frame_offset = [
    49,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_9]
pos = [
    779,
    802,
]
size = [
    61,
    197,
]
frame_offset = [
    57,
    34,
]
frame_size = [
    128,
    256,
]
