[fixtures_windows_metal_100]
pos = [
    876,
    798,
]
size = [
    51,
    153,
]
frame_offset = [
    2,
    9,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_101]
pos = [
    894,
    155,
]
size = [
    55,
    152,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_102]
pos = [
    72,
    0,
]
size = [
    67,
    225,
]
frame_offset = [
    1,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_103]
pos = [
    0,
    0,
]
size = [
    70,
    254,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_104]
pos = [
    951,
    219,
]
size = [
    55,
    151,
]
frame_offset = [
    7,
    6,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_105]
pos = [
    476,
    493,
]
size = [
    54,
    150,
]
frame_offset = [
    64,
    6,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_106]
pos = [
    466,
    375,
]
size = [
    55,
    116,
]
frame_offset = [
    7,
    40,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_107]
pos = [
    224,
    809,
]
size = [
    54,
    117,
]
frame_offset = [
    65,
    40,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_108]
pos = [
    643,
    713,
]
size = [
    52,
    219,
]
frame_offset = [
    16,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_109]
pos = [
    953,
    0,
]
size = [
    55,
    217,
]
frame_offset = [
    70,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_110]
pos = [
    252,
    433,
]
size = [
    54,
    218,
]
frame_offset = [
    1,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_111]
pos = [
    588,
    527,
]
size = [
    53,
    216,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_112]
pos = [
    885,
    598,
]
size = [
    52,
    98,
]
frame_offset = [
    15,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_113]
pos = [
    697,
    881,
]
size = [
    52,
    97,
]
frame_offset = [
    71,
    59,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_114]
pos = [
    414,
    227,
]
size = [
    64,
    105,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_115]
pos = [
    208,
    324,
]
size = [
    65,
    107,
]
frame_offset = [
    59,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_116]
pos = [
    446,
    918,
]
size = [
    52,
    99,
]
frame_offset = [
    2,
    58,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_117]
pos = [
    929,
    894,
]
size = [
    51,
    97,
]
frame_offset = [
    59,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_118]
pos = [
    805,
    943,
]
size = [
    50,
    66,
]
frame_offset = [
    8,
    18,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_119]
pos = [
    277,
    928,
]
size = [
    51,
    65,
]
frame_offset = [
    68,
    18,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_76]
pos = [
    712,
    660,
]
size = [
    52,
    219,
]
frame_offset = [
    16,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_77]
pos = [
    837,
    155,
]
size = [
    55,
    217,
]
frame_offset = [
    70,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_78]
pos = [
    0,
    703,
]
size = [
    54,
    218,
]
frame_offset = [
    1,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_79]
pos = [
    657,
    495,
]
size = [
    53,
    216,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_80]
pos = [
    556,
    879,
]
size = [
    52,
    99,
]
frame_offset = [
    15,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_81]
pos = [
    751,
    908,
]
size = [
    52,
    97,
]
frame_offset = [
    71,
    59,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_82]
pos = [
    342,
    336,
]
size = [
    64,
    105,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_83]
pos = [
    347,
    227,
]
size = [
    65,
    107,
]
frame_offset = [
    59,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_84]
pos = [
    766,
    707,
]
size = [
    52,
    99,
]
frame_offset = [
    2,
    58,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_85]
pos = [
    876,
    698,
]
size = [
    52,
    98,
]
frame_offset = [
    59,
    51,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_86]
pos = [
    857,
    953,
]
size = [
    50,
    66,
]
frame_offset = [
    8,
    18,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_87]
pos = [
    610,
    934,
]
size = [
    51,
    65,
]
frame_offset = [
    68,
    18,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_88]
pos = [
    718,
    155,
]
size = [
    56,
    153,
]
frame_offset = [
    16,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_89]
pos = [
    56,
    874,
]
size = [
    54,
    133,
]
frame_offset = [
    71,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_90]
pos = [
    532,
    439,
]
size = [
    54,
    133,
]
frame_offset = [
    1,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_91]
pos = [
    895,
    0,
]
size = [
    56,
    153,
]
frame_offset = [
    54,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_92]
pos = [
    602,
    155,
]
size = [
    56,
    218,
]
frame_offset = [
    15,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_93]
pos = [
    112,
    674,
]
size = [
    54,
    197,
]
frame_offset = [
    70,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_94]
pos = [
    391,
    767,
]
size = [
    53,
    198,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_95]
pos = [
    660,
    155,
]
size = [
    56,
    217,
]
frame_offset = [
    55,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_96]
pos = [
    279,
    0,
]
size = [
    67,
    159,
]
frame_offset = [
    0,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_97]
pos = [
    279,
    161,
]
size = [
    66,
    158,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_98]
pos = [
    420,
    493,
]
size = [
    54,
    153,
]
frame_offset = [
    15,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_metal_99]
pos = [
    930,
    741,
]
size = [
    51,
    151,
]
frame_offset = [
    73,
    11,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_0]
pos = [
    602,
    0,
]
size = [
    57,
    153,
]
frame_offset = [
    15,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_1]
pos = [
    767,
    574,
]
size = [
    53,
    131,
]
frame_offset = [
    71,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_10]
pos = [
    661,
    0,
]
size = [
    57,
    153,
]
frame_offset = [
    14,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_11]
pos = [
    168,
    654,
]
size = [
    54,
    153,
]
frame_offset = [
    72,
    9,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_12]
pos = [
    224,
    654,
]
size = [
    54,
    153,
]
frame_offset = [
    1,
    9,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_13]
pos = [
    775,
    418,
]
size = [
    53,
    154,
]
frame_offset = [
    57,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_14]
pos = [
    0,
    256,
]
size = [
    66,
    224,
]
frame_offset = [
    2,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_15]
pos = [
    348,
    0,
]
size = [
    66,
    225,
]
frame_offset = [
    58,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_16]
pos = [
    446,
    767,
]
size = [
    53,
    149,
]
frame_offset = [
    7,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_17]
pos = [
    601,
    375,
]
size = [
    54,
    150,
]
frame_offset = [
    65,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_18]
pos = [
    112,
    873,
]
size = [
    54,
    118,
]
frame_offset = [
    8,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_19]
pos = [
    392,
    648,
]
size = [
    54,
    117,
]
frame_offset = [
    64,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_2]
pos = [
    501,
    794,
]
size = [
    53,
    132,
]
frame_offset = [
    1,
    30,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_20]
pos = [
    822,
    626,
]
size = [
    52,
    216,
]
frame_offset = [
    16,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_21]
pos = [
    0,
    482,
]
size = [
    54,
    219,
]
frame_offset = [
    71,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_22]
pos = [
    336,
    766,
]
size = [
    53,
    218,
]
frame_offset = [
    2,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_23]
pos = [
    68,
    453,
]
size = [
    54,
    219,
]
frame_offset = [
    57,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_24]
pos = [
    830,
    526,
]
size = [
    53,
    98,
]
frame_offset = [
    13,
    53,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_25]
pos = [
    820,
    844,
]
size = [
    52,
    97,
]
frame_offset = [
    73,
    60,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_26]
pos = [
    275,
    324,
]
size = [
    65,
    105,
]
frame_offset = [
    1,
    53,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_27]
pos = [
    140,
    324,
]
size = [
    66,
    105,
]
frame_offset = [
    60,
    52,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_28]
pos = [
    766,
    808,
]
size = [
    52,
    98,
]
frame_offset = [
    1,
    60,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_29]
pos = [
    0,
    923,
]
size = [
    53,
    99,
]
frame_offset = [
    60,
    52,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_3]
pos = [
    408,
    336,
]
size = [
    56,
    153,
]
frame_offset = [
    54,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_30]
pos = [
    224,
    928,
]
size = [
    51,
    66,
]
frame_offset = [
    8,
    18,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_31]
pos = [
    500,
    928,
]
size = [
    51,
    65,
]
frame_offset = [
    68,
    19,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_4]
pos = [
    484,
    0,
]
size = [
    57,
    218,
]
frame_offset = [
    15,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_47]
pos = [
    68,
    256,
]
size = [
    2,
    13,
]
frame_offset = [
    126,
    243,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_48]
pos = [
    712,
    509,
]
size = [
    53,
    149,
]
frame_offset = [
    7,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_49]
pos = [
    833,
    374,
]
size = [
    53,
    150,
]
frame_offset = [
    65,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_5]
pos = [
    776,
    219,
]
size = [
    55,
    197,
]
frame_offset = [
    71,
    30,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_50]
pos = [
    336,
    646,
]
size = [
    54,
    118,
]
frame_offset = [
    8,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_51]
pos = [
    280,
    808,
]
size = [
    54,
    117,
]
frame_offset = [
    64,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_56]
pos = [
    484,
    220,
]
size = [
    57,
    153,
]
frame_offset = [
    15,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_57]
pos = [
    888,
    465,
]
size = [
    53,
    131,
]
frame_offset = [
    71,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_58]
pos = [
    587,
    745,
]
size = [
    53,
    132,
]
frame_offset = [
    1,
    30,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_59]
pos = [
    837,
    0,
]
size = [
    56,
    153,
]
frame_offset = [
    54,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_6]
pos = [
    308,
    443,
]
size = [
    54,
    198,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_60]
pos = [
    543,
    0,
]
size = [
    57,
    218,
]
frame_offset = [
    15,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_61]
pos = [
    718,
    310,
]
size = [
    55,
    197,
]
frame_offset = [
    71,
    30,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_62]
pos = [
    56,
    674,
]
size = [
    54,
    198,
]
frame_offset = [
    0,
    29,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_63]
pos = [
    543,
    220,
]
size = [
    56,
    217,
]
frame_offset = [
    56,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_64]
pos = [
    141,
    0,
]
size = [
    67,
    161,
]
frame_offset = [
    0,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_65]
pos = [
    141,
    163,
]
size = [
    66,
    159,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_66]
pos = [
    720,
    0,
]
size = [
    57,
    153,
]
frame_offset = [
    14,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_67]
pos = [
    364,
    491,
]
size = [
    54,
    153,
]
frame_offset = [
    72,
    9,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_68]
pos = [
    280,
    653,
]
size = [
    54,
    153,
]
frame_offset = [
    1,
    9,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_69]
pos = [
    894,
    309,
]
size = [
    53,
    154,
]
frame_offset = [
    57,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_7]
pos = [
    779,
    0,
]
size = [
    56,
    217,
]
frame_offset = [
    56,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_70]
pos = [
    72,
    227,
]
size = [
    66,
    224,
]
frame_offset = [
    2,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_71]
pos = [
    416,
    0,
]
size = [
    66,
    225,
]
frame_offset = [
    58,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_72]
pos = [
    949,
    372,
]
size = [
    53,
    149,
]
frame_offset = [
    7,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_73]
pos = [
    168,
    809,
]
size = [
    54,
    150,
]
frame_offset = [
    65,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_74]
pos = [
    657,
    375,
]
size = [
    54,
    118,
]
frame_offset = [
    8,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_75]
pos = [
    448,
    648,
]
size = [
    54,
    117,
]
frame_offset = [
    64,
    39,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_76]
pos = [
    943,
    523,
]
size = [
    52,
    216,
]
frame_offset = [
    16,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_77]
pos = [
    140,
    431,
]
size = [
    54,
    219,
]
frame_offset = [
    71,
    7,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_78]
pos = [
    532,
    574,
]
size = [
    53,
    218,
]
frame_offset = [
    2,
    8,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_79]
pos = [
    196,
    433,
]
size = [
    54,
    219,
]
frame_offset = [
    57,
    0,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_8]
pos = [
    210,
    0,
]
size = [
    67,
    161,
]
frame_offset = [
    0,
    1,
]
frame_size = [
    128,
    256,
]

[fixtures_windows_white_9]
pos = [
    209,
    163,
]
size = [
    66,
    159,
]
frame_offset = [
    58,
    2,
]
frame_size = [
    128,
    256,
]
