[location_entertainment_theatre_01_100]
pos = [
    452,
    480,
]
size = [
    74,
    234,
]
frame_offset = [
    24,
    22,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_101]
pos = [
    426,
    716,
]
size = [
    70,
    237,
]
frame_offset = [
    25,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_102]
pos = [
    602,
    375,
]
size = [
    70,
    256,
]
frame_offset = [
    25,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_103]
pos = [
    353,
    639,
]
size = [
    71,
    215,
]
frame_offset = [
    24,
    22,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_104]
pos = [
    0,
    800,
]
size = [
    86,
    134,
]
frame_offset = [
    33,
    18,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_105]
pos = [
    0,
    394,
]
size = [
    89,
    222,
]
frame_offset = [
    29,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_106]
pos = [
    509,
    283,
]
size = [
    91,
    195,
]
frame_offset = [
    27,
    8,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_107]
pos = [
    91,
    394,
]
size = [
    89,
    214,
]
frame_offset = [
    29,
    8,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_108]
pos = [
    273,
    569,
]
size = [
    78,
    256,
]
frame_offset = [
    30,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_109]
pos = [
    171,
    818,
]
size = [
    68,
    191,
]
frame_offset = [
    20,
    3,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_110]
pos = [
    953,
    241,
]
size = [
    64,
    210,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_111]
pos = [
    307,
    856,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    83,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_112]
pos = [
    0,
    222,
]
size = [
    108,
    170,
]
frame_offset = [
    2,
    9,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_113]
pos = [
    767,
    0,
]
size = [
    92,
    214,
]
frame_offset = [
    16,
    8,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_114]
pos = [
    671,
    178,
]
size = [
    90,
    195,
]
frame_offset = [
    18,
    9,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_115]
pos = [
    182,
    600,
]
size = [
    86,
    216,
]
frame_offset = [
    16,
    6,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_116]
pos = [
    364,
    431,
]
size = [
    86,
    206,
]
frame_offset = [
    10,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_117]
pos = [
    624,
    886,
]
size = [
    54,
    110,
]
frame_offset = [
    12,
    108,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_118]
pos = [
    498,
    844,
]
size = [
    64,
    106,
]
frame_offset = [
    2,
    115,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_119]
pos = [
    315,
    250,
]
size = [
    8,
    35,
]
frame_offset = [
    2,
    151,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_120]
pos = [
    480,
    0,
]
size = [
    94,
    177,
]
frame_offset = [
    33,
    54,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_121]
pos = [
    763,
    216,
]
size = [
    90,
    173,
]
frame_offset = [
    34,
    65,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_122]
pos = [
    182,
    425,
]
size = [
    89,
    173,
]
frame_offset = [
    2,
    65,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_123]
pos = [
    672,
    0,
]
size = [
    93,
    176,
]
frame_offset = [
    0,
    54,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_124]
pos = [
    861,
    0,
]
size = [
    90,
    180,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_125]
pos = [
    362,
    118,
]
size = [
    95,
    173,
]
frame_offset = [
    0,
    81,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_126]
pos = [
    218,
    250,
]
size = [
    95,
    173,
]
frame_offset = [
    31,
    81,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_127]
pos = [
    0,
    618,
]
size = [
    89,
    180,
]
frame_offset = [
    36,
    71,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_128]
pos = [
    576,
    0,
]
size = [
    94,
    140,
]
frame_offset = [
    33,
    91,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_129]
pos = [
    855,
    327,
]
size = [
    90,
    136,
]
frame_offset = [
    34,
    102,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_130]
pos = [
    273,
    431,
]
size = [
    89,
    136,
]
frame_offset = [
    2,
    102,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_131]
pos = [
    576,
    142,
]
size = [
    93,
    139,
]
frame_offset = [
    0,
    91,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_132]
pos = [
    861,
    182,
]
size = [
    90,
    143,
]
frame_offset = [
    1,
    108,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_133]
pos = [
    412,
    293,
]
size = [
    95,
    135,
]
frame_offset = [
    0,
    118,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_134]
pos = [
    315,
    293,
]
size = [
    95,
    136,
]
frame_offset = [
    31,
    118,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_135]
pos = [
    91,
    610,
]
size = [
    89,
    143,
]
frame_offset = [
    36,
    108,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_136]
pos = [
    602,
    283,
]
size = [
    66,
    38,
]
frame_offset = [
    0,
    184,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_137]
pos = [
    0,
    111,
]
size = [
    124,
    35,
]
frame_offset = [
    2,
    187,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_138]
pos = [
    241,
    978,
]
size = [
    64,
    37,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_139]
pos = [
    818,
    613,
]
size = [
    58,
    63,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_140]
pos = [
    740,
    634,
]
size = [
    64,
    37,
]
frame_offset = [
    62,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_141]
pos = [
    0,
    0,
]
size = [
    126,
    35,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_142]
pos = [
    373,
    955,
]
size = [
    64,
    37,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_143]
pos = [
    564,
    871,
]
size = [
    58,
    63,
]
frame_offset = [
    6,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_144]
pos = [
    110,
    222,
]
size = [
    7,
    11,
]
frame_offset = [
    119,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_145]
pos = [
    218,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_146]
pos = [
    128,
    381,
]
size = [
    7,
    10,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_147]
pos = [
    222,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    243,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_148]
pos = [
    119,
    222,
]
size = [
    7,
    11,
]
frame_offset = [
    119,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_149]
pos = [
    226,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    5,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_150]
pos = [
    137,
    381,
]
size = [
    7,
    10,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_151]
pos = [
    230,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    63,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_152]
pos = [
    602,
    323,
]
size = [
    66,
    38,
]
frame_offset = [
    0,
    4,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_153]
pos = [
    0,
    148,
]
size = [
    124,
    35,
]
frame_offset = [
    2,
    7,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_154]
pos = [
    630,
    761,
]
size = [
    64,
    37,
]
frame_offset = [
    60,
    4,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_155]
pos = [
    950,
    492,
]
size = [
    58,
    63,
]
frame_offset = [
    62,
    5,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_156]
pos = [
    818,
    574,
]
size = [
    64,
    37,
]
frame_offset = [
    62,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_157]
pos = [
    0,
    37,
]
size = [
    126,
    35,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_158]
pos = [
    439,
    955,
]
size = [
    64,
    37,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_159]
pos = [
    740,
    712,
]
size = [
    58,
    63,
]
frame_offset = [
    6,
    5,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_160]
pos = [
    0,
    982,
]
size = [
    66,
    38,
]
frame_offset = [
    0,
    184,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_161]
pos = [
    0,
    185,
]
size = [
    124,
    35,
]
frame_offset = [
    2,
    187,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_162]
pos = [
    564,
    832,
]
size = [
    64,
    37,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_163]
pos = [
    505,
    952,
]
size = [
    58,
    63,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_164]
pos = [
    950,
    453,
]
size = [
    64,
    37,
]
frame_offset = [
    62,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_165]
pos = [
    0,
    74,
]
size = [
    126,
    35,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_166]
pos = [
    740,
    673,
]
size = [
    64,
    37,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_167]
pos = [
    690,
    800,
]
size = [
    58,
    63,
]
frame_offset = [
    6,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_168]
pos = [
    110,
    381,
]
size = [
    7,
    11,
]
frame_offset = [
    119,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_169]
pos = [
    234,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    185,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_170]
pos = [
    146,
    381,
]
size = [
    7,
    10,
]
frame_offset = [
    0,
    211,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_171]
pos = [
    238,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    243,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_172]
pos = [
    119,
    381,
]
size = [
    7,
    11,
]
frame_offset = [
    119,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_173]
pos = [
    242,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    5,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_174]
pos = [
    155,
    381,
]
size = [
    7,
    10,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_175]
pos = [
    246,
    239,
]
size = [
    2,
    5,
]
frame_offset = [
    62,
    63,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_51]
pos = [
    498,
    716,
]
size = [
    64,
    126,
]
frame_offset = [
    60,
    110,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_52]
pos = [
    601,
    633,
]
size = [
    64,
    126,
]
frame_offset = [
    60,
    90,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_53]
pos = [
    674,
    618,
]
size = [
    64,
    113,
]
frame_offset = [
    60,
    106,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_54]
pos = [
    818,
    465,
]
size = [
    64,
    107,
]
frame_offset = [
    60,
    107,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_55]
pos = [
    937,
    781,
]
size = [
    34,
    73,
]
frame_offset = [
    60,
    107,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_56]
pos = [
    944,
    557,
]
size = [
    56,
    63,
]
frame_offset = [
    10,
    150,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_57]
pos = [
    937,
    623,
]
size = [
    52,
    52,
]
frame_offset = [
    2,
    165,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_58]
pos = [
    373,
    856,
]
size = [
    50,
    56,
]
frame_offset = [
    74,
    163,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_59]
pos = [
    806,
    678,
]
size = [
    58,
    51,
]
frame_offset = [
    60,
    159,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_63]
pos = [
    128,
    0,
]
size = [
    124,
    237,
]
frame_offset = [
    0,
    19,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_64]
pos = [
    565,
    936,
]
size = [
    54,
    58,
]
frame_offset = [
    12,
    150,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_65]
pos = [
    884,
    465,
]
size = [
    64,
    70,
]
frame_offset = [
    2,
    150,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_66]
pos = [
    680,
    923,
]
size = [
    44,
    53,
]
frame_offset = [
    2,
    164,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_67]
pos = [
    750,
    777,
]
size = [
    46,
    59,
]
frame_offset = [
    78,
    162,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_68]
pos = [
    564,
    761,
]
size = [
    64,
    69,
]
frame_offset = [
    60,
    153,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_69]
pos = [
    690,
    865,
]
size = [
    52,
    56,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_70]
pos = [
    953,
    0,
]
size = [
    68,
    239,
]
frame_offset = [
    0,
    17,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_71]
pos = [
    72,
    945,
]
size = [
    68,
    57,
]
frame_offset = [
    56,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_72]
pos = [
    459,
    179,
]
size = [
    82,
    95,
]
frame_offset = [
    42,
    66,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_73]
pos = [
    800,
    731,
]
size = [
    54,
    82,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_74]
pos = [
    91,
    755,
]
size = [
    78,
    93,
]
frame_offset = [
    46,
    68,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_75]
pos = [
    884,
    537,
]
size = [
    58,
    84,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_76]
pos = [
    88,
    850,
]
size = [
    78,
    93,
]
frame_offset = [
    46,
    67,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_77]
pos = [
    630,
    800,
]
size = [
    58,
    84,
]
frame_offset = [
    60,
    72,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_78]
pos = [
    878,
    623,
]
size = [
    57,
    183,
]
frame_offset = [
    8,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_79]
pos = [
    744,
    865,
]
size = [
    49,
    115,
]
frame_offset = [
    68,
    68,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_80]
pos = [
    798,
    815,
]
size = [
    40,
    102,
]
frame_offset = [
    12,
    74,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_81]
pos = [
    980,
    677,
]
size = [
    40,
    101,
]
frame_offset = [
    12,
    74,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_82]
pos = [
    795,
    919,
]
size = [
    40,
    100,
]
frame_offset = [
    12,
    75,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_83]
pos = [
    840,
    815,
]
size = [
    40,
    102,
]
frame_offset = [
    72,
    74,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_84]
pos = [
    937,
    677,
]
size = [
    41,
    102,
]
frame_offset = [
    72,
    74,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_85]
pos = [
    882,
    808,
]
size = [
    40,
    101,
]
frame_offset = [
    72,
    74,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_88]
pos = [
    110,
    239,
]
size = [
    106,
    140,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_89]
pos = [
    254,
    118,
]
size = [
    106,
    130,
]
frame_offset = [
    18,
    116,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_90]
pos = [
    254,
    0,
]
size = [
    112,
    116,
]
frame_offset = [
    16,
    140,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_91]
pos = [
    368,
    0,
]
size = [
    110,
    113,
]
frame_offset = [
    0,
    140,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_92]
pos = [
    528,
    480,
]
size = [
    71,
    215,
]
frame_offset = [
    31,
    22,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_93]
pos = [
    674,
    375,
]
size = [
    70,
    241,
]
frame_offset = [
    31,
    15,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_94]
pos = [
    746,
    391,
]
size = [
    70,
    241,
]
frame_offset = [
    31,
    15,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_95]
pos = [
    0,
    936,
]
size = [
    70,
    44,
]
frame_offset = [
    32,
    22,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_96]
pos = [
    973,
    781,
]
size = [
    21,
    238,
]
frame_offset = [
    56,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_97]
pos = [
    996,
    780,
]
size = [
    15,
    231,
]
frame_offset = [
    59,
    25,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_98]
pos = [
    543,
    179,
]
size = [
    22,
    42,
]
frame_offset = [
    44,
    142,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_99]
pos = [
    241,
    827,
]
size = [
    64,
    149,
]
frame_offset = [
    2,
    65,
]
frame_size = [
    128,
    256,
]
