[fixtures_counters_01_113]
pos = [
    860,
    506,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_114]
pos = [
    756,
    611,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_115]
pos = [
    523,
    885,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_116]
pos = [
    646,
    783,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_117]
pos = [
    860,
    577,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_118]
pos = [
    754,
    682,
]
size = [
    101,
    69,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_120]
pos = [
    511,
    450,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_121]
pos = [
    635,
    450,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_122]
pos = [
    759,
    449,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_123]
pos = [
    895,
    426,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_124]
pos = [
    0,
    486,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_125]
pos = [
    0,
    543,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_126]
pos = [
    0,
    600,
]
size = [
    122,
    55,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_128]
pos = [
    210,
    918,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_129]
pos = [
    439,
    714,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_130]
pos = [
    316,
    818,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_131]
pos = [
    548,
    609,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_132]
pos = [
    653,
    507,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_133]
pos = [
    316,
    887,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_134]
pos = [
    439,
    783,
]
size = [
    102,
    67,
]
frame_offset = [
    22,
    126,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_136]
pos = [
    0,
    428,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_137]
pos = [
    130,
    416,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_138]
pos = [
    259,
    315,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_139]
pos = [
    259,
    373,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_140]
pos = [
    257,
    431,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_141]
pos = [
    384,
    431,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_142]
pos = [
    390,
    0,
]
size = [
    125,
    56,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_144]
pos = [
    127,
    474,
]
size = [
    104,
    100,
]
frame_offset = [
    24,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_145]
pos = [
    444,
    609,
]
size = [
    102,
    100,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_146]
pos = [
    444,
    507,
]
size = [
    103,
    100,
]
frame_offset = [
    21,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_147]
pos = [
    0,
    657,
]
size = [
    104,
    100,
]
frame_offset = [
    1,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_148]
pos = [
    124,
    576,
]
size = [
    104,
    100,
]
frame_offset = [
    24,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_149]
pos = [
    549,
    507,
]
size = [
    102,
    100,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_150]
pos = [
    211,
    816,
]
size = [
    103,
    100,
]
frame_offset = [
    21,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_151]
pos = [
    233,
    489,
]
size = [
    104,
    100,
]
frame_offset = [
    1,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_152]
pos = [
    420,
    852,
]
size = [
    101,
    101,
]
frame_offset = [
    25,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_153]
pos = [
    548,
    678,
]
size = [
    101,
    102,
]
frame_offset = [
    1,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_154]
pos = [
    653,
    576,
]
size = [
    101,
    102,
]
frame_offset = [
    23,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_155]
pos = [
    543,
    782,
]
size = [
    101,
    101,
]
frame_offset = [
    2,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_156]
pos = [
    651,
    680,
]
size = [
    101,
    101,
]
frame_offset = [
    25,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_157]
pos = [
    335,
    714,
]
size = [
    102,
    102,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_158]
pos = [
    757,
    507,
]
size = [
    101,
    102,
]
frame_offset = [
    23,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_159]
pos = [
    105,
    903,
]
size = [
    103,
    101,
]
frame_offset = [
    2,
    2,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_160]
pos = [
    769,
    0,
]
size = [
    124,
    222,
]
frame_offset = [
    0,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_161]
pos = [
    0,
    759,
]
size = [
    103,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_162]
pos = [
    0,
    0,
]
size = [
    128,
    212,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_163]
pos = [
    390,
    58,
]
size = [
    124,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_164]
pos = [
    642,
    225,
]
size = [
    124,
    222,
]
frame_offset = [
    0,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_165]
pos = [
    106,
    678,
]
size = [
    103,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_166]
pos = [
    130,
    0,
]
size = [
    128,
    212,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_167]
pos = [
    517,
    0,
]
size = [
    124,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_168]
pos = [
    389,
    283,
]
size = [
    122,
    99,
]
frame_offset = [
    2,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_169]
pos = [
    748,
    866,
]
size = [
    99,
    111,
]
frame_offset = [
    4,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_170]
pos = [
    130,
    315,
]
size = [
    127,
    99,
]
frame_offset = [
    1,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_171]
pos = [
    646,
    854,
]
size = [
    100,
    111,
]
frame_offset = [
    24,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_172]
pos = [
    895,
    224,
]
size = [
    122,
    99,
]
frame_offset = [
    2,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_173]
pos = [
    856,
    761,
]
size = [
    99,
    111,
]
frame_offset = [
    4,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_174]
pos = [
    130,
    214,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_175]
pos = [
    754,
    753,
]
size = [
    100,
    111,
]
frame_offset = [
    24,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_176]
pos = [
    895,
    0,
]
size = [
    124,
    222,
]
frame_offset = [
    0,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_177]
pos = [
    230,
    591,
]
size = [
    103,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_178]
pos = [
    260,
    0,
]
size = [
    128,
    212,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_179]
pos = [
    643,
    0,
]
size = [
    124,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_180]
pos = [
    769,
    224,
]
size = [
    124,
    222,
]
frame_offset = [
    0,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_181]
pos = [
    339,
    489,
]
size = [
    103,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_182]
pos = [
    0,
    214,
]
size = [
    128,
    212,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_183]
pos = [
    516,
    225,
]
size = [
    124,
    223,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_184]
pos = [
    895,
    325,
]
size = [
    122,
    99,
]
frame_offset = [
    2,
    4,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_185]
pos = [
    849,
    874,
]
size = [
    99,
    111,
]
frame_offset = [
    4,
    3,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_186]
pos = [
    260,
    214,
]
size = [
    127,
    99,
]
frame_offset = [
    1,
    14,
]
frame_size = [
    128,
    256,
]

[fixtures_counters_01_187]
pos = [
    859,
    648,
]
size = [
    100,
    111,
]
frame_offset = [
    24,
    3,
]
frame_size = [
    128,
    256,
]
