[signs_one-off_02_327]
pos = [
    154,
    188,
]
size = [
    66,
    52,
]
frame_offset = [
    60,
    164,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_328]
pos = [
    846,
    701,
]
size = [
    49,
    73,
]
frame_offset = [
    17,
    124,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_329]
pos = [
    462,
    793,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_330]
pos = [
    754,
    480,
]
size = [
    64,
    85,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_331]
pos = [
    330,
    932,
]
size = [
    64,
    79,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_332]
pos = [
    594,
    684,
]
size = [
    64,
    78,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_333]
pos = [
    462,
    879,
]
size = [
    64,
    67,
]
frame_offset = [
    2,
    133,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_334]
pos = [
    660,
    662,
]
size = [
    64,
    73,
]
frame_offset = [
    60,
    39,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_335]
pos = [
    622,
    482,
]
size = [
    64,
    94,
]
frame_offset = [
    60,
    20,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_336]
pos = [
    198,
    646,
]
size = [
    64,
    129,
]
frame_offset = [
    2,
    50,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_337]
pos = [
    660,
    737,
]
size = [
    59,
    123,
]
frame_offset = [
    2,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_338]
pos = [
    659,
    862,
]
size = [
    50,
    88,
]
frame_offset = [
    74,
    88,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_339]
pos = [
    66,
    435,
]
size = [
    64,
    157,
]
frame_offset = [
    60,
    61,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_340]
pos = [
    492,
    167,
]
size = [
    64,
    159,
]
frame_offset = [
    60,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_341]
pos = [
    528,
    916,
]
size = [
    57,
    89,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_342]
pos = [
    462,
    698,
]
size = [
    64,
    93,
]
frame_offset = [
    60,
    22,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_343]
pos = [
    587,
    923,
]
size = [
    52,
    47,
]
frame_offset = [
    60,
    59,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_344]
pos = [
    912,
    613,
]
size = [
    49,
    95,
]
frame_offset = [
    17,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_345]
pos = [
    421,
    429,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_346]
pos = [
    330,
    500,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_347]
pos = [
    0,
    874,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_348]
pos = [
    789,
    699,
]
size = [
    55,
    71,
]
frame_offset = [
    69,
    145,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_349]
pos = [
    820,
    480,
]
size = [
    64,
    78,
]
frame_offset = [
    60,
    139,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_350]
pos = [
    528,
    865,
]
size = [
    61,
    49,
]
frame_offset = [
    60,
    143,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_352]
pos = [
    711,
    936,
]
size = [
    34,
    78,
]
frame_offset = [
    32,
    77,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_353]
pos = [
    198,
    890,
]
size = [
    64,
    96,
]
frame_offset = [
    2,
    78,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_354]
pos = [
    396,
    672,
]
size = [
    64,
    98,
]
frame_offset = [
    2,
    77,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_355]
pos = [
    396,
    772,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    87,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_356]
pos = [
    330,
    743,
]
size = [
    64,
    97,
]
frame_offset = [
    2,
    77,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_357]
pos = [
    264,
    789,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    76,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_358]
pos = [
    825,
    776,
]
size = [
    37,
    76,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_359]
pos = [
    897,
    710,
]
size = [
    39,
    114,
]
frame_offset = [
    85,
    85,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_360]
pos = [
    886,
    480,
]
size = [
    62,
    131,
]
frame_offset = [
    4,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_361]
pos = [
    66,
    734,
]
size = [
    64,
    130,
]
frame_offset = [
    2,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_362]
pos = [
    726,
    652,
]
size = [
    61,
    107,
]
frame_offset = [
    2,
    77,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_363]
pos = [
    66,
    866,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_364]
pos = [
    132,
    849,
]
size = [
    64,
    110,
]
frame_offset = [
    60,
    78,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_365]
pos = [
    528,
    601,
]
size = [
    64,
    94,
]
frame_offset = [
    60,
    104,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_366]
pos = [
    264,
    890,
]
size = [
    64,
    94,
]
frame_offset = [
    60,
    103,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_367]
pos = [
    462,
    601,
]
size = [
    64,
    95,
]
frame_offset = [
    60,
    103,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_368]
pos = [
    754,
    924,
]
size = [
    35,
    96,
]
frame_offset = [
    31,
    91,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_369]
pos = [
    223,
    175,
]
size = [
    64,
    177,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_370]
pos = [
    289,
    223,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    35,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_371]
pos = [
    132,
    242,
]
size = [
    64,
    179,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_372]
pos = [
    355,
    331,
]
size = [
    64,
    167,
]
frame_offset = [
    2,
    39,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_373]
pos = [
    66,
    594,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    75,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_374]
pos = [
    864,
    829,
]
size = [
    29,
    95,
]
frame_offset = [
    2,
    118,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_375]
pos = [
    679,
    952,
]
size = [
    30,
    58,
]
frame_offset = [
    94,
    84,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_376]
pos = [
    132,
    718,
]
size = [
    64,
    129,
]
frame_offset = [
    60,
    69,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_377]
pos = [
    791,
    924,
]
size = [
    32,
    72,
]
frame_offset = [
    60,
    103,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_378]
pos = [
    688,
    482,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_379]
pos = [
    493,
    0,
]
size = [
    64,
    165,
]
frame_offset = [
    60,
    44,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_380]
pos = [
    66,
    241,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_381]
pos = [
    0,
    241,
]
size = [
    64,
    194,
]
frame_offset = [
    60,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_382]
pos = [
    553,
    488,
]
size = [
    64,
    105,
]
frame_offset = [
    60,
    40,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_383]
pos = [
    711,
    862,
]
size = [
    41,
    72,
]
frame_offset = [
    60,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_384]
pos = [
    587,
    972,
]
size = [
    41,
    50,
]
frame_offset = [
    76,
    170,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_385]
pos = [
    864,
    776,
]
size = [
    30,
    51,
]
frame_offset = [
    36,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_386]
pos = [
    641,
    952,
]
size = [
    36,
    53,
]
frame_offset = [
    2,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_387]
pos = [
    0,
    75,
]
size = [
    83,
    164,
]
frame_offset = [
    41,
    20,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_388]
pos = [
    691,
    0,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_389]
pos = [
    559,
    166,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_390]
pos = [
    757,
    0,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_391]
pos = [
    625,
    162,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_392]
pos = [
    490,
    328,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_393]
pos = [
    823,
    0,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_394]
pos = [
    691,
    160,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_395]
pos = [
    556,
    328,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_396]
pos = [
    889,
    0,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_397]
pos = [
    757,
    160,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_398]
pos = [
    625,
    322,
]
size = [
    64,
    158,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_399]
pos = [
    938,
    720,
]
size = [
    36,
    139,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_400]
pos = [
    825,
    854,
]
size = [
    36,
    140,
]
frame_offset = [
    30,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_401]
pos = [
    955,
    0,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_402]
pos = [
    823,
    160,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_403]
pos = [
    691,
    320,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_404]
pos = [
    889,
    160,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_405]
pos = [
    757,
    320,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_406]
pos = [
    359,
    0,
]
size = [
    65,
    159,
]
frame_offset = [
    2,
    29,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_407]
pos = [
    594,
    764,
]
size = [
    63,
    157,
]
frame_offset = [
    3,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_408]
pos = [
    955,
    160,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_409]
pos = [
    823,
    320,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_410]
pos = [
    889,
    320,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_411]
pos = [
    955,
    320,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_412]
pos = [
    0,
    437,
]
size = [
    64,
    158,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_413]
pos = [
    1004,
    577,
]
size = [
    18,
    131,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_416]
pos = [
    778,
    772,
]
size = [
    45,
    150,
]
frame_offset = [
    21,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_417]
pos = [
    358,
    161,
]
size = [
    64,
    168,
]
frame_offset = [
    2,
    30,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_418]
pos = [
    426,
    82,
]
size = [
    64,
    175,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_419]
pos = [
    963,
    577,
]
size = [
    39,
    141,
]
frame_offset = [
    2,
    60,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_420]
pos = [
    950,
    480,
]
size = [
    57,
    95,
]
frame_offset = [
    9,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_421]
pos = [
    0,
    741,
]
size = [
    64,
    131,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_422]
pos = [
    264,
    671,
]
size = [
    64,
    116,
]
frame_offset = [
    2,
    58,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_423]
pos = [
    459,
    948,
]
size = [
    56,
    44,
]
frame_offset = [
    2,
    76,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_424]
pos = [
    396,
    946,
]
size = [
    61,
    74,
]
frame_offset = [
    5,
    145,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_425]
pos = [
    726,
    572,
]
size = [
    64,
    78,
]
frame_offset = [
    2,
    145,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_426]
pos = [
    0,
    0,
]
size = [
    126,
    73,
]
frame_offset = [
    2,
    150,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_427]
pos = [
    223,
    105,
]
size = [
    66,
    68,
]
frame_offset = [
    0,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_428]
pos = [
    528,
    786,
]
size = [
    64,
    77,
]
frame_offset = [
    2,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_429]
pos = [
    132,
    961,
]
size = [
    62,
    58,
]
frame_offset = [
    2,
    166,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_430]
pos = [
    594,
    595,
]
size = [
    64,
    87,
]
frame_offset = [
    2,
    131,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_431]
pos = [
    330,
    630,
]
size = [
    64,
    111,
]
frame_offset = [
    2,
    109,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_432]
pos = [
    660,
    578,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_433]
pos = [
    396,
    862,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_434]
pos = [
    291,
    0,
]
size = [
    66,
    81,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_435]
pos = [
    426,
    0,
]
size = [
    65,
    80,
]
frame_offset = [
    1,
    133,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_436]
pos = [
    528,
    697,
]
size = [
    64,
    87,
]
frame_offset = [
    2,
    133,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_437]
pos = [
    128,
    0,
]
size = [
    69,
    81,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_438]
pos = [
    198,
    777,
]
size = [
    64,
    111,
]
frame_offset = [
    2,
    109,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_439]
pos = [
    223,
    0,
]
size = [
    66,
    103,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_440]
pos = [
    976,
    720,
]
size = [
    36,
    122,
]
frame_offset = [
    30,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_441]
pos = [
    198,
    507,
]
size = [
    64,
    137,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_442]
pos = [
    291,
    83,
]
size = [
    65,
    138,
]
frame_offset = [
    1,
    56,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_443]
pos = [
    949,
    861,
]
size = [
    22,
    115,
]
frame_offset = [
    3,
    79,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_444]
pos = [
    896,
    826,
]
size = [
    25,
    133,
]
frame_offset = [
    41,
    42,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_445]
pos = [
    198,
    354,
]
size = [
    64,
    151,
]
frame_offset = [
    2,
    47,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_446]
pos = [
    132,
    423,
]
size = [
    64,
    156,
]
frame_offset = [
    2,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_447]
pos = [
    923,
    861,
]
size = [
    24,
    136,
]
frame_offset = [
    2,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_448]
pos = [
    976,
    844,
]
size = [
    19,
    127,
]
frame_offset = [
    47,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_449]
pos = [
    625,
    0,
]
size = [
    64,
    160,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_450]
pos = [
    559,
    0,
]
size = [
    64,
    164,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_451]
pos = [
    424,
    259,
]
size = [
    64,
    168,
]
frame_offset = [
    2,
    48,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_452]
pos = [
    85,
    83,
]
size = [
    67,
    152,
]
frame_offset = [
    2,
    60,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_456]
pos = [
    330,
    842,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    108,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_457]
pos = [
    487,
    488,
]
size = [
    64,
    111,
]
frame_offset = [
    2,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_458]
pos = [
    396,
    559,
]
size = [
    64,
    111,
]
frame_offset = [
    2,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_459]
pos = [
    154,
    83,
]
size = [
    67,
    103,
]
frame_offset = [
    2,
    113,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_460]
pos = [
    857,
    613,
]
size = [
    53,
    86,
]
frame_offset = [
    13,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_461]
pos = [
    132,
    581,
]
size = [
    64,
    135,
]
frame_offset = [
    2,
    83,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_462]
pos = [
    264,
    539,
]
size = [
    64,
    130,
]
frame_offset = [
    2,
    88,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_463]
pos = [
    721,
    761,
]
size = [
    55,
    90,
]
frame_offset = [
    2,
    128,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_464]
pos = [
    792,
    567,
]
size = [
    63,
    130,
]
frame_offset = [
    3,
    52,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_465]
pos = [
    264,
    399,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_02_466]
pos = [
    0,
    597,
]
size = [
    64,
    142,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]
