[crafted_05_100]
pos = [
    81,
    638,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_05_101]
pos = [
    572,
    234,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_05_102]
pos = [
    736,
    347,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_05_103]
pos = [
    243,
    469,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_05_104]
pos = [
    0,
    772,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_05_105]
pos = [
    654,
    234,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_05_106]
pos = [
    817,
    347,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_05_107]
pos = [
    324,
    459,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_05_108]
pos = [
    358,
    0,
]
size = [
    113,
    157,
]
frame_offset = [
    4,
    95,
]
frame_size = [
    128,
    256,
]

[crafted_05_109]
pos = [
    121,
    0,
]
size = [
    119,
    142,
]
frame_offset = [
    5,
    102,
]
frame_size = [
    128,
    256,
]

[crafted_05_110]
pos = [
    0,
    0,
]
size = [
    119,
    144,
]
frame_offset = [
    6,
    102,
]
frame_size = [
    128,
    256,
]

[crafted_05_111]
pos = [
    242,
    0,
]
size = [
    114,
    151,
]
frame_offset = [
    9,
    100,
]
frame_size = [
    128,
    256,
]

[crafted_05_112]
pos = [
    474,
    733,
]
size = [
    66,
    119,
]
frame_offset = [
    23,
    131,
]
frame_size = [
    128,
    256,
]

[crafted_05_113]
pos = [
    738,
    900,
]
size = [
    57,
    108,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[crafted_05_114]
pos = [
    782,
    685,
]
size = [
    60,
    106,
]
frame_offset = [
    62,
    122,
]
frame_size = [
    128,
    256,
]

[crafted_05_115]
pos = [
    715,
    555,
]
size = [
    66,
    114,
]
frame_offset = [
    37,
    134,
]
frame_size = [
    128,
    256,
]

[crafted_05_116]
pos = [
    646,
    582,
]
size = [
    66,
    119,
]
frame_offset = [
    23,
    131,
]
frame_size = [
    128,
    256,
]

[crafted_05_117]
pos = [
    906,
    730,
]
size = [
    57,
    108,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[crafted_05_118]
pos = [
    851,
    607,
]
size = [
    60,
    106,
]
frame_offset = [
    62,
    122,
]
frame_size = [
    128,
    256,
]

[crafted_05_119]
pos = [
    243,
    853,
]
size = [
    68,
    114,
]
frame_offset = [
    35,
    134,
]
frame_size = [
    128,
    256,
]

[crafted_05_120]
pos = [
    382,
    851,
]
size = [
    66,
    119,
]
frame_offset = [
    23,
    131,
]
frame_size = [
    128,
    256,
]

[crafted_05_121]
pos = [
    802,
    823,
]
size = [
    57,
    108,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[crafted_05_122]
pos = [
    678,
    776,
]
size = [
    60,
    106,
]
frame_offset = [
    62,
    122,
]
frame_size = [
    128,
    256,
]

[crafted_05_123]
pos = [
    898,
    408,
]
size = [
    66,
    114,
]
frame_offset = [
    37,
    134,
]
frame_size = [
    128,
    256,
]

[crafted_05_124]
pos = [
    542,
    733,
]
size = [
    66,
    119,
]
frame_offset = [
    23,
    131,
]
frame_size = [
    128,
    256,
]

[crafted_05_125]
pos = [
    965,
    730,
]
size = [
    57,
    108,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[crafted_05_126]
pos = [
    676,
    884,
]
size = [
    60,
    106,
]
frame_offset = [
    62,
    122,
]
frame_size = [
    128,
    256,
]

[crafted_05_127]
pos = [
    450,
    854,
]
size = [
    66,
    114,
]
frame_offset = [
    37,
    134,
]
frame_size = [
    128,
    256,
]

[crafted_05_128]
pos = [
    572,
    130,
]
size = [
    68,
    81,
]
frame_offset = [
    20,
    161,
]
frame_size = [
    128,
    256,
]

[crafted_05_129]
pos = [
    783,
    602,
]
size = [
    66,
    81,
]
frame_offset = [
    40,
    160,
]
frame_size = [
    128,
    256,
]

[crafted_05_130]
pos = [
    646,
    508,
]
size = [
    67,
    72,
]
frame_offset = [
    21,
    164,
]
frame_size = [
    128,
    256,
]

[crafted_05_131]
pos = [
    313,
    853,
]
size = [
    67,
    72,
]
frame_offset = [
    38,
    164,
]
frame_size = [
    128,
    256,
]

[crafted_05_132]
pos = [
    564,
    644,
]
size = [
    67,
    72,
]
frame_offset = [
    21,
    164,
]
frame_size = [
    128,
    256,
]

[crafted_05_133]
pos = [
    735,
    481,
]
size = [
    67,
    72,
]
frame_offset = [
    38,
    164,
]
frame_size = [
    128,
    256,
]

[crafted_05_134]
pos = [
    818,
    242,
]
size = [
    68,
    81,
]
frame_offset = [
    20,
    161,
]
frame_size = [
    128,
    256,
]

[crafted_05_135]
pos = [
    872,
    524,
]
size = [
    66,
    81,
]
frame_offset = [
    40,
    160,
]
frame_size = [
    128,
    256,
]

[crafted_05_136]
pos = [
    586,
    920,
]
size = [
    59,
    94,
]
frame_offset = [
    28,
    160,
]
frame_size = [
    128,
    256,
]

[crafted_05_137]
pos = [
    913,
    640,
]
size = [
    59,
    88,
]
frame_offset = [
    1,
    151,
]
frame_size = [
    128,
    256,
]

[crafted_05_138]
pos = [
    162,
    894,
]
size = [
    76,
    100,
]
frame_offset = [
    8,
    151,
]
frame_size = [
    128,
    256,
]

[crafted_05_139]
pos = [
    0,
    900,
]
size = [
    77,
    100,
]
frame_offset = [
    42,
    152,
]
frame_size = [
    128,
    256,
]

[crafted_05_140]
pos = [
    313,
    927,
]
size = [
    66,
    89,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[crafted_05_141]
pos = [
    610,
    823,
]
size = [
    64,
    95,
]
frame_offset = [
    39,
    161,
]
frame_size = [
    128,
    256,
]

[crafted_05_144]
pos = [
    804,
    481,
]
size = [
    66,
    119,
]
frame_offset = [
    23,
    131,
]
frame_size = [
    128,
    256,
]

[crafted_05_145]
pos = [
    861,
    840,
]
size = [
    57,
    108,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[crafted_05_146]
pos = [
    844,
    715,
]
size = [
    60,
    106,
]
frame_offset = [
    62,
    122,
]
frame_size = [
    128,
    256,
]

[crafted_05_147]
pos = [
    404,
    723,
]
size = [
    68,
    114,
]
frame_offset = [
    35,
    134,
]
frame_size = [
    128,
    256,
]

[crafted_05_149]
pos = [
    218,
    144,
]
size = [
    1,
    1,
]
frame_offset = [
    62,
    0,
]
frame_size = [
    128,
    256,
]

[crafted_05_62]
pos = [
    645,
    0,
]
size = [
    82,
    232,
]
frame_offset = [
    16,
    5,
]
frame_size = [
    128,
    256,
]

[crafted_05_63]
pos = [
    488,
    130,
]
size = [
    82,
    232,
]
frame_offset = [
    16,
    5,
]
frame_size = [
    128,
    256,
]

[crafted_05_64]
pos = [
    736,
    242,
]
size = [
    80,
    103,
]
frame_offset = [
    16,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_65]
pos = [
    610,
    718,
]
size = [
    66,
    103,
]
frame_offset = [
    30,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_66]
pos = [
    518,
    854,
]
size = [
    66,
    103,
]
frame_offset = [
    30,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_67]
pos = [
    714,
    671,
]
size = [
    66,
    103,
]
frame_offset = [
    30,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_68]
pos = [
    0,
    399,
]
size = [
    82,
    103,
]
frame_offset = [
    14,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_69]
pos = [
    813,
    0,
]
size = [
    82,
    103,
]
frame_offset = [
    14,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_70]
pos = [
    729,
    122,
]
size = [
    82,
    103,
]
frame_offset = [
    14,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_71]
pos = [
    487,
    364,
]
size = [
    82,
    103,
]
frame_offset = [
    14,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_72]
pos = [
    977,
    152,
]
size = [
    36,
    101,
]
frame_offset = [
    54,
    140,
]
frame_size = [
    128,
    256,
]

[crafted_05_73]
pos = [
    979,
    51,
]
size = [
    38,
    48,
]
frame_offset = [
    44,
    186,
]
frame_size = [
    128,
    256,
]

[crafted_05_74]
pos = [
    111,
    146,
]
size = [
    105,
    103,
]
frame_offset = [
    14,
    145,
]
frame_size = [
    128,
    256,
]

[crafted_05_75]
pos = [
    0,
    146,
]
size = [
    109,
    102,
]
frame_offset = [
    9,
    146,
]
frame_size = [
    128,
    256,
]

[crafted_05_76]
pos = [
    729,
    0,
]
size = [
    82,
    120,
]
frame_offset = [
    15,
    121,
]
frame_size = [
    128,
    256,
]

[crafted_05_77]
pos = [
    106,
    386,
]
size = [
    89,
    116,
]
frame_offset = [
    28,
    126,
]
frame_size = [
    128,
    256,
]

[crafted_05_80]
pos = [
    401,
    289,
]
size = [
    84,
    168,
]
frame_offset = [
    13,
    72,
]
frame_size = [
    128,
    256,
]

[crafted_05_81]
pos = [
    0,
    250,
]
size = [
    104,
    147,
]
frame_offset = [
    1,
    100,
]
frame_size = [
    128,
    256,
]

[crafted_05_82]
pos = [
    218,
    153,
]
size = [
    91,
    155,
]
frame_offset = [
    32,
    89,
]
frame_size = [
    128,
    256,
]

[crafted_05_83]
pos = [
    940,
    524,
]
size = [
    60,
    114,
]
frame_offset = [
    47,
    126,
]
frame_size = [
    128,
    256,
]

[crafted_05_84]
pos = [
    740,
    793,
]
size = [
    60,
    105,
]
frame_offset = [
    27,
    135,
]
frame_size = [
    128,
    256,
]

[crafted_05_85]
pos = [
    208,
    310,
]
size = [
    87,
    157,
]
frame_offset = [
    10,
    90,
]
frame_size = [
    128,
    256,
]

[crafted_05_86]
pos = [
    106,
    251,
]
size = [
    100,
    133,
]
frame_offset = [
    28,
    104,
]
frame_size = [
    128,
    256,
]

[crafted_05_87]
pos = [
    311,
    159,
]
size = [
    88,
    167,
]
frame_offset = [
    26,
    74,
]
frame_size = [
    128,
    256,
]

[crafted_05_88]
pos = [
    559,
    0,
]
size = [
    84,
    128,
]
frame_offset = [
    39,
    108,
]
frame_size = [
    128,
    256,
]

[crafted_05_89]
pos = [
    485,
    597,
]
size = [
    77,
    134,
]
frame_offset = [
    35,
    96,
]
frame_size = [
    128,
    256,
]

[crafted_05_90]
pos = [
    324,
    715,
]
size = [
    78,
    134,
]
frame_offset = [
    24,
    95,
]
frame_size = [
    128,
    256,
]

[crafted_05_91]
pos = [
    297,
    328,
]
size = [
    85,
    128,
]
frame_offset = [
    11,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_05_92]
pos = [
    162,
    766,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_05_93]
pos = [
    571,
    371,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_05_94]
pos = [
    0,
    638,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_05_95]
pos = [
    486,
    469,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_05_96]
pos = [
    243,
    725,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_05_97]
pos = [
    653,
    371,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_05_98]
pos = [
    162,
    504,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_05_99]
pos = [
    81,
    894,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_05_on_56]
pos = [
    240,
    969,
]
size = [
    66,
    41,
]
frame_offset = [
    30,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_on_6]
pos = [
    979,
    101,
]
size = [
    37,
    49,
]
frame_offset = [
    74,
    176,
]
frame_size = [
    128,
    256,
]

[crafted_05_on_60]
pos = [
    381,
    972,
]
size = [
    66,
    41,
]
frame_offset = [
    31,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_on_64]
pos = [
    450,
    970,
]
size = [
    66,
    41,
]
frame_offset = [
    30,
    136,
]
frame_size = [
    128,
    256,
]

[crafted_05_on_7]
pos = [
    979,
    0,
]
size = [
    38,
    49,
]
frame_offset = [
    17,
    176,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_0]
pos = [
    473,
    0,
]
size = [
    84,
    128,
]
frame_offset = [
    39,
    108,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_1]
pos = [
    567,
    508,
]
size = [
    77,
    134,
]
frame_offset = [
    35,
    96,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_10]
pos = [
    898,
    274,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_11]
pos = [
    162,
    638,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_12]
pos = [
    243,
    597,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_13]
pos = [
    897,
    0,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_14]
pos = [
    0,
    504,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_2]
pos = [
    405,
    587,
]
size = [
    78,
    134,
]
frame_offset = [
    24,
    95,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_3]
pos = [
    401,
    159,
]
size = [
    85,
    128,
]
frame_offset = [
    11,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_4]
pos = [
    81,
    766,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_5]
pos = [
    813,
    105,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_6]
pos = [
    81,
    504,
]
size = [
    79,
    132,
]
frame_offset = [
    20,
    98,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_7]
pos = [
    405,
    459,
]
size = [
    79,
    126,
]
frame_offset = [
    15,
    105,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_8]
pos = [
    324,
    587,
]
size = [
    79,
    126,
]
frame_offset = [
    38,
    107,
]
frame_size = [
    128,
    256,
]

[crafted_skins_drying_01_9]
pos = [
    895,
    137,
]
size = [
    80,
    135,
]
frame_offset = [
    33,
    97,
]
frame_size = [
    128,
    256,
]
