[roofs_burnt_01_102]
pos = [
    520,
    438,
]
size = [
    128,
    86,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_103]
pos = [
    130,
    902,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_104]
pos = [
    910,
    0,
]
size = [
    88,
    66,
]
frame_offset = [
    40,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_105]
pos = [
    910,
    68,
]
size = [
    88,
    65,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_112]
pos = [
    130,
    141,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_113]
pos = [
    0,
    330,
]
size = [
    128,
    131,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_114]
pos = [
    260,
    0,
]
size = [
    128,
    134,
]
frame_offset = [
    0,
    122,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_115]
pos = [
    0,
    194,
]
size = [
    128,
    134,
]
frame_offset = [
    0,
    58,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_116]
pos = [
    260,
    136,
]
size = [
    128,
    130,
]
frame_offset = [
    0,
    61,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_117]
pos = [
    130,
    274,
]
size = [
    128,
    130,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_118]
pos = [
    0,
    0,
]
size = [
    128,
    192,
]
frame_offset = [
    0,
    53,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_119]
pos = [
    130,
    0,
]
size = [
    128,
    139,
]
frame_offset = [
    0,
    116,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_120]
pos = [
    260,
    880,
]
size = [
    128,
    68,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_121]
pos = [
    520,
    611,
]
size = [
    128,
    74,
]
frame_offset = [
    0,
    152,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_122]
pos = [
    0,
    960,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_123]
pos = [
    520,
    822,
]
size = [
    128,
    45,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_124]
pos = [
    520,
    526,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_125]
pos = [
    390,
    659,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_126]
pos = [
    390,
    744,
]
size = [
    128,
    72,
]
frame_offset = [
    0,
    154,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_127]
pos = [
    260,
    796,
]
size = [
    128,
    82,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_128]
pos = [
    390,
    131,
]
size = [
    128,
    113,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_129]
pos = [
    260,
    268,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_130]
pos = [
    520,
    131,
]
size = [
    128,
    105,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_131]
pos = [
    650,
    415,
]
size = [
    128,
    82,
]
frame_offset = [
    0,
    174,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_132]
pos = [
    390,
    246,
]
size = [
    128,
    113,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_133]
pos = [
    390,
    0,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_134]
pos = [
    520,
    0,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_01_135]
pos = [
    650,
    0,
]
size = [
    128,
    113,
]
frame_offset = [
    0,
    143,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_0]
pos = [
    130,
    506,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_1]
pos = [
    390,
    361,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_10]
pos = [
    130,
    406,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_11]
pos = [
    0,
    663,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_12]
pos = [
    260,
    399,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_13]
pos = [
    130,
    605,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_16]
pos = [
    130,
    987,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_17]
pos = [
    780,
    666,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_18]
pos = [
    650,
    801,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_19]
pos = [
    780,
    700,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_2]
pos = [
    260,
    499,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_20]
pos = [
    650,
    835,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_21]
pos = [
    390,
    953,
]
size = [
    126,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_24]
pos = [
    518,
    968,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_25]
pos = [
    779,
    734,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_26]
pos = [
    649,
    869,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_27]
pos = [
    779,
    768,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_28]
pos = [
    649,
    903,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_29]
pos = [
    778,
    802,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_3]
pos = [
    520,
    338,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_32]
pos = [
    0,
    762,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_33]
pos = [
    520,
    238,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_34]
pos = [
    780,
    567,
]
size = [
    127,
    97,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_35]
pos = [
    650,
    115,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_36]
pos = [
    780,
    0,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_37]
pos = [
    130,
    704,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_4]
pos = [
    650,
    215,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_40]
pos = [
    650,
    636,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_41]
pos = [
    520,
    687,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    30,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_42]
pos = [
    390,
    818,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    62,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_43]
pos = [
    520,
    755,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_44]
pos = [
    260,
    950,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_45]
pos = [
    650,
    499,
]
size = [
    128,
    67,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_48]
pos = [
    649,
    937,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_49]
pos = [
    778,
    836,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_5]
pos = [
    390,
    461,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_50]
pos = [
    646,
    971,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_51]
pos = [
    777,
    870,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_52]
pos = [
    777,
    904,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_53]
pos = [
    777,
    938,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_56]
pos = [
    650,
    702,
]
size = [
    127,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_57]
pos = [
    780,
    100,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_58]
pos = [
    650,
    315,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_59]
pos = [
    520,
    869,
]
size = [
    127,
    97,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_60]
pos = [
    780,
    200,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_61]
pos = [
    650,
    568,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_64]
pos = [
    260,
    598,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_65]
pos = [
    780,
    300,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_66]
pos = [
    0,
    861,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_67]
pos = [
    780,
    400,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_68]
pos = [
    0,
    463,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_69]
pos = [
    130,
    803,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_72]
pos = [
    390,
    560,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_73]
pos = [
    390,
    886,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_74]
pos = [
    780,
    500,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_8]
pos = [
    260,
    697,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_9]
pos = [
    0,
    563,
]
size = [
    128,
    98,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]
