[walls_interior_house_07_108]
pos = [
    68,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_109]
pos = [
    136,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_110]
pos = [
    680,
    888,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_111]
pos = [
    748,
    887,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_112]
pos = [
    204,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_113]
pos = [
    272,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_114]
pos = [
    340,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_115]
pos = [
    408,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_116]
pos = [
    680,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_117]
pos = [
    748,
    684,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_118]
pos = [
    884,
    684,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_119]
pos = [
    476,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_120]
pos = [
    748,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_121]
pos = [
    544,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_122]
pos = [
    816,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_123]
pos = [
    612,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_124]
pos = [
    884,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_125]
pos = [
    680,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_126]
pos = [
    952,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_07_127]
pos = [
    748,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_0]
pos = [
    0,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_1]
pos = [
    204,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_10]
pos = [
    0,
    0,
]
size = [
    66,
    256,
]

[walls_interior_house_08_11]
pos = [
    68,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_12]
pos = [
    816,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_13]
pos = [
    884,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_14]
pos = [
    816,
    887,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_15]
pos = [
    884,
    886,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_16]
pos = [
    952,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_17]
pos = [
    0,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_18]
pos = [
    68,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_19]
pos = [
    136,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_2]
pos = [
    272,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_20]
pos = [
    0,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_21]
pos = [
    816,
    684,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_22]
pos = [
    952,
    660,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_23]
pos = [
    272,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_24]
pos = [
    68,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_25]
pos = [
    340,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_26]
pos = [
    136,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_27]
pos = [
    408,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_28]
pos = [
    204,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_29]
pos = [
    476,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_3]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_30]
pos = [
    544,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_31]
pos = [
    340,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_32]
pos = [
    612,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_33]
pos = [
    408,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_34]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_35]
pos = [
    476,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_36]
pos = [
    136,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_37]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_38]
pos = [
    680,
    684,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_39]
pos = [
    544,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_4]
pos = [
    476,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_40]
pos = [
    204,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_41]
pos = [
    272,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_42]
pos = [
    340,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_43]
pos = [
    408,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_5]
pos = [
    612,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_6]
pos = [
    952,
    456,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_7]
pos = [
    884,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_8]
pos = [
    544,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_08_9]
pos = [
    612,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
