[walls_interior_house_12_101]
pos = [
    0,
    258,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_102]
pos = [
    759,
    0,
]
size = [
    67,
    220,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_103]
pos = [
    136,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_104]
pos = [
    0,
    0,
]
size = [
    67,
    256,
]

[walls_interior_house_12_105]
pos = [
    69,
    0,
]
size = [
    67,
    256,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_106]
pos = [
    138,
    0,
]
size = [
    67,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_107]
pos = [
    207,
    0,
]
size = [
    67,
    256,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_108]
pos = [
    276,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_109]
pos = [
    69,
    258,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_110]
pos = [
    621,
    228,
]
size = [
    67,
    175,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_111]
pos = [
    897,
    0,
]
size = [
    67,
    174,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_112]
pos = [
    345,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_113]
pos = [
    138,
    258,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_114]
pos = [
    414,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_115]
pos = [
    207,
    258,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_116]
pos = [
    204,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_117]
pos = [
    552,
    228,
]
size = [
    67,
    201,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_118]
pos = [
    828,
    0,
]
size = [
    67,
    201,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_119]
pos = [
    276,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_120]
pos = [
    276,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_121]
pos = [
    345,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_122]
pos = [
    414,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_123]
pos = [
    483,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_124]
pos = [
    552,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_125]
pos = [
    621,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_126]
pos = [
    690,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_12_127]
pos = [
    483,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_0]
pos = [
    68,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_1]
pos = [
    480,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_10]
pos = [
    690,
    228,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_11]
pos = [
    759,
    222,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_12]
pos = [
    0,
    744,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_13]
pos = [
    68,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_14]
pos = [
    272,
    912,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_15]
pos = [
    340,
    912,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_16]
pos = [
    344,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_17]
pos = [
    136,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_18]
pos = [
    412,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_19]
pos = [
    204,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_2]
pos = [
    758,
    480,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_20]
pos = [
    272,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_21]
pos = [
    826,
    689,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_22]
pos = [
    895,
    662,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_23]
pos = [
    552,
    431,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_24]
pos = [
    340,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_25]
pos = [
    621,
    405,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_26]
pos = [
    408,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_27]
pos = [
    476,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_28]
pos = [
    689,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_29]
pos = [
    548,
    659,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_3]
pos = [
    827,
    461,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_30]
pos = [
    620,
    633,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_4]
pos = [
    828,
    203,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_5]
pos = [
    896,
    434,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_6]
pos = [
    757,
    708,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_7]
pos = [
    688,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_8]
pos = [
    897,
    176,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_13_9]
pos = [
    0,
    486,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
