[walls_interior_house_15_31]
pos = [
    0,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_32]
pos = [
    68,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_33]
pos = [
    136,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_34]
pos = [
    204,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_35]
pos = [
    272,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_36]
pos = [
    0,
    0,
]
size = [
    66,
    256,
]

[walls_interior_house_15_37]
pos = [
    612,
    684,
]
size = [
    66,
    203,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_38]
pos = [
    884,
    456,
]
size = [
    66,
    203,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_39]
pos = [
    544,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_40]
pos = [
    340,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_41]
pos = [
    68,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_42]
pos = [
    136,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_43]
pos = [
    204,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_44]
pos = [
    612,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_45]
pos = [
    408,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_46]
pos = [
    612,
    889,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_47]
pos = [
    680,
    889,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_48]
pos = [
    680,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_49]
pos = [
    476,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_50]
pos = [
    748,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_51]
pos = [
    544,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_52]
pos = [
    816,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_53]
pos = [
    748,
    684,
]
size = [
    66,
    202,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_54]
pos = [
    884,
    661,
]
size = [
    66,
    201,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_55]
pos = [
    612,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_56]
pos = [
    884,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_57]
pos = [
    680,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_58]
pos = [
    952,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_59]
pos = [
    748,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_60]
pos = [
    816,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_61]
pos = [
    884,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_62]
pos = [
    952,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_63]
pos = [
    0,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_64]
pos = [
    68,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_65]
pos = [
    136,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_66]
pos = [
    204,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_67]
pos = [
    0,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_68]
pos = [
    272,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_69]
pos = [
    680,
    684,
]
size = [
    66,
    203,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_70]
pos = [
    952,
    456,
]
size = [
    66,
    203,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_71]
pos = [
    272,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_72]
pos = [
    68,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_73]
pos = [
    340,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_74]
pos = [
    408,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_75]
pos = [
    476,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_76]
pos = [
    340,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_77]
pos = [
    136,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_78]
pos = [
    748,
    888,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_79]
pos = [
    816,
    888,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_80]
pos = [
    408,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_81]
pos = [
    204,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_82]
pos = [
    476,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_83]
pos = [
    272,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_84]
pos = [
    544,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_85]
pos = [
    816,
    684,
]
size = [
    66,
    202,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_86]
pos = [
    952,
    661,
]
size = [
    66,
    201,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_87]
pos = [
    340,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_88]
pos = [
    612,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_89]
pos = [
    408,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_90]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_91]
pos = [
    476,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_92]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_93]
pos = [
    544,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_house_15_94]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]
