[walls_exterior_house_low_01_102]
pos = [
    0,
    438,
]
size = [
    128,
    67,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_103]
pos = [
    339,
    425,
]
size = [
    6,
    37,
]
frame_offset = [
    60,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_104]
pos = [
    481,
    581,
]
size = [
    66,
    106,
]
frame_offset = [
    0,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_105]
pos = [
    647,
    229,
]
size = [
    68,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_106]
pos = [
    0,
    330,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_107]
pos = [
    469,
    395,
]
size = [
    6,
    76,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_108]
pos = [
    206,
    861,
]
size = [
    66,
    106,
]
frame_offset = [
    0,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_109]
pos = [
    924,
    0,
]
size = [
    68,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_110]
pos = [
    130,
    283,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_111]
pos = [
    994,
    0,
]
size = [
    6,
    76,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_112]
pos = [
    927,
    287,
]
size = [
    66,
    75,
]
frame_offset = [
    0,
    151,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_113]
pos = [
    927,
    208,
]
size = [
    68,
    77,
]
frame_offset = [
    60,
    149,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_114]
pos = [
    343,
    809,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_115]
pos = [
    787,
    228,
]
size = [
    68,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_116]
pos = [
    617,
    611,
]
size = [
    66,
    74,
]
frame_offset = [
    0,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_117]
pos = [
    857,
    310,
]
size = [
    68,
    76,
]
frame_offset = [
    60,
    150,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_118]
pos = [
    549,
    613,
]
size = [
    66,
    97,
]
frame_offset = [
    0,
    129,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_119]
pos = [
    924,
    108,
]
size = [
    68,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_120]
pos = [
    137,
    953,
]
size = [
    66,
    67,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_121]
pos = [
    646,
    439,
]
size = [
    68,
    67,
]
frame_offset = [
    60,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_122]
pos = [
    260,
    356,
]
size = [
    128,
    67,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_123]
pos = [
    347,
    425,
]
size = [
    6,
    37,
]
frame_offset = [
    60,
    159,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_128]
pos = [
    275,
    800,
]
size = [
    66,
    105,
]
frame_offset = [
    0,
    121,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_129]
pos = [
    717,
    228,
]
size = [
    68,
    105,
]
frame_offset = [
    60,
    121,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_130]
pos = [
    260,
    164,
]
size = [
    128,
    105,
]
frame_offset = [
    0,
    121,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_131]
pos = [
    1002,
    0,
]
size = [
    6,
    75,
]
frame_offset = [
    60,
    121,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_136]
pos = [
    685,
    508,
]
size = [
    66,
    78,
]
frame_offset = [
    0,
    148,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_137]
pos = [
    787,
    328,
]
size = [
    68,
    78,
]
frame_offset = [
    60,
    148,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_138]
pos = [
    413,
    677,
]
size = [
    66,
    100,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_low_01_139]
pos = [
    717,
    335,
]
size = [
    68,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_0]
pos = [
    617,
    510,
]
size = [
    66,
    99,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_1]
pos = [
    413,
    512,
]
size = [
    66,
    163,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_10]
pos = [
    927,
    364,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_11]
pos = [
    617,
    687,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_12]
pos = [
    548,
    844,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_13]
pos = [
    717,
    435,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_14]
pos = [
    0,
    898,
]
size = [
    66,
    115,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_15]
pos = [
    481,
    689,
]
size = [
    66,
    81,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_16]
pos = [
    207,
    681,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_17]
pos = [
    390,
    215,
]
size = [
    114,
    178,
]
frame_offset = [
    14,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_18]
pos = [
    481,
    449,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_19]
pos = [
    683,
    843,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_2]
pos = [
    69,
    788,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_20]
pos = [
    518,
    0,
]
size = [
    122,
    212,
]
frame_offset = [
    2,
    14,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_21]
pos = [
    331,
    425,
]
size = [
    6,
    69,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_24]
pos = [
    130,
    391,
]
size = [
    128,
    99,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_25]
pos = [
    0,
    0,
]
size = [
    128,
    164,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_26]
pos = [
    0,
    507,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_27]
pos = [
    642,
    0,
]
size = [
    69,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_28]
pos = [
    130,
    0,
]
size = [
    128,
    163,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_29]
pos = [
    576,
    409,
]
size = [
    68,
    99,
]
frame_offset = [
    59,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_3]
pos = [
    784,
    0,
]
size = [
    68,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_30]
pos = [
    506,
    215,
]
size = [
    69,
    116,
]
frame_offset = [
    59,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_31]
pos = [
    857,
    228,
]
size = [
    68,
    80,
]
frame_offset = [
    59,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_32]
pos = [
    411,
    860,
]
size = [
    65,
    66,
]
frame_offset = [
    2,
    161,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_33]
pos = [
    549,
    712,
]
size = [
    65,
    130,
]
frame_offset = [
    2,
    97,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_34]
pos = [
    857,
    388,
]
size = [
    65,
    194,
]
frame_offset = [
    2,
    33,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_35]
pos = [
    481,
    772,
]
size = [
    65,
    193,
]
frame_offset = [
    59,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_36]
pos = [
    753,
    503,
]
size = [
    65,
    129,
]
frame_offset = [
    59,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_37]
pos = [
    260,
    425,
]
size = [
    69,
    69,
]
frame_offset = [
    59,
    158,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_38]
pos = [
    130,
    165,
]
size = [
    128,
    116,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_39]
pos = [
    207,
    599,
]
size = [
    67,
    80,
]
frame_offset = [
    0,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_4]
pos = [
    260,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_40]
pos = [
    69,
    507,
]
size = [
    67,
    179,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_41]
pos = [
    713,
    0,
]
size = [
    69,
    179,
]
frame_offset = [
    59,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_42]
pos = [
    138,
    492,
]
size = [
    67,
    131,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_43]
pos = [
    0,
    736,
]
size = [
    67,
    101,
]
frame_offset = [
    59,
    126,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_44]
pos = [
    390,
    0,
]
size = [
    126,
    213,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_45]
pos = [
    460,
    395,
]
size = [
    7,
    72,
]
frame_offset = [
    60,
    126,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_48]
pos = [
    409,
    928,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_49]
pos = [
    818,
    714,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_5]
pos = [
    69,
    688,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_50]
pos = [
    952,
    558,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_51]
pos = [
    952,
    659,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_52]
pos = [
    680,
    944,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_53]
pos = [
    475,
    967,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_54]
pos = [
    950,
    885,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_55]
pos = [
    950,
    743,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_56]
pos = [
    818,
    815,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_57]
pos = [
    751,
    828,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_58]
pos = [
    884,
    714,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_59]
pos = [
    749,
    929,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_6]
pos = [
    390,
    395,
]
size = [
    68,
    115,
]
frame_offset = [
    60,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_60]
pos = [
    884,
    815,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_61]
pos = [
    883,
    957,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_62]
pos = [
    950,
    937,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_63]
pos = [
    817,
    899,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_64]
pos = [
    260,
    271,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    144,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_65]
pos = [
    207,
    496,
]
size = [
    67,
    101,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_66]
pos = [
    647,
    337,
]
size = [
    68,
    100,
]
frame_offset = [
    59,
    127,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_67]
pos = [
    274,
    907,
]
size = [
    66,
    80,
]
frame_offset = [
    59,
    147,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_68]
pos = [
    412,
    779,
]
size = [
    66,
    79,
]
frame_offset = [
    1,
    148,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_69]
pos = [
    0,
    839,
]
size = [
    67,
    57,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_7]
pos = [
    276,
    496,
]
size = [
    67,
    81,
]
frame_offset = [
    60,
    175,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_70]
pos = [
    685,
    588,
]
size = [
    65,
    59,
]
frame_offset = [
    59,
    168,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_71]
pos = [
    342,
    909,
]
size = [
    65,
    81,
]
frame_offset = [
    59,
    146,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_72]
pos = [
    549,
    510,
]
size = [
    66,
    101,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_73]
pos = [
    276,
    631,
]
size = [
    66,
    167,
]
frame_offset = [
    0,
    59,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_74]
pos = [
    138,
    725,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_75]
pos = [
    854,
    0,
]
size = [
    68,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_76]
pos = [
    0,
    166,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_77]
pos = [
    138,
    625,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_78]
pos = [
    506,
    333,
]
size = [
    68,
    114,
]
frame_offset = [
    60,
    112,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_79]
pos = [
    276,
    579,
]
size = [
    67,
    50,
]
frame_offset = [
    60,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_8]
pos = [
    884,
    891,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_80]
pos = [
    950,
    819,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_81]
pos = [
    820,
    584,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_82]
pos = [
    685,
    649,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_83]
pos = [
    752,
    634,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_84]
pos = [
    886,
    584,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_85]
pos = [
    787,
    408,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_86]
pos = [
    344,
    692,
]
size = [
    66,
    115,
]
frame_offset = [
    0,
    111,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_87]
pos = [
    205,
    969,
]
size = [
    66,
    50,
]
frame_offset = [
    0,
    176,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_88]
pos = [
    345,
    512,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_89]
pos = [
    577,
    229,
]
size = [
    68,
    178,
]
frame_offset = [
    60,
    48,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_01_9]
pos = [
    614,
    881,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]
