[walls_interior_detailing_bathroom_03_100]
pos = [
    469,
    843,
]
size = [
    15,
    155,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_101]
pos = [
    402,
    706,
]
size = [
    65,
    155,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_102]
pos = [
    603,
    524,
]
size = [
    65,
    155,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_103]
pos = [
    1006,
    0,
]
size = [
    15,
    156,
]
frame_offset = [
    110,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_104]
pos = [
    871,
    364,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_105]
pos = [
    737,
    522,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_106]
pos = [
    603,
    681,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_107]
pos = [
    937,
    364,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_108]
pos = [
    268,
    868,
]
size = [
    65,
    154,
]
frame_offset = [
    1,
    72,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_109]
pos = [
    248,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_110]
pos = [
    315,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_111]
pos = [
    67,
    727,
]
size = [
    65,
    161,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_112]
pos = [
    670,
    364,
]
size = [
    65,
    156,
]
frame_offset = [
    1,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_113]
pos = [
    382,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_114]
pos = [
    804,
    521,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_115]
pos = [
    201,
    728,
]
size = [
    65,
    158,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_116]
pos = [
    335,
    546,
]
size = [
    65,
    160,
]
frame_offset = [
    1,
    66,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_117]
pos = [
    0,
    181,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_118]
pos = [
    335,
    708,
]
size = [
    65,
    156,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_119]
pos = [
    268,
    546,
]
size = [
    65,
    161,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_120]
pos = [
    0,
    909,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_121]
pos = [
    67,
    890,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_122]
pos = [
    469,
    686,
]
size = [
    65,
    155,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_123]
pos = [
    67,
    181,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_124]
pos = [
    670,
    679,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_125]
pos = [
    268,
    709,
]
size = [
    65,
    157,
]
frame_offset = [
    60,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_126]
pos = [
    0,
    1009,
]
size = [
    1,
    1,
]
frame_offset = [
    1,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_127]
pos = [
    3,
    1009,
]
size = [
    1,
    1,
]
frame_offset = [
    124,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_128]
pos = [
    134,
    181,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_129]
pos = [
    201,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_130]
pos = [
    268,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_131]
pos = [
    335,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_132]
pos = [
    423,
    863,
]
size = [
    19,
    156,
]
frame_offset = [
    1,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_133]
pos = [
    486,
    843,
]
size = [
    13,
    155,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_134]
pos = [
    516,
    843,
]
size = [
    12,
    154,
]
frame_offset = [
    54,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_135]
pos = [
    985,
    0,
]
size = [
    19,
    157,
]
frame_offset = [
    106,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_136]
pos = [
    402,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_137]
pos = [
    449,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_138]
pos = [
    516,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_139]
pos = [
    583,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_140]
pos = [
    650,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_141]
pos = [
    469,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_142]
pos = [
    717,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_143]
pos = [
    536,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_144]
pos = [
    784,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_145]
pos = [
    603,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_146]
pos = [
    0,
    0,
]
size = [
    122,
    179,
]
frame_offset = [
    2,
    47,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_147]
pos = [
    1003,
    473,
]
size = [
    6,
    150,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_148]
pos = [
    1005,
    316,
]
size = [
    15,
    155,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_149]
pos = [
    804,
    364,
]
size = [
    65,
    155,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_150]
pos = [
    670,
    522,
]
size = [
    65,
    155,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_151]
pos = [
    1006,
    158,
]
size = [
    15,
    156,
]
frame_offset = [
    110,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_152]
pos = [
    536,
    840,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_153]
pos = [
    870,
    546,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_154]
pos = [
    736,
    704,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_155]
pos = [
    936,
    546,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_156]
pos = [
    536,
    684,
]
size = [
    65,
    154,
]
frame_offset = [
    1,
    72,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_157]
pos = [
    851,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_158]
pos = [
    670,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_159]
pos = [
    469,
    364,
]
size = [
    65,
    161,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_160]
pos = [
    536,
    526,
]
size = [
    65,
    156,
]
frame_offset = [
    1,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_161]
pos = [
    918,
    0,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_162]
pos = [
    802,
    704,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_163]
pos = [
    402,
    546,
]
size = [
    65,
    158,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_67]
pos = [
    603,
    364,
]
size = [
    65,
    158,
]
frame_offset = [
    60,
    68,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_68]
pos = [
    536,
    364,
]
size = [
    65,
    160,
]
frame_offset = [
    1,
    66,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_69]
pos = [
    737,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_70]
pos = [
    737,
    364,
]
size = [
    65,
    156,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_71]
pos = [
    134,
    727,
]
size = [
    65,
    161,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_72]
pos = [
    134,
    890,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_73]
pos = [
    201,
    888,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_74]
pos = [
    335,
    866,
]
size = [
    65,
    155,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_75]
pos = [
    804,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_76]
pos = [
    868,
    728,
]
size = [
    64,
    180,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_77]
pos = [
    469,
    527,
]
size = [
    65,
    157,
]
frame_offset = [
    60,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_78]
pos = [
    0,
    1012,
]
size = [
    1,
    1,
]
frame_offset = [
    1,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_79]
pos = [
    6,
    1009,
]
size = [
    1,
    1,
]
frame_offset = [
    124,
    152,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_80]
pos = [
    871,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_81]
pos = [
    938,
    182,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_82]
pos = [
    0,
    363,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_83]
pos = [
    67,
    363,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_84]
pos = [
    444,
    863,
]
size = [
    19,
    156,
]
frame_offset = [
    1,
    70,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_85]
pos = [
    501,
    843,
]
size = [
    13,
    155,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_86]
pos = [
    602,
    863,
]
size = [
    12,
    154,
]
frame_offset = [
    54,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_87]
pos = [
    402,
    863,
]
size = [
    19,
    157,
]
frame_offset = [
    106,
    69,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_88]
pos = [
    134,
    363,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_89]
pos = [
    0,
    545,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_90]
pos = [
    201,
    364,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_91]
pos = [
    67,
    545,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_92]
pos = [
    268,
    364,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_93]
pos = [
    134,
    545,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_94]
pos = [
    335,
    364,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_95]
pos = [
    0,
    727,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_96]
pos = [
    201,
    546,
]
size = [
    65,
    180,
]
frame_offset = [
    1,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_97]
pos = [
    402,
    364,
]
size = [
    65,
    180,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_98]
pos = [
    124,
    0,
]
size = [
    122,
    179,
]
frame_offset = [
    2,
    47,
]
frame_size = [
    128,
    256,
]

[walls_interior_detailing_bathroom_03_99]
pos = [
    616,
    863,
]
size = [
    6,
    150,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]
