[walls_exterior_roofs_30_16_41]
pos = [
    69,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_42]
pos = [
    483,
    296,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_43]
pos = [
    276,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_44]
pos = [
    276,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_45]
pos = [
    276,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_48]
pos = [
    340,
    756,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_49]
pos = [
    340,
    656,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_50]
pos = [
    68,
    852,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_51]
pos = [
    272,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_52]
pos = [
    0,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_53]
pos = [
    759,
    200,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_56]
pos = [
    476,
    696,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_57]
pos = [
    408,
    796,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_58]
pos = [
    755,
    624,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_59]
pos = [
    889,
    724,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_60]
pos = [
    880,
    824,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_61]
pos = [
    744,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_64]
pos = [
    879,
    960,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_65]
pos = [
    947,
    824,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_66]
pos = [
    813,
    824,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_67]
pos = [
    746,
    756,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_68]
pos = [
    611,
    764,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_69]
pos = [
    544,
    636,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_72]
pos = [
    69,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_73]
pos = [
    414,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_74]
pos = [
    414,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_75]
pos = [
    690,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_76]
pos = [
    690,
    132,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_77]
pos = [
    621,
    264,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_80]
pos = [
    612,
    532,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_81]
pos = [
    204,
    920,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_82]
pos = [
    408,
    628,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_83]
pos = [
    621,
    332,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_84]
pos = [
    340,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_85]
pos = [
    136,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_88]
pos = [
    828,
    100,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_89]
pos = [
    897,
    0,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_90]
pos = [
    552,
    296,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_91]
pos = [
    552,
    164,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_92]
pos = [
    552,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_16_93]
pos = [
    69,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_0]
pos = [
    544,
    532,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_1]
pos = [
    552,
    432,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_10]
pos = [
    272,
    888,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_11]
pos = [
    892,
    624,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_12]
pos = [
    610,
    928,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_13]
pos = [
    204,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_16]
pos = [
    407,
    960,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_17]
pos = [
    677,
    956,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_18]
pos = [
    678,
    856,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_19]
pos = [
    475,
    892,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_2]
pos = [
    0,
    884,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_20]
pos = [
    827,
    364,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_21]
pos = [
    340,
    824,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_24]
pos = [
    0,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_25]
pos = [
    207,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_26]
pos = [
    207,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_27]
pos = [
    207,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_28]
pos = [
    414,
    360,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_29]
pos = [
    0,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_3]
pos = [
    68,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_32]
pos = [
    68,
    984,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_33]
pos = [
    136,
    952,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_34]
pos = [
    136,
    852,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_35]
pos = [
    408,
    496,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_36]
pos = [
    204,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_37]
pos = [
    690,
    300,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_4]
pos = [
    896,
    296,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_40]
pos = [
    414,
    460,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_41]
pos = [
    138,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_42]
pos = [
    621,
    164,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_43]
pos = [
    483,
    164,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_44]
pos = [
    345,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_45]
pos = [
    345,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_48]
pos = [
    476,
    628,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_49]
pos = [
    204,
    820,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_5]
pos = [
    897,
    68,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_50]
pos = [
    272,
    656,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_51]
pos = [
    136,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_52]
pos = [
    68,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_53]
pos = [
    828,
    136,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_56]
pos = [
    612,
    568,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_57]
pos = [
    825,
    528,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_58]
pos = [
    894,
    492,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_59]
pos = [
    745,
    888,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_60]
pos = [
    812,
    924,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_61]
pos = [
    947,
    892,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_64]
pos = [
    947,
    928,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_65]
pos = [
    880,
    892,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_66]
pos = [
    956,
    724,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_67]
pos = [
    822,
    692,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_68]
pos = [
    543,
    832,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_69]
pos = [
    688,
    496,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_72]
pos = [
    138,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_73]
pos = [
    0,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_74]
pos = [
    483,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_75]
pos = [
    345,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_76]
pos = [
    828,
    0,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_77]
pos = [
    759,
    132,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_8]
pos = [
    758,
    428,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_80]
pos = [
    544,
    600,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_81]
pos = [
    408,
    728,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_82]
pos = [
    272,
    788,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_83]
pos = [
    476,
    496,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_84]
pos = [
    204,
    656,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_85]
pos = [
    0,
    688,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_88]
pos = [
    552,
    396,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_89]
pos = [
    690,
    232,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_9]
pos = [
    679,
    692,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_90]
pos = [
    483,
    396,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_91]
pos = [
    759,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_92]
pos = [
    621,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_17_93]
pos = [
    138,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_18_0]
pos = [
    620,
    464,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]
