[object_snow_overlay_01_156]
pos = [
    762,
    0,
]
size = [
    119,
    155,
]
frame_offset = [
    9,
    101,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_157]
pos = [
    113,
    870,
]
size = [
    108,
    145,
]
frame_offset = [
    6,
    111,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_158]
pos = [
    883,
    129,
]
size = [
    114,
    144,
]
frame_offset = [
    12,
    112,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_159]
pos = [
    511,
    259,
]
size = [
    117,
    147,
]
frame_offset = [
    0,
    104,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_160]
pos = [
    638,
    0,
]
size = [
    122,
    130,
]
frame_offset = [
    3,
    125,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_161]
pos = [
    387,
    258,
]
size = [
    122,
    214,
]
frame_offset = [
    3,
    41,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_162]
pos = [
    113,
    739,
]
size = [
    111,
    129,
]
frame_offset = [
    8,
    61,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_163]
pos = [
    350,
    479,
]
size = [
    111,
    130,
]
frame_offset = [
    9,
    60,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_164]
pos = [
    0,
    501,
]
size = [
    111,
    256,
]
frame_offset = [
    8,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_165]
pos = [
    124,
    481,
]
size = [
    111,
    256,
]
frame_offset = [
    9,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_166]
pos = [
    935,
    383,
]
size = [
    69,
    103,
]
frame_offset = [
    30,
    138,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_167]
pos = [
    935,
    275,
]
size = [
    69,
    106,
]
frame_offset = [
    30,
    135,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_168]
pos = [
    514,
    0,
]
size = [
    122,
    131,
]
frame_offset = [
    3,
    125,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_169]
pos = [
    390,
    0,
]
size = [
    122,
    132,
]
frame_offset = [
    3,
    124,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_170]
pos = [
    0,
    759,
]
size = [
    111,
    195,
]
frame_offset = [
    8,
    61,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_171]
pos = [
    237,
    481,
]
size = [
    111,
    196,
]
frame_offset = [
    9,
    60,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_172]
pos = [
    237,
    679,
]
size = [
    111,
    125,
]
frame_offset = [
    8,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_173]
pos = [
    638,
    132,
]
size = [
    119,
    125,
]
frame_offset = [
    9,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_174]
pos = [
    331,
    815,
]
size = [
    69,
    118,
]
frame_offset = [
    29,
    138,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_175]
pos = [
    818,
    494,
]
size = [
    68,
    256,
]
frame_offset = [
    30,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_176]
pos = [
    561,
    535,
]
size = [
    87,
    231,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_177]
pos = [
    744,
    430,
]
size = [
    72,
    232,
]
frame_offset = [
    56,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_178]
pos = [
    0,
    0,
]
size = [
    128,
    256,
]

[object_snow_overlay_01_179]
pos = [
    883,
    798,
]
size = [
    55,
    203,
]
frame_offset = [
    24,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_180]
pos = [
    462,
    616,
]
size = [
    95,
    79,
]
frame_offset = [
    4,
    163,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_181]
pos = [
    350,
    735,
]
size = [
    94,
    78,
]
frame_offset = [
    31,
    162,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_182]
pos = [
    748,
    354,
]
size = [
    86,
    74,
]
frame_offset = [
    18,
    154,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_183]
pos = [
    223,
    878,
]
size = [
    86,
    73,
]
frame_offset = [
    19,
    170,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_184]
pos = [
    630,
    259,
]
size = [
    116,
    124,
]
frame_offset = [
    6,
    131,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_185]
pos = [
    350,
    611,
]
size = [
    110,
    122,
]
frame_offset = [
    8,
    66,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_186]
pos = [
    511,
    408,
]
size = [
    110,
    125,
]
frame_offset = [
    8,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_187]
pos = [
    883,
    0,
]
size = [
    117,
    127,
]
frame_offset = [
    5,
    128,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_188]
pos = [
    630,
    385,
]
size = [
    112,
    122,
]
frame_offset = [
    5,
    64,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_189]
pos = [
    759,
    157,
]
size = [
    115,
    123,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_192]
pos = [
    260,
    130,
]
size = [
    128,
    126,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_193]
pos = [
    0,
    258,
]
size = [
    128,
    129,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_194]
pos = [
    130,
    193,
]
size = [
    128,
    127,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_195]
pos = [
    260,
    0,
]
size = [
    128,
    128,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_196]
pos = [
    390,
    134,
]
size = [
    114,
    80,
]
frame_offset = [
    8,
    170,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_197]
pos = [
    463,
    535,
]
size = [
    96,
    79,
]
frame_offset = [
    21,
    173,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_198]
pos = [
    226,
    806,
]
size = [
    103,
    70,
]
frame_offset = [
    13,
    176,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_199]
pos = [
    748,
    282,
]
size = [
    104,
    70,
]
frame_offset = [
    17,
    177,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_200]
pos = [
    842,
    890,
]
size = [
    24,
    106,
]
frame_offset = [
    51,
    100,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_201]
pos = [
    541,
    901,
]
size = [
    65,
    108,
]
frame_offset = [
    59,
    116,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_202]
pos = [
    888,
    688,
]
size = [
    65,
    108,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_203]
pos = [
    514,
    133,
]
size = [
    122,
    124,
]
frame_offset = [
    2,
    100,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_204]
pos = [
    472,
    908,
]
size = [
    67,
    111,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_205]
pos = [
    402,
    908,
]
size = [
    68,
    107,
]
frame_offset = [
    56,
    118,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_206]
pos = [
    0,
    389,
]
size = [
    122,
    110,
]
frame_offset = [
    2,
    117,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_207]
pos = [
    1002,
    0,
]
size = [
    17,
    83,
]
frame_offset = [
    55,
    117,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_208]
pos = [
    955,
    705,
]
size = [
    64,
    213,
]
frame_offset = [
    60,
    11,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_209]
pos = [
    888,
    494,
]
size = [
    67,
    192,
]
frame_offset = [
    59,
    33,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_210]
pos = [
    611,
    768,
]
size = [
    67,
    193,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_211]
pos = [
    957,
    488,
]
size = [
    65,
    215,
]
frame_offset = [
    2,
    11,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_212]
pos = [
    260,
    258,
]
size = [
    125,
    219,
]
frame_offset = [
    2,
    6,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_213]
pos = [
    650,
    509,
]
size = [
    71,
    221,
]
frame_offset = [
    4,
    6,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_216]
pos = [
    748,
    796,
]
size = [
    66,
    160,
]
frame_offset = [
    59,
    64,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_217]
pos = [
    541,
    768,
]
size = [
    68,
    131,
]
frame_offset = [
    59,
    94,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_218]
pos = [
    723,
    664,
]
size = [
    67,
    130,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_219]
pos = [
    816,
    752,
]
size = [
    65,
    136,
]
frame_offset = [
    2,
    90,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_220]
pos = [
    130,
    322,
]
size = [
    123,
    157,
]
frame_offset = [
    2,
    68,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_221]
pos = [
    816,
    890,
]
size = [
    24,
    115,
]
frame_offset = [
    51,
    90,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_224]
pos = [
    462,
    697,
]
size = [
    77,
    209,
]
frame_offset = [
    51,
    15,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_225]
pos = [
    130,
    0,
]
size = [
    128,
    191,
]
frame_offset = [
    0,
    33,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_226]
pos = [
    680,
    796,
]
size = [
    66,
    191,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[object_snow_overlay_01_227]
pos = [
    854,
    282,
]
size = [
    79,
    210,
]
frame_offset = [
    0,
    16,
]
frame_size = [
    128,
    256,
]
