[roofs_30_05_100]
pos = [
    130,
    512,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_101]
pos = [
    0,
    648,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_104]
pos = [
    260,
    838,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_105]
pos = [
    520,
    396,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    62,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_106]
pos = [
    650,
    297,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_107]
pos = [
    780,
    197,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_108]
pos = [
    650,
    365,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_109]
pos = [
    780,
    265,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    190,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_112]
pos = [
    520,
    598,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_113]
pos = [
    650,
    501,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_114]
pos = [
    390,
    763,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_115]
pos = [
    260,
    904,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_116]
pos = [
    520,
    664,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_117]
pos = [
    650,
    567,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_12]
pos = [
    130,
    216,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_13]
pos = [
    260,
    206,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_14]
pos = [
    910,
    0,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    231,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_16]
pos = [
    0,
    983,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_17]
pos = [
    260,
    970,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_18]
pos = [
    520,
    796,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_19]
pos = [
    780,
    570,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_20]
pos = [
    520,
    831,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_21]
pos = [
    780,
    605,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_24]
pos = [
    650,
    769,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_25]
pos = [
    520,
    901,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_26]
pos = [
    780,
    675,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_27]
pos = [
    650,
    839,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_28]
pos = [
    520,
    971,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_29]
pos = [
    390,
    829,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_32]
pos = [
    390,
    99,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_33]
pos = [
    390,
    198,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_34]
pos = [
    650,
    0,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_35]
pos = [
    520,
    198,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_36]
pos = [
    650,
    99,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_37]
pos = [
    0,
    414,
]
size = [
    128,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_40]
pos = [
    520,
    730,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_41]
pos = [
    650,
    433,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_42]
pos = [
    780,
    333,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_43]
pos = [
    780,
    401,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_44]
pos = [
    0,
    512,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_45]
pos = [
    0,
    580,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_48]
pos = [
    650,
    633,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_49]
pos = [
    780,
    745,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_50]
pos = [
    650,
    909,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_51]
pos = [
    780,
    780,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_52]
pos = [
    650,
    944,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_53]
pos = [
    780,
    815,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_56]
pos = [
    390,
    895,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_57]
pos = [
    130,
    579,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_58]
pos = [
    0,
    715,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_59]
pos = [
    260,
    503,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_60]
pos = [
    130,
    646,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_61]
pos = [
    0,
    782,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_64]
pos = [
    520,
    297,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_65]
pos = [
    0,
    0,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_66]
pos = [
    0,
    108,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_67]
pos = [
    130,
    0,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_68]
pos = [
    130,
    108,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_69]
pos = [
    260,
    0,
]
size = [
    128,
    105,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_70]
pos = [
    910,
    4,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_72]
pos = [
    260,
    570,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_73]
pos = [
    130,
    713,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_74]
pos = [
    0,
    849,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_75]
pos = [
    390,
    495,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_76]
pos = [
    260,
    637,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_77]
pos = [
    130,
    780,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_78]
pos = [
    916,
    0,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    231,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_80]
pos = [
    0,
    916,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_81]
pos = [
    390,
    562,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_82]
pos = [
    260,
    704,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_83]
pos = [
    130,
    847,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_84]
pos = [
    520,
    464,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_85]
pos = [
    390,
    629,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_88]
pos = [
    650,
    979,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_89]
pos = [
    780,
    850,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_90]
pos = [
    780,
    884,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_91]
pos = [
    780,
    918,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_92]
pos = [
    780,
    952,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_93]
pos = [
    780,
    986,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_96]
pos = [
    260,
    771,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_97]
pos = [
    130,
    914,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_98]
pos = [
    520,
    531,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_05_99]
pos = [
    390,
    696,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_0]
pos = [
    260,
    107,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_1]
pos = [
    260,
    404,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_10]
pos = [
    0,
    216,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_11]
pos = [
    0,
    315,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_12]
pos = [
    130,
    315,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_13]
pos = [
    260,
    305,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_14]
pos = [
    913,
    0,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    231,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_16]
pos = [
    130,
    981,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_17]
pos = [
    780,
    535,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_18]
pos = [
    650,
    699,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_19]
pos = [
    390,
    961,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_2]
pos = [
    390,
    0,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_20]
pos = [
    650,
    734,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_21]
pos = [
    520,
    866,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_24]
pos = [
    780,
    640,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_25]
pos = [
    650,
    804,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_26]
pos = [
    520,
    936,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_27]
pos = [
    780,
    710,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_28]
pos = [
    650,
    874,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_29]
pos = [
    780,
    469,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_3]
pos = [
    780,
    0,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_32]
pos = [
    520,
    0,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_33]
pos = [
    520,
    99,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_34]
pos = [
    390,
    297,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_4]
pos = [
    390,
    396,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_5]
pos = [
    130,
    414,
]
size = [
    128,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_8]
pos = [
    780,
    99,
]
size = [
    128,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_9]
pos = [
    650,
    198,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]
