[walls_interior_bathroom_01_26]
pos = [
    384,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_27]
pos = [
    512,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_28]
pos = [
    580,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_29]
pos = [
    648,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_30]
pos = [
    452,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_31]
pos = [
    716,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_32]
pos = [
    520,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_33]
pos = [
    784,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_34]
pos = [
    0,
    0,
]
size = [
    126,
    226,
]

[walls_interior_bathroom_01_35]
pos = [
    988,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_36]
pos = [
    588,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_37]
pos = [
    852,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_38]
pos = [
    128,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_39]
pos = [
    996,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_40]
pos = [
    656,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_41]
pos = [
    920,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_42]
pos = [
    724,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_43]
pos = [
    792,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_44]
pos = [
    860,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_45]
pos = [
    928,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_46]
pos = [
    0,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_47]
pos = [
    68,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_48]
pos = [
    136,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_49]
pos = [
    204,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_50]
pos = [
    256,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_51]
pos = [
    1004,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_52]
pos = [
    0,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_53]
pos = [
    272,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_54]
pos = [
    384,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_55]
pos = [
    1012,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_56]
pos = [
    68,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_57]
pos = [
    340,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_58]
pos = [
    136,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_59]
pos = [
    408,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_60]
pos = [
    204,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_61]
pos = [
    476,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_62]
pos = [
    272,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_63]
pos = [
    544,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_64]
pos = [
    340,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_65]
pos = [
    612,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_66]
pos = [
    0,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_67]
pos = [
    996,
    198,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_68]
pos = [
    408,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_69]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_70]
pos = [
    128,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_71]
pos = [
    1004,
    198,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_72]
pos = [
    476,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_73]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_74]
pos = [
    544,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_75]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_76]
pos = [
    612,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_77]
pos = [
    884,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_78]
pos = [
    680,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_79]
pos = [
    952,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_80]
pos = [
    748,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_81]
pos = [
    816,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_82]
pos = [
    256,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_83]
pos = [
    1012,
    198,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_84]
pos = [
    884,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_interior_bathroom_01_85]
pos = [
    952,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
