[roofs_30_06_100]
pos = [
    390,
    136,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_101]
pos = [
    520,
    68,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_104]
pos = [
    780,
    335,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_105]
pos = [
    0,
    414,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    62,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_106]
pos = [
    130,
    314,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_107]
pos = [
    260,
    206,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_108]
pos = [
    130,
    382,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_109]
pos = [
    260,
    274,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    190,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_112]
pos = [
    780,
    401,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_113]
pos = [
    0,
    482,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_114]
pos = [
    0,
    548,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_115]
pos = [
    130,
    450,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_116]
pos = [
    0,
    614,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_117]
pos = [
    130,
    516,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_35]
pos = [
    260,
    107,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_36]
pos = [
    0,
    216,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_37]
pos = [
    130,
    216,
]
size = [
    128,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_40]
pos = [
    0,
    680,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_41]
pos = [
    260,
    342,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_42]
pos = [
    260,
    410,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_43]
pos = [
    390,
    0,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_44]
pos = [
    390,
    68,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_45]
pos = [
    520,
    0,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_48]
pos = [
    130,
    582,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_49]
pos = [
    0,
    746,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_50]
pos = [
    130,
    648,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_51]
pos = [
    0,
    781,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_52]
pos = [
    260,
    544,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_53]
pos = [
    130,
    683,
]
size = [
    128,
    33,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_56]
pos = [
    260,
    478,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_57]
pos = [
    390,
    203,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_58]
pos = [
    650,
    0,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_59]
pos = [
    520,
    135,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_60]
pos = [
    390,
    270,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_61]
pos = [
    650,
    67,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_64]
pos = [
    0,
    315,
]
size = [
    128,
    97,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_65]
pos = [
    0,
    0,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_66]
pos = [
    0,
    108,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_67]
pos = [
    130,
    0,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_68]
pos = [
    130,
    108,
]
size = [
    128,
    106,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_69]
pos = [
    260,
    0,
]
size = [
    128,
    105,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_70]
pos = [
    910,
    0,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    71,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_72]
pos = [
    520,
    202,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_73]
pos = [
    390,
    337,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_74]
pos = [
    780,
    0,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_75]
pos = [
    650,
    134,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_76]
pos = [
    520,
    269,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_77]
pos = [
    390,
    404,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_78]
pos = [
    913,
    0,
]
size = [
    1,
    2,
]
frame_offset = [
    1,
    231,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_80]
pos = [
    780,
    67,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_81]
pos = [
    650,
    201,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_82]
pos = [
    520,
    336,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_83]
pos = [
    780,
    134,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_84]
pos = [
    650,
    268,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_85]
pos = [
    520,
    403,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_88]
pos = [
    0,
    816,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_89]
pos = [
    260,
    579,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_90]
pos = [
    130,
    718,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_91]
pos = [
    0,
    850,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_92]
pos = [
    390,
    471,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_93]
pos = [
    260,
    613,
]
size = [
    128,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_96]
pos = [
    780,
    201,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_97]
pos = [
    650,
    335,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_98]
pos = [
    780,
    268,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_30_06_99]
pos = [
    650,
    402,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_0]
pos = [
    130,
    752,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_1]
pos = [
    520,
    470,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_10]
pos = [
    0,
    884,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_11]
pos = [
    390,
    505,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_12]
pos = [
    260,
    647,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_13]
pos = [
    130,
    850,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_16]
pos = [
    0,
    982,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_17]
pos = [
    517,
    929,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_18]
pos = [
    647,
    799,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_19]
pos = [
    777,
    701,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_2]
pos = [
    390,
    603,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_20]
pos = [
    517,
    963,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_21]
pos = [
    647,
    833,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_24]
pos = [
    777,
    735,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_25]
pos = [
    647,
    867,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_26]
pos = [
    777,
    769,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_27]
pos = [
    647,
    901,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_28]
pos = [
    775,
    803,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_29]
pos = [
    645,
    935,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_3]
pos = [
    389,
    799,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_32]
pos = [
    260,
    745,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_33]
pos = [
    519,
    568,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_34]
pos = [
    389,
    701,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_35]
pos = [
    259,
    843,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_36]
pos = [
    650,
    469,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_37]
pos = [
    519,
    666,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_4]
pos = [
    648,
    568,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_40]
pos = [
    129,
    948,
]
size = [
    127,
    65,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_41]
pos = [
    259,
    941,
]
size = [
    127,
    65,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_42]
pos = [
    648,
    666,
]
size = [
    127,
    65,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_43]
pos = [
    777,
    567,
]
size = [
    127,
    65,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_44]
pos = [
    518,
    862,
]
size = [
    127,
    65,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_45]
pos = [
    648,
    733,
]
size = [
    127,
    64,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_48]
pos = [
    775,
    837,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_49]
pos = [
    645,
    969,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_5]
pos = [
    780,
    467,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_50]
pos = [
    775,
    871,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_51]
pos = [
    775,
    905,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_52]
pos = [
    773,
    939,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_53]
pos = [
    773,
    973,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_56]
pos = [
    777,
    634,
]
size = [
    126,
    65,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_8]
pos = [
    518,
    764,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_30_07_9]
pos = [
    388,
    897,
]
size = [
    127,
    96,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]
