[vegetation_gardening_unhealthy_01_100]
pos = [
    107,
    877,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_101]
pos = [
    325,
    687,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_104]
pos = [
    107,
    934,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_105]
pos = [
    541,
    502,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_106]
pos = [
    318,
    744,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_107]
pos = [
    214,
    862,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_108]
pos = [
    536,
    559,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_109]
pos = [
    318,
    801,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_112]
pos = [
    0,
    707,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_113]
pos = [
    220,
    467,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_114]
pos = [
    220,
    522,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_115]
pos = [
    0,
    762,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_116]
pos = [
    327,
    467,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_117]
pos = [
    220,
    577,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_120]
pos = [
    0,
    817,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_121]
pos = [
    107,
    712,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_122]
pos = [
    327,
    522,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_123]
pos = [
    218,
    632,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_124]
pos = [
    0,
    872,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_125]
pos = [
    107,
    767,
]
size = [
    105,
    53,
]
frame_offset = [
    9,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_128]
pos = [
    209,
    919,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_129]
pos = [
    643,
    477,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_130]
pos = [
    536,
    616,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_131]
pos = [
    427,
    724,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_132]
pos = [
    318,
    858,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_133]
pos = [
    643,
    534,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_136]
pos = [
    420,
    781,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_137]
pos = [
    536,
    673,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_138]
pos = [
    745,
    477,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_139]
pos = [
    311,
    919,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_140]
pos = [
    638,
    591,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_141]
pos = [
    420,
    838,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_144]
pos = [
    327,
    577,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_145]
pos = [
    218,
    687,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_146]
pos = [
    0,
    927,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_147]
pos = [
    107,
    822,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_148]
pos = [
    434,
    502,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_149]
pos = [
    325,
    632,
]
size = [
    105,
    53,
]
frame_offset = [
    10,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_152]
pos = [
    843,
    425,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_153]
pos = [
    420,
    895,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_154]
pos = [
    522,
    787,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_155]
pos = [
    847,
    476,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_156]
pos = [
    740,
    591,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_157]
pos = [
    638,
    705,
]
size = [
    96,
    49,
]
frame_offset = [
    11,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_97]
pos = [
    529,
    730,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_98]
pos = [
    745,
    534,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_gardening_unhealthy_01_99]
pos = [
    638,
    648,
]
size = [
    100,
    55,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_0]
pos = [
    434,
    445,
]
size = [
    24,
    31,
]
frame_offset = [
    49,
    133,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_1]
pos = [
    331,
    976,
]
size = [
    37,
    42,
]
frame_offset = [
    47,
    113,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_10]
pos = [
    921,
    822,
]
size = [
    67,
    143,
]
frame_offset = [
    27,
    90,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_11]
pos = [
    386,
    0,
]
size = [
    122,
    190,
]
frame_offset = [
    5,
    42,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_12]
pos = [
    522,
    838,
]
size = [
    91,
    123,
]
frame_offset = [
    21,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_16]
pos = [
    0,
    458,
]
size = [
    108,
    123,
]
frame_offset = [
    10,
    130,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_17]
pos = [
    921,
    647,
]
size = [
    87,
    173,
]
frame_offset = [
    25,
    83,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_18]
pos = [
    110,
    583,
]
size = [
    106,
    127,
]
frame_offset = [
    8,
    106,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_19]
pos = [
    629,
    0,
]
size = [
    113,
    168,
]
frame_offset = [
    5,
    64,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_2]
pos = [
    370,
    976,
]
size = [
    30,
    41,
]
frame_offset = [
    7,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_20]
pos = [
    847,
    527,
]
size = [
    91,
    118,
]
frame_offset = [
    21,
    112,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_21]
pos = [
    687,
    894,
]
size = [
    66,
    112,
]
frame_offset = [
    35,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_24]
pos = [
    110,
    458,
]
size = [
    108,
    123,
]
frame_offset = [
    10,
    130,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_25]
pos = [
    832,
    647,
]
size = [
    87,
    234,
]
frame_offset = [
    25,
    0,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_26]
pos = [
    631,
    756,
]
size = [
    89,
    127,
]
frame_offset = [
    21,
    106,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_27]
pos = [
    384,
    279,
]
size = [
    122,
    164,
]
frame_offset = [
    5,
    68,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_28]
pos = [
    740,
    642,
]
size = [
    90,
    111,
]
frame_offset = [
    21,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_29]
pos = [
    945,
    425,
]
size = [
    73,
    104,
]
frame_offset = [
    27,
    130,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_3]
pos = [
    492,
    946,
]
size = [
    24,
    57,
]
frame_offset = [
    8,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_32]
pos = [
    0,
    583,
]
size = [
    108,
    122,
]
frame_offset = [
    10,
    131,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_33]
pos = [
    966,
    0,
]
size = [
    53,
    82,
]
frame_offset = [
    40,
    152,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_34]
pos = [
    965,
    197,
]
size = [
    51,
    68,
]
frame_offset = [
    43,
    165,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_35]
pos = [
    722,
    756,
]
size = [
    88,
    136,
]
frame_offset = [
    39,
    96,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_36]
pos = [
    615,
    885,
]
size = [
    70,
    97,
]
frame_offset = [
    42,
    133,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_37]
pos = [
    413,
    946,
]
size = [
    47,
    58,
]
frame_offset = [
    41,
    174,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_4]
pos = [
    209,
    976,
]
size = [
    59,
    43,
]
frame_offset = [
    20,
    117,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_5]
pos = [
    270,
    976,
]
size = [
    59,
    43,
]
frame_offset = [
    47,
    117,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_6]
pos = [
    462,
    946,
]
size = [
    28,
    49,
]
frame_offset = [
    10,
    114,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_7]
pos = [
    954,
    300,
]
size = [
    67,
    115,
]
frame_offset = [
    33,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_8]
pos = [
    623,
    346,
]
size = [
    108,
    127,
]
frame_offset = [
    10,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_indoor_01_9]
pos = [
    512,
    169,
]
size = [
    109,
    205,
]
frame_offset = [
    15,
    29,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_0]
pos = [
    734,
    176,
]
size = [
    108,
    173,
]
frame_offset = [
    5,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_1]
pos = [
    623,
    170,
]
size = [
    109,
    174,
]
frame_offset = [
    13,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_10]
pos = [
    744,
    0,
]
size = [
    109,
    174,
]
frame_offset = [
    13,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_11]
pos = [
    855,
    126,
]
size = [
    108,
    172,
]
frame_offset = [
    5,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_12]
pos = [
    855,
    0,
]
size = [
    109,
    124,
]
frame_offset = [
    13,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_13]
pos = [
    844,
    300,
]
size = [
    108,
    123,
]
frame_offset = [
    5,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_16]
pos = [
    0,
    180,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_17]
pos = [
    258,
    0,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_18]
pos = [
    128,
    180,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_19]
pos = [
    0,
    320,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_2]
pos = [
    510,
    0,
]
size = [
    117,
    167,
]
frame_offset = [
    5,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_20]
pos = [
    128,
    250,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_21]
pos = [
    0,
    389,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_22]
pos = [
    128,
    319,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_23]
pos = [
    129,
    90,
]
size = [
    126,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_28]
pos = [
    0,
    0,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_29]
pos = [
    0,
    90,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_3]
pos = [
    434,
    557,
]
size = [
    100,
    165,
]
frame_offset = [
    13,
    85,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_30]
pos = [
    129,
    0,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_32]
pos = [
    258,
    70,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_33]
pos = [
    257,
    140,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_34]
pos = [
    0,
    250,
]
size = [
    126,
    68,
]
frame_offset = [
    0,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_35]
pos = [
    256,
    210,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_36]
pos = [
    128,
    388,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_37]
pos = [
    256,
    279,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_38]
pos = [
    384,
    210,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_4]
pos = [
    733,
    351,
]
size = [
    108,
    124,
]
frame_offset = [
    5,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_5]
pos = [
    508,
    376,
]
size = [
    109,
    124,
]
frame_offset = [
    13,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_6]
pos = [
    256,
    348,
]
size = [
    117,
    117,
]
frame_offset = [
    5,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_7]
pos = [
    214,
    742,
]
size = [
    102,
    118,
]
frame_offset = [
    11,
    134,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_8]
pos = [
    966,
    84,
]
size = [
    52,
    111,
]
frame_offset = [
    38,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_9]
pos = [
    940,
    531,
]
size = [
    72,
    79,
]
frame_offset = [
    28,
    160,
]
frame_size = [
    128,
    256,
]
