[roofs_burnt_30_01_100]
pos = [
    649,
    781,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    62,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_101]
pos = [
    779,
    647,
]
size = [
    126,
    97,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_104]
pos = [
    390,
    316,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_105]
pos = [
    650,
    71,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_106]
pos = [
    520,
    222,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_107]
pos = [
    390,
    384,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_108]
pos = [
    780,
    0,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_109]
pos = [
    780,
    272,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_112]
pos = [
    0,
    515,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_113]
pos = [
    0,
    581,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_114]
pos = [
    130,
    512,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_115]
pos = [
    0,
    647,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_116]
pos = [
    130,
    578,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_117]
pos = [
    0,
    713,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_75]
pos = [
    650,
    411,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_76]
pos = [
    780,
    339,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_77]
pos = [
    260,
    507,
]
size = [
    128,
    64,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_80]
pos = [
    780,
    406,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    191,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_81]
pos = [
    780,
    136,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    159,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_82]
pos = [
    650,
    275,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_83]
pos = [
    520,
    426,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    95,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_84]
pos = [
    780,
    204,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_85]
pos = [
    0,
    448,
]
size = [
    128,
    65,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_88]
pos = [
    518,
    972,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_89]
pos = [
    646,
    987,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_90]
pos = [
    776,
    883,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_91]
pos = [
    776,
    917,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_92]
pos = [
    776,
    951,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_93]
pos = [
    774,
    987,
]
size = [
    126,
    32,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_96]
pos = [
    648,
    919,
]
size = [
    126,
    66,
]
frame_offset = [
    0,
    190,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_97]
pos = [
    648,
    850,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    158,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_98]
pos = [
    777,
    815,
]
size = [
    126,
    66,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_burnt_30_01_99]
pos = [
    778,
    746,
]
size = [
    126,
    67,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_0]
pos = [
    390,
    748,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_1]
pos = [
    0,
    0,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_10]
pos = [
    130,
    973,
]
size = [
    128,
    40,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_11]
pos = [
    390,
    618,
]
size = [
    128,
    42,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_12]
pos = [
    130,
    269,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_13]
pos = [
    520,
    624,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_14]
pos = [
    907,
    647,
]
size = [
    115,
    57,
]
frame_offset = [
    13,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_15]
pos = [
    650,
    139,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_16]
pos = [
    650,
    520,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_17]
pos = [
    0,
    270,
]
size = [
    128,
    87,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_18]
pos = [
    130,
    644,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_19]
pos = [
    260,
    789,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_2]
pos = [
    390,
    515,
]
size = [
    128,
    56,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_20]
pos = [
    130,
    441,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_21]
pos = [
    260,
    266,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_22]
pos = [
    390,
    85,
]
size = [
    128,
    78,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_23]
pos = [
    520,
    80,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_24]
pos = [
    260,
    917,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_25]
pos = [
    0,
    90,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_26]
pos = [
    130,
    770,
]
size = [
    128,
    56,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_27]
pos = [
    390,
    662,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_28]
pos = [
    260,
    699,
]
size = [
    128,
    43,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_29]
pos = [
    0,
    779,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_3]
pos = [
    520,
    538,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_30]
pos = [
    130,
    0,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_31]
pos = [
    390,
    835,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_32]
pos = [
    909,
    473,
]
size = [
    113,
    59,
]
frame_offset = [
    2,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_33]
pos = [
    520,
    290,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_34]
pos = [
    650,
    478,
]
size = [
    128,
    40,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_35]
pos = [
    520,
    494,
]
size = [
    128,
    42,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_36]
pos = [
    260,
    180,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_37]
pos = [
    520,
    711,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_38]
pos = [
    907,
    706,
]
size = [
    115,
    57,
]
frame_offset = [
    13,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_39]
pos = [
    780,
    68,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_4]
pos = [
    390,
    573,
]
size = [
    128,
    43,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_40]
pos = [
    780,
    473,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_41]
pos = [
    130,
    180,
]
size = [
    128,
    87,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_42]
pos = [
    260,
    573,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_43]
pos = [
    130,
    930,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_44]
pos = [
    390,
    245,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_45]
pos = [
    260,
    351,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_46]
pos = [
    520,
    0,
]
size = [
    128,
    78,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_47]
pos = [
    650,
    0,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_48]
pos = [
    650,
    607,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_49]
pos = [
    130,
    90,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_5]
pos = [
    390,
    452,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_50]
pos = [
    0,
    905,
]
size = [
    128,
    56,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_51]
pos = [
    260,
    832,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_52]
pos = [
    0,
    963,
]
size = [
    128,
    43,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_53]
pos = [
    130,
    707,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_54]
pos = [
    260,
    0,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_55]
pos = [
    389,
    922,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_56]
pos = [
    909,
    534,
]
size = [
    113,
    59,
]
frame_offset = [
    2,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_57]
pos = [
    650,
    207,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_58]
pos = [
    260,
    875,
]
size = [
    128,
    40,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_59]
pos = [
    130,
    886,
]
size = [
    128,
    42,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_6]
pos = [
    260,
    90,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_60]
pos = [
    130,
    355,
]
size = [
    128,
    84,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_61]
pos = [
    519,
    798,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_62]
pos = [
    906,
    765,
]
size = [
    115,
    57,
]
frame_offset = [
    13,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_63]
pos = [
    520,
    358,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_64]
pos = [
    779,
    560,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_65]
pos = [
    0,
    359,
]
size = [
    128,
    87,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_66]
pos = [
    0,
    842,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_67]
pos = [
    390,
    705,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_68]
pos = [
    520,
    151,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_69]
pos = [
    390,
    0,
]
size = [
    128,
    83,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_7]
pos = [
    519,
    885,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_70]
pos = [
    390,
    165,
]
size = [
    128,
    78,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_71]
pos = [
    260,
    436,
]
size = [
    128,
    69,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_72]
pos = [
    649,
    694,
]
size = [
    127,
    85,
]
frame_offset = [
    0,
    142,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_73]
pos = [
    0,
    180,
]
size = [
    128,
    88,
]
frame_offset = [
    0,
    123,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_74]
pos = [
    130,
    828,
]
size = [
    128,
    56,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_75]
pos = [
    520,
    581,
]
size = [
    128,
    41,
]
frame_offset = [
    0,
    170,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_76]
pos = [
    260,
    744,
]
size = [
    128,
    43,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_77]
pos = [
    260,
    636,
]
size = [
    128,
    61,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_8]
pos = [
    905,
    824,
]
size = [
    113,
    59,
]
frame_offset = [
    2,
    168,
]
frame_size = [
    128,
    256,
]

[roofs_shallow_01_9]
pos = [
    650,
    343,
]
size = [
    128,
    66,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]
