[walls_exterior_roofs_30_10_10]
pos = [
    204,
    888,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_11]
pos = [
    542,
    896,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_12]
pos = [
    609,
    956,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_13]
pos = [
    136,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_16]
pos = [
    676,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_17]
pos = [
    818,
    856,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_18]
pos = [
    677,
    888,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_19]
pos = [
    543,
    764,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_20]
pos = [
    340,
    796,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_21]
pos = [
    689,
    396,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_24]
pos = [
    0,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_25]
pos = [
    207,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_26]
pos = [
    138,
    228,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_27]
pos = [
    552,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_28]
pos = [
    138,
    392,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_29]
pos = [
    0,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_32]
pos = [
    0,
    984,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_33]
pos = [
    551,
    464,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_34]
pos = [
    272,
    656,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_35]
pos = [
    0,
    852,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_36]
pos = [
    136,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_37]
pos = [
    828,
    68,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_40]
pos = [
    345,
    460,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_41]
pos = [
    483,
    296,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_42]
pos = [
    345,
    360,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_43]
pos = [
    621,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_44]
pos = [
    276,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_45]
pos = [
    345,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_48]
pos = [
    272,
    756,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_49]
pos = [
    340,
    628,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_50]
pos = [
    414,
    460,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_51]
pos = [
    68,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_52]
pos = [
    896,
    196,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_53]
pos = [
    690,
    168,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_56]
pos = [
    272,
    824,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_57]
pos = [
    756,
    524,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_58]
pos = [
    753,
    688,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_59]
pos = [
    820,
    756,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_60]
pos = [
    885,
    856,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_61]
pos = [
    952,
    856,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_64]
pos = [
    945,
    928,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_65]
pos = [
    954,
    788,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_66]
pos = [
    957,
    688,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_67]
pos = [
    892,
    556,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_68]
pos = [
    895,
    392,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_69]
pos = [
    476,
    636,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_72]
pos = [
    138,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_73]
pos = [
    0,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_74]
pos = [
    414,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_75]
pos = [
    483,
    164,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_76]
pos = [
    759,
    0,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_77]
pos = [
    552,
    264,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_8]
pos = [
    619,
    496,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_80]
pos = [
    476,
    600,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_81]
pos = [
    340,
    728,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_82]
pos = [
    408,
    592,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_83]
pos = [
    552,
    332,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_84]
pos = [
    136,
    656,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_85]
pos = [
    68,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_88]
pos = [
    621,
    232,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_89]
pos = [
    828,
    0,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_9]
pos = [
    475,
    832,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_90]
pos = [
    414,
    360,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_91]
pos = [
    552,
    132,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_92]
pos = [
    483,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_10_93]
pos = [
    69,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_0]
pos = [
    482,
    532,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_1]
pos = [
    68,
    852,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_10]
pos = [
    407,
    888,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_11]
pos = [
    610,
    856,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_12]
pos = [
    744,
    920,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_13]
pos = [
    339,
    960,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_16]
pos = [
    743,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_17]
pos = [
    887,
    788,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_18]
pos = [
    751,
    820,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_19]
pos = [
    684,
    756,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_2]
pos = [
    340,
    496,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_20]
pos = [
    686,
    592,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_21]
pos = [
    758,
    328,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_24]
pos = [
    69,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_25]
pos = [
    276,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_26]
pos = [
    207,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_27]
pos = [
    207,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_28]
pos = [
    690,
    0,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_29]
pos = [
    69,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_3]
pos = [
    204,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_32]
pos = [
    550,
    532,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_33]
pos = [
    68,
    952,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_34]
pos = [
    136,
    820,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_35]
pos = [
    204,
    656,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_36]
pos = [
    0,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_37]
pos = [
    897,
    0,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_4]
pos = [
    827,
    264,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_40]
pos = [
    483,
    364,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_41]
pos = [
    690,
    100,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_42]
pos = [
    621,
    132,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_43]
pos = [
    276,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_44]
pos = [
    345,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_45]
pos = [
    414,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_48]
pos = [
    136,
    920,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_49]
pos = [
    204,
    788,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_5]
pos = [
    621,
    268,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_50]
pos = [
    483,
    400,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_51]
pos = [
    272,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_52]
pos = [
    0,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_53]
pos = [
    759,
    100,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_56]
pos = [
    408,
    692,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_57]
pos = [
    825,
    460,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_58]
pos = [
    823,
    624,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_59]
pos = [
    890,
    688,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_60]
pos = [
    811,
    924,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_61]
pos = [
    952,
    892,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_64]
pos = [
    945,
    964,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_65]
pos = [
    878,
    924,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_8]
pos = [
    550,
    568,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_9]
pos = [
    617,
    692,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]
