[location_community_church_small_01_147]
pos = [
    0,
    774,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_148]
pos = [
    640,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_149]
pos = [
    907,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_150]
pos = [
    392,
    485,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_151]
pos = [
    460,
    485,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_152]
pos = [
    708,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_153]
pos = [
    528,
    484,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_154]
pos = [
    196,
    774,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_155]
pos = [
    776,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_156]
pos = [
    264,
    774,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_157]
pos = [
    844,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_158]
pos = [
    392,
    713,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_159]
pos = [
    596,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_160]
pos = [
    664,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_161]
pos = [
    912,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_162]
pos = [
    460,
    713,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_163]
pos = [
    732,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_164]
pos = [
    528,
    712,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_165]
pos = [
    800,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_166]
pos = [
    596,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_167]
pos = [
    868,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_168]
pos = [
    256,
    516,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_169]
pos = [
    324,
    516,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_170]
pos = [
    664,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_171]
pos = [
    128,
    743,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_172]
pos = [
    936,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_173]
pos = [
    732,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_174]
pos = [
    800,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_175]
pos = [
    868,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_176]
pos = [
    779,
    0,
]
size = [
    126,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_177]
pos = [
    0,
    258,
]
size = [
    126,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_178]
pos = [
    0,
    0,
]
size = [
    128,
    256,
]

[location_community_church_small_01_179]
pos = [
    130,
    0,
]
size = [
    128,
    256,
]

[location_community_church_small_01_180]
pos = [
    512,
    258,
]
size = [
    126,
    224,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_181]
pos = [
    384,
    258,
]
size = [
    126,
    225,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_184]
pos = [
    260,
    0,
]
size = [
    128,
    256,
]

[location_community_church_small_01_185]
pos = [
    390,
    0,
]
size = [
    128,
    256,
]

[location_community_church_small_01_186]
pos = [
    650,
    0,
]
size = [
    127,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_187]
pos = [
    128,
    258,
]
size = [
    126,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_188]
pos = [
    520,
    0,
]
size = [
    128,
    256,
]

[location_community_church_small_01_189]
pos = [
    128,
    516,
]
size = [
    126,
    225,
]
frame_offset = [
    0,
    31,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_192]
pos = [
    256,
    258,
]
size = [
    126,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_community_church_small_01_193]
pos = [
    0,
    516,
]
size = [
    126,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]
