[signs_one-off_07_100]
pos = [
    600,
    733,
]
size = [
    64,
    58,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_101]
pos = [
    0,
    956,
]
size = [
    64,
    65,
]
frame_offset = [
    60,
    121,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_102]
pos = [
    198,
    978,
]
size = [
    35,
    39,
]
frame_offset = [
    60,
    123,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_104]
pos = [
    920,
    767,
]
size = [
    54,
    135,
]
frame_offset = [
    12,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_105]
pos = [
    838,
    173,
]
size = [
    64,
    163,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_106]
pos = [
    904,
    169,
]
size = [
    64,
    162,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_107]
pos = [
    731,
    844,
]
size = [
    60,
    146,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_108]
pos = [
    943,
    671,
]
size = [
    57,
    94,
]
frame_offset = [
    9,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_109]
pos = [
    132,
    923,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_110]
pos = [
    66,
    920,
]
size = [
    64,
    102,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_111]
pos = [
    402,
    716,
]
size = [
    64,
    93,
]
frame_offset = [
    2,
    100,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_112]
pos = [
    796,
    757,
]
size = [
    60,
    164,
]
frame_offset = [
    6,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_113]
pos = [
    706,
    0,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_114]
pos = [
    473,
    297,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_115]
pos = [
    772,
    0,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_116]
pos = [
    573,
    75,
]
size = [
    64,
    175,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_117]
pos = [
    815,
    572,
]
size = [
    63,
    165,
]
frame_offset = [
    2,
    41,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_118]
pos = [
    330,
    933,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    102,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_119]
pos = [
    301,
    359,
]
size = [
    33,
    67,
]
frame_offset = [
    2,
    119,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_120]
pos = [
    0,
    298,
]
size = [
    76,
    138,
]
frame_offset = [
    0,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_121]
pos = [
    0,
    816,
]
size = [
    64,
    138,
]
frame_offset = [
    12,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_122]
pos = [
    66,
    780,
]
size = [
    64,
    138,
]
frame_offset = [
    12,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_123]
pos = [
    353,
    454,
]
size = [
    64,
    138,
]
frame_offset = [
    12,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_124]
pos = [
    270,
    595,
]
size = [
    64,
    138,
]
frame_offset = [
    12,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_125]
pos = [
    132,
    783,
]
size = [
    64,
    138,
]
frame_offset = [
    12,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_126]
pos = [
    232,
    304,
]
size = [
    67,
    134,
]
frame_offset = [
    12,
    97,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_128]
pos = [
    858,
    891,
]
size = [
    41,
    130,
]
frame_offset = [
    31,
    9,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_129]
pos = [
    706,
    176,
]
size = [
    64,
    168,
]
frame_offset = [
    8,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_130]
pos = [
    970,
    80,
]
size = [
    47,
    133,
]
frame_offset = [
    8,
    41,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_131]
pos = [
    901,
    904,
]
size = [
    27,
    75,
]
frame_offset = [
    39,
    40,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_132]
pos = [
    617,
    483,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_133]
pos = [
    468,
    798,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    48,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_134]
pos = [
    833,
    923,
]
size = [
    23,
    61,
]
frame_offset = [
    2,
    74,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_135]
pos = [
    593,
    949,
]
size = [
    29,
    45,
]
frame_offset = [
    95,
    174,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_136]
pos = [
    232,
    255,
]
size = [
    22,
    33,
]
frame_offset = [
    42,
    188,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_137]
pos = [
    396,
    965,
]
size = [
    64,
    56,
]
frame_offset = [
    0,
    163,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_138]
pos = [
    749,
    598,
]
size = [
    64,
    58,
]
frame_offset = [
    0,
    163,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_139]
pos = [
    534,
    829,
]
size = [
    64,
    52,
]
frame_offset = [
    0,
    164,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_140]
pos = [
    462,
    884,
]
size = [
    64,
    58,
]
frame_offset = [
    0,
    164,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_141]
pos = [
    348,
    145,
]
size = [
    69,
    57,
]
frame_offset = [
    0,
    164,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_142]
pos = [
    264,
    951,
]
size = [
    64,
    70,
]
frame_offset = [
    60,
    150,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_143]
pos = [
    301,
    304,
]
size = [
    34,
    53,
]
frame_offset = [
    60,
    150,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_144]
pos = [
    72,
    477,
]
size = [
    64,
    159,
]
frame_offset = [
    2,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_145]
pos = [
    772,
    344,
]
size = [
    64,
    162,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_146]
pos = [
    267,
    0,
]
size = [
    79,
    170,
]
frame_offset = [
    2,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_147]
pos = [
    624,
    949,
]
size = [
    24,
    51,
]
frame_offset = [
    42,
    107,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_148]
pos = [
    396,
    811,
]
size = [
    64,
    86,
]
frame_offset = [
    2,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_149]
pos = [
    683,
    511,
]
size = [
    64,
    86,
]
frame_offset = [
    2,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_150]
pos = [
    534,
    745,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    100,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_151]
pos = [
    488,
    145,
]
size = [
    14,
    57,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_152]
pos = [
    1011,
    436,
]
size = [
    11,
    139,
]
frame_offset = [
    55,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_153]
pos = [
    639,
    178,
]
size = [
    64,
    171,
]
frame_offset = [
    2,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_154]
pos = [
    904,
    0,
]
size = [
    64,
    167,
]
frame_offset = [
    2,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_155]
pos = [
    838,
    338,
]
size = [
    64,
    162,
]
frame_offset = [
    2,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_156]
pos = [
    705,
    346,
]
size = [
    64,
    163,
]
frame_offset = [
    2,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_157]
pos = [
    572,
    252,
]
size = [
    64,
    171,
]
frame_offset = [
    2,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_158]
pos = [
    838,
    0,
]
size = [
    64,
    171,
]
frame_offset = [
    2,
    37,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_159]
pos = [
    904,
    333,
]
size = [
    64,
    161,
]
frame_offset = [
    2,
    47,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_160]
pos = [
    665,
    911,
]
size = [
    60,
    94,
]
frame_offset = [
    64,
    44,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_29]
pos = [
    731,
    757,
]
size = [
    63,
    85,
]
frame_offset = [
    61,
    108,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_30]
pos = [
    264,
    861,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_31]
pos = [
    970,
    0,
]
size = [
    50,
    78,
]
frame_offset = [
    2,
    81,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_32]
pos = [
    152,
    399,
]
size = [
    67,
    84,
]
frame_offset = [
    9,
    145,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_33]
pos = [
    749,
    658,
]
size = [
    63,
    97,
]
frame_offset = [
    12,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_34]
pos = [
    946,
    496,
]
size = [
    63,
    86,
]
frame_offset = [
    11,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_35]
pos = [
    506,
    0,
]
size = [
    65,
    113,
]
frame_offset = [
    10,
    119,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_36]
pos = [
    749,
    511,
]
size = [
    64,
    85,
]
frame_offset = [
    11,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_37]
pos = [
    946,
    584,
]
size = [
    63,
    85,
]
frame_offset = [
    11,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_38]
pos = [
    528,
    884,
]
size = [
    63,
    95,
]
frame_offset = [
    10,
    136,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_39]
pos = [
    970,
    364,
]
size = [
    46,
    70,
]
frame_offset = [
    9,
    161,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_40]
pos = [
    419,
    145,
]
size = [
    67,
    150,
]
frame_offset = [
    9,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_41]
pos = [
    666,
    680,
]
size = [
    63,
    229,
]
frame_offset = [
    12,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_42]
pos = [
    600,
    793,
]
size = [
    63,
    154,
]
frame_offset = [
    11,
    8,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_43]
pos = [
    406,
    297,
]
size = [
    65,
    155,
]
frame_offset = [
    10,
    7,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_44]
pos = [
    138,
    485,
]
size = [
    64,
    155,
]
frame_offset = [
    11,
    7,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_45]
pos = [
    337,
    204,
]
size = [
    67,
    227,
]
frame_offset = [
    11,
    7,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_46]
pos = [
    881,
    502,
]
size = [
    63,
    156,
]
frame_offset = [
    10,
    7,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_47]
pos = [
    970,
    215,
]
size = [
    46,
    147,
]
frame_offset = [
    9,
    16,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_48]
pos = [
    793,
    923,
]
size = [
    38,
    75,
]
frame_offset = [
    86,
    146,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_49]
pos = [
    551,
    554,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_50]
pos = [
    198,
    872,
]
size = [
    64,
    104,
]
frame_offset = [
    60,
    117,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_51]
pos = [
    468,
    606,
]
size = [
    64,
    100,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_52]
pos = [
    402,
    606,
]
size = [
    64,
    108,
]
frame_offset = [
    60,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_53]
pos = [
    462,
    944,
]
size = [
    43,
    78,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_54]
pos = [
    78,
    385,
]
size = [
    72,
    90,
]
frame_offset = [
    52,
    64,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_55]
pos = [
    91,
    0,
]
size = [
    88,
    127,
]
frame_offset = [
    2,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_56]
pos = [
    0,
    0,
]
size = [
    89,
    151,
]
frame_offset = [
    8,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_57]
pos = [
    0,
    153,
]
size = [
    76,
    143,
]
frame_offset = [
    22,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_58]
pos = [
    348,
    0,
]
size = [
    77,
    143,
]
frame_offset = [
    22,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_59]
pos = [
    181,
    111,
]
size = [
    78,
    142,
]
frame_offset = [
    21,
    102,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_60]
pos = [
    155,
    255,
]
size = [
    75,
    142,
]
frame_offset = [
    22,
    102,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_61]
pos = [
    427,
    0,
]
size = [
    77,
    143,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_62]
pos = [
    78,
    240,
]
size = [
    75,
    143,
]
frame_offset = [
    22,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_63]
pos = [
    261,
    172,
]
size = [
    74,
    130,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_64]
pos = [
    287,
    440,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_65]
pos = [
    0,
    673,
]
size = [
    64,
    141,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_66]
pos = [
    336,
    594,
]
size = [
    64,
    138,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_67]
pos = [
    198,
    736,
]
size = [
    64,
    134,
]
frame_offset = [
    60,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_68]
pos = [
    132,
    642,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_69]
pos = [
    204,
    595,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_70]
pos = [
    330,
    735,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_71]
pos = [
    683,
    599,
]
size = [
    64,
    79,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_72]
pos = [
    858,
    746,
]
size = [
    60,
    143,
]
frame_offset = [
    6,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_73]
pos = [
    221,
    440,
]
size = [
    64,
    153,
]
frame_offset = [
    2,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_74]
pos = [
    66,
    638,
]
size = [
    64,
    140,
]
frame_offset = [
    2,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_75]
pos = [
    419,
    473,
]
size = [
    64,
    131,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_76]
pos = [
    638,
    351,
]
size = [
    64,
    130,
]
frame_offset = [
    2,
    67,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_77]
pos = [
    485,
    473,
]
size = [
    64,
    131,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_78]
pos = [
    264,
    736,
]
size = [
    64,
    123,
]
frame_offset = [
    2,
    71,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_79]
pos = [
    551,
    425,
]
size = [
    64,
    127,
]
frame_offset = [
    2,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_80]
pos = [
    330,
    843,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_81]
pos = [
    468,
    708,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_82]
pos = [
    617,
    577,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_83]
pos = [
    534,
    655,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_84]
pos = [
    880,
    660,
]
size = [
    61,
    84,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_85]
pos = [
    91,
    129,
]
size = [
    84,
    109,
]
frame_offset = [
    20,
    137,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_86]
pos = [
    181,
    0,
]
size = [
    84,
    109,
]
frame_offset = [
    21,
    137,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_88]
pos = [
    573,
    0,
]
size = [
    65,
    73,
]
frame_offset = [
    1,
    131,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_89]
pos = [
    0,
    438,
]
size = [
    70,
    71,
]
frame_offset = [
    2,
    133,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_90]
pos = [
    976,
    767,
]
size = [
    41,
    161,
]
frame_offset = [
    83,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_91]
pos = [
    506,
    115,
]
size = [
    64,
    176,
]
frame_offset = [
    60,
    42,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_92]
pos = [
    640,
    0,
]
size = [
    64,
    176,
]
frame_offset = [
    60,
    42,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_93]
pos = [
    772,
    176,
]
size = [
    64,
    166,
]
frame_offset = [
    60,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_94]
pos = [
    0,
    511,
]
size = [
    64,
    160,
]
frame_offset = [
    60,
    43,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_95]
pos = [
    539,
    293,
]
size = [
    30,
    111,
]
frame_offset = [
    60,
    59,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_96]
pos = [
    970,
    436,
]
size = [
    35,
    39,
]
frame_offset = [
    89,
    147,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_97]
pos = [
    815,
    508,
]
size = [
    64,
    62,
]
frame_offset = [
    60,
    123,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_98]
pos = [
    600,
    667,
]
size = [
    64,
    64,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_99]
pos = [
    396,
    899,
]
size = [
    64,
    64,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]
