[walls_exterior_house_02_24]
pos = [
    256,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_25]
pos = [
    324,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_26]
pos = [
    392,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_27]
pos = [
    512,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_28]
pos = [
    580,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_29]
pos = [
    648,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_30]
pos = [
    460,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_31]
pos = [
    716,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_32]
pos = [
    528,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_33]
pos = [
    784,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_34]
pos = [
    0,
    0,
]
size = [
    126,
    226,
]

[walls_exterior_house_02_35]
pos = [
    988,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_36]
pos = [
    596,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_37]
pos = [
    852,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_38]
pos = [
    128,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_39]
pos = [
    996,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_40]
pos = [
    664,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_41]
pos = [
    920,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_42]
pos = [
    732,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_43]
pos = [
    800,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_44]
pos = [
    868,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_45]
pos = [
    936,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_46]
pos = [
    0,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_47]
pos = [
    68,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_48]
pos = [
    136,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_49]
pos = [
    204,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_50]
pos = [
    256,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_51]
pos = [
    1004,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_52]
pos = [
    0,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_53]
pos = [
    272,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_54]
pos = [
    384,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_55]
pos = [
    884,
    684,
]
size = [
    64,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_56]
pos = [
    68,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_57]
pos = [
    340,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_58]
pos = [
    136,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_59]
pos = [
    408,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_60]
pos = [
    204,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_61]
pos = [
    476,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_62]
pos = [
    272,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_63]
pos = [
    544,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_64]
pos = [
    340,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_65]
pos = [
    612,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_66]
pos = [
    0,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_67]
pos = [
    950,
    684,
]
size = [
    64,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_68]
pos = [
    408,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_69]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_70]
pos = [
    128,
    228,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_71]
pos = [
    1012,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_72]
pos = [
    476,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_73]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_74]
pos = [
    544,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_75]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_76]
pos = [
    612,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_77]
pos = [
    884,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_78]
pos = [
    680,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_79]
pos = [
    952,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_80]
pos = [
    748,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_02_81]
pos = [
    816,
    684,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
