[fencing_damaged_05_175]
pos = [
    0,
    474,
]
size = [
    73,
    184,
]
frame_offset = [
    4,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_176]
pos = [
    0,
    438,
]
size = [
    76,
    34,
]
frame_offset = [
    36,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_177]
pos = [
    358,
    866,
]
size = [
    52,
    46,
]
frame_offset = [
    52,
    210,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_178]
pos = [
    333,
    0,
]
size = [
    86,
    46,
]
frame_offset = [
    40,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_179]
pos = [
    123,
    55,
]
size = [
    106,
    55,
]
frame_offset = [
    0,
    201,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_180]
pos = [
    393,
    384,
]
size = [
    71,
    50,
]
frame_offset = [
    0,
    198,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_181]
pos = [
    149,
    870,
]
size = [
    62,
    18,
]
frame_offset = [
    64,
    219,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_184]
pos = [
    333,
    77,
]
size = [
    78,
    186,
]
frame_offset = [
    47,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_185]
pos = [
    604,
    632,
]
size = [
    65,
    199,
]
frame_offset = [
    61,
    33,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_186]
pos = [
    421,
    0,
]
size = [
    80,
    197,
]
frame_offset = [
    48,
    21,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_187]
pos = [
    737,
    823,
]
size = [
    61,
    199,
]
frame_offset = [
    64,
    33,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_188]
pos = [
    0,
    253,
]
size = [
    80,
    183,
]
frame_offset = [
    47,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_189]
pos = [
    291,
    844,
]
size = [
    65,
    169,
]
frame_offset = [
    63,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_190]
pos = [
    231,
    55,
]
size = [
    10,
    17,
]
frame_offset = [
    0,
    60,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_191]
pos = [
    243,
    0,
]
size = [
    88,
    208,
]
frame_offset = [
    36,
    23,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_192]
pos = [
    413,
    199,
]
size = [
    75,
    183,
]
frame_offset = [
    48,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_193]
pos = [
    810,
    386,
]
size = [
    65,
    201,
]
frame_offset = [
    59,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_194]
pos = [
    732,
    0,
]
size = [
    74,
    196,
]
frame_offset = [
    48,
    17,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_195]
pos = [
    465,
    605,
]
size = [
    67,
    209,
]
frame_offset = [
    58,
    21,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_200]
pos = [
    140,
    984,
]
size = [
    48,
    36,
]
frame_offset = [
    78,
    207,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_201]
pos = [
    82,
    253,
]
size = [
    79,
    33,
]
frame_offset = [
    24,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_202]
pos = [
    123,
    112,
]
size = [
    98,
    55,
]
frame_offset = [
    28,
    201,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_203]
pos = [
    333,
    48,
]
size = [
    81,
    27,
]
frame_offset = [
    0,
    215,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_204]
pos = [
    140,
    890,
]
size = [
    59,
    50,
]
frame_offset = [
    18,
    206,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_205]
pos = [
    0,
    197,
]
size = [
    106,
    54,
]
frame_offset = [
    0,
    193,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_208]
pos = [
    808,
    0,
]
size = [
    74,
    193,
]
frame_offset = [
    0,
    39,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_209]
pos = [
    537,
    411,
]
size = [
    68,
    160,
]
frame_offset = [
    10,
    52,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_210]
pos = [
    935,
    820,
]
size = [
    61,
    190,
]
frame_offset = [
    10,
    42,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_211]
pos = [
    0,
    0,
]
size = [
    121,
    195,
]
frame_offset = [
    7,
    31,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_212]
pos = [
    884,
    194,
]
size = [
    73,
    185,
]
frame_offset = [
    0,
    47,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_213]
pos = [
    222,
    660,
]
size = [
    69,
    136,
]
frame_offset = [
    9,
    78,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_214]
pos = [
    600,
    833,
]
size = [
    62,
    161,
]
frame_offset = [
    11,
    71,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_215]
pos = [
    293,
    660,
]
size = [
    68,
    182,
]
frame_offset = [
    9,
    31,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_220]
pos = [
    877,
    386,
]
size = [
    65,
    184,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_221]
pos = [
    72,
    884,
]
size = [
    66,
    135,
]
frame_offset = [
    1,
    81,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_222]
pos = [
    432,
    631,
]
size = [
    20,
    89,
]
frame_offset = [
    50,
    123,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_223]
pos = [
    579,
    213,
]
size = [
    74,
    196,
]
frame_offset = [
    3,
    31,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_224]
pos = [
    108,
    218,
]
size = [
    83,
    30,
]
frame_offset = [
    22,
    226,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_225]
pos = [
    140,
    942,
]
size = [
    57,
    40,
]
frame_offset = [
    69,
    204,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_226]
pos = [
    271,
    210,
]
size = [
    60,
    29,
]
frame_offset = [
    34,
    193,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_227]
pos = [
    193,
    218,
]
size = [
    76,
    42,
]
frame_offset = [
    0,
    197,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_228]
pos = [
    123,
    0,
]
size = [
    118,
    53,
]
frame_offset = [
    0,
    203,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_05_229]
pos = [
    123,
    169,
]
size = [
    94,
    47,
]
frame_offset = [
    32,
    192,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_0]
pos = [
    503,
    181,
]
size = [
    74,
    197,
]
frame_offset = [
    48,
    16,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_1]
pos = [
    809,
    804,
]
size = [
    61,
    215,
]
frame_offset = [
    58,
    16,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_10]
pos = [
    808,
    195,
]
size = [
    73,
    189,
]
frame_offset = [
    49,
    25,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_11]
pos = [
    959,
    0,
]
size = [
    63,
    195,
]
frame_offset = [
    58,
    36,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_12]
pos = [
    239,
    262,
]
size = [
    75,
    191,
]
frame_offset = [
    49,
    23,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_13]
pos = [
    743,
    391,
]
size = [
    65,
    214,
]
frame_offset = [
    60,
    16,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_16]
pos = [
    75,
    689,
]
size = [
    72,
    193,
]
frame_offset = [
    6,
    20,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_17]
pos = [
    537,
    573,
]
size = [
    65,
    218,
]
frame_offset = [
    5,
    14,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_18]
pos = [
    239,
    455,
]
size = [
    72,
    203,
]
frame_offset = [
    6,
    9,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_19]
pos = [
    676,
    415,
]
size = [
    65,
    230,
]
frame_offset = [
    5,
    2,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_2]
pos = [
    656,
    0,
]
size = [
    74,
    204,
]
frame_offset = [
    49,
    8,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_20]
pos = [
    656,
    206,
]
size = [
    73,
    207,
]
frame_offset = [
    5,
    6,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_21]
pos = [
    222,
    798,
]
size = [
    67,
    218,
]
frame_offset = [
    2,
    13,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_24]
pos = [
    162,
    288,
]
size = [
    75,
    196,
]
frame_offset = [
    3,
    18,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_25]
pos = [
    743,
    607,
]
size = [
    64,
    214,
]
frame_offset = [
    3,
    17,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_26]
pos = [
    316,
    265,
]
size = [
    75,
    188,
]
frame_offset = [
    3,
    27,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_27]
pos = [
    872,
    804,
]
size = [
    61,
    196,
]
frame_offset = [
    6,
    35,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_28]
pos = [
    732,
    198,
]
size = [
    73,
    191,
]
frame_offset = [
    5,
    22,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_29]
pos = [
    363,
    649,
]
size = [
    67,
    215,
]
frame_offset = [
    2,
    15,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_3]
pos = [
    877,
    572,
]
size = [
    62,
    226,
]
frame_offset = [
    59,
    5,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_4]
pos = [
    0,
    807,
]
size = [
    70,
    207,
]
frame_offset = [
    49,
    4,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_40]
pos = [
    607,
    415,
]
size = [
    67,
    215,
]
frame_offset = [
    2,
    16,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_41]
pos = [
    75,
    504,
]
size = [
    73,
    183,
]
frame_offset = [
    5,
    30,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_42]
pos = [
    959,
    197,
]
size = [
    62,
    179,
]
frame_offset = [
    7,
    53,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_43]
pos = [
    0,
    660,
]
size = [
    73,
    145,
]
frame_offset = [
    5,
    70,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_44]
pos = [
    534,
    793,
]
size = [
    64,
    217,
]
frame_offset = [
    8,
    14,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_45]
pos = [
    393,
    436,
]
size = [
    70,
    193,
]
frame_offset = [
    8,
    19,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_48]
pos = [
    884,
    0,
]
size = [
    73,
    192,
]
frame_offset = [
    48,
    19,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_49]
pos = [
    944,
    381,
]
size = [
    64,
    217,
]
frame_offset = [
    57,
    14,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_5]
pos = [
    150,
    651,
]
size = [
    70,
    217,
]
frame_offset = [
    55,
    13,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_50]
pos = [
    162,
    486,
]
size = [
    73,
    163,
]
frame_offset = [
    50,
    52,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_51]
pos = [
    432,
    816,
]
size = [
    65,
    168,
]
frame_offset = [
    59,
    63,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_52]
pos = [
    503,
    0,
]
size = [
    75,
    179,
]
frame_offset = [
    50,
    35,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_53]
pos = [
    810,
    589,
]
size = [
    64,
    213,
]
frame_offset = [
    61,
    16,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_56]
pos = [
    466,
    384,
]
size = [
    69,
    219,
]
frame_offset = [
    1,
    12,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_57]
pos = [
    580,
    0,
]
size = [
    74,
    211,
]
frame_offset = [
    6,
    2,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_58]
pos = [
    671,
    647,
]
size = [
    64,
    227,
]
frame_offset = [
    0,
    5,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_59]
pos = [
    82,
    288,
]
size = [
    78,
    214,
]
frame_offset = [
    0,
    1,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_8]
pos = [
    313,
    455,
]
size = [
    72,
    192,
]
frame_offset = [
    49,
    20,
]
frame_size = [
    128,
    256,
]

[fencing_damaged_06_9]
pos = [
    941,
    600,
]
size = [
    61,
    218,
]
frame_offset = [
    57,
    13,
]
frame_size = [
    128,
    256,
]
