[walls_exterior_house_08_106]
pos = [
    0,
    0,
]
size = [
    66,
    256,
]

[walls_exterior_house_08_107]
pos = [
    68,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_108]
pos = [
    68,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_109]
pos = [
    136,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_110]
pos = [
    680,
    888,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_111]
pos = [
    748,
    887,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_112]
pos = [
    204,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_113]
pos = [
    272,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_114]
pos = [
    340,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_115]
pos = [
    408,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_116]
pos = [
    680,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_117]
pos = [
    748,
    684,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_118]
pos = [
    884,
    684,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_119]
pos = [
    476,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_120]
pos = [
    748,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_121]
pos = [
    544,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_122]
pos = [
    816,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_123]
pos = [
    612,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_124]
pos = [
    884,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_125]
pos = [
    680,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_126]
pos = [
    952,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_08_127]
pos = [
    748,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_0]
pos = [
    0,
    258,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_1]
pos = [
    204,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_10]
pos = [
    136,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_11]
pos = [
    204,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_12]
pos = [
    816,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_13]
pos = [
    884,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_14]
pos = [
    816,
    887,
]
size = [
    66,
    41,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_15]
pos = [
    884,
    886,
]
size = [
    66,
    41,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_16]
pos = [
    952,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_17]
pos = [
    0,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_18]
pos = [
    68,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_19]
pos = [
    136,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_2]
pos = [
    272,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_20]
pos = [
    0,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_21]
pos = [
    816,
    684,
]
size = [
    66,
    201,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_22]
pos = [
    952,
    660,
]
size = [
    66,
    200,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_23]
pos = [
    272,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_24]
pos = [
    68,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_25]
pos = [
    340,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_26]
pos = [
    136,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_27]
pos = [
    408,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_28]
pos = [
    204,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_29]
pos = [
    476,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_3]
pos = [
    816,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_30]
pos = [
    544,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_31]
pos = [
    340,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_32]
pos = [
    612,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_33]
pos = [
    408,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_34]
pos = [
    680,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_35]
pos = [
    476,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_36]
pos = [
    272,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_37]
pos = [
    748,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_38]
pos = [
    680,
    684,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_39]
pos = [
    544,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_4]
pos = [
    476,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_40]
pos = [
    340,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_41]
pos = [
    408,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_5]
pos = [
    612,
    714,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_6]
pos = [
    952,
    456,
]
size = [
    66,
    202,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_7]
pos = [
    884,
    456,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_8]
pos = [
    544,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_house_09_9]
pos = [
    612,
    0,
]
size = [
    66,
    256,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
