[vegetation_farming_unhealthy_01b_10]
pos = [
    107,
    771,
]
size = [
    105,
    64,
]
frame_offset = [
    14,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_11]
pos = [
    0,
    711,
]
size = [
    105,
    143,
]
frame_offset = [
    14,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_12]
pos = [
    0,
    856,
]
size = [
    105,
    111,
]
frame_offset = [
    14,
    139,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_13]
pos = [
    214,
    496,
]
size = [
    105,
    139,
]
frame_offset = [
    14,
    111,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_14]
pos = [
    107,
    630,
]
size = [
    105,
    139,
]
frame_offset = [
    14,
    111,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_15]
pos = [
    344,
    442,
]
size = [
    105,
    131,
]
frame_offset = [
    14,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_16]
pos = [
    738,
    676,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_17]
pos = [
    840,
    586,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_18]
pos = [
    738,
    602,
]
size = [
    100,
    72,
]
frame_offset = [
    14,
    177,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_19]
pos = [
    661,
    497,
]
size = [
    101,
    103,
]
frame_offset = [
    13,
    146,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_20]
pos = [
    732,
    0,
]
size = [
    111,
    134,
]
frame_offset = [
    6,
    115,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_21]
pos = [
    0,
    175,
]
size = [
    117,
    152,
]
frame_offset = [
    1,
    97,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_22]
pos = [
    119,
    199,
]
size = [
    117,
    151,
]
frame_offset = [
    1,
    98,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_23]
pos = [
    357,
    310,
]
size = [
    114,
    130,
]
frame_offset = [
    4,
    119,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_24]
pos = [
    630,
    825,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_25]
pos = [
    214,
    878,
]
size = [
    102,
    61,
]
frame_offset = [
    12,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_26]
pos = [
    423,
    875,
]
size = [
    100,
    79,
]
frame_offset = [
    14,
    171,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_27]
pos = [
    532,
    711,
]
size = [
    101,
    102,
]
frame_offset = [
    14,
    148,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_28]
pos = [
    425,
    717,
]
size = [
    101,
    156,
]
frame_offset = [
    13,
    94,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_29]
pos = [
    320,
    803,
]
size = [
    101,
    219,
]
frame_offset = [
    13,
    31,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_30]
pos = [
    835,
    297,
]
size = [
    101,
    220,
]
frame_offset = [
    14,
    30,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_31]
pos = [
    533,
    591,
]
size = [
    101,
    118,
]
frame_offset = [
    13,
    132,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_32]
pos = [
    321,
    632,
]
size = [
    105,
    53,
]
frame_offset = [
    13,
    196,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_33]
pos = [
    321,
    575,
]
size = [
    105,
    55,
]
frame_offset = [
    13,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_34]
pos = [
    696,
    402,
]
size = [
    106,
    93,
]
frame_offset = [
    13,
    156,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_35]
pos = [
    473,
    315,
]
size = [
    111,
    113,
]
frame_offset = [
    11,
    136,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_36]
pos = [
    379,
    0,
]
size = [
    121,
    179,
]
frame_offset = [
    7,
    70,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_37]
pos = [
    253,
    0,
]
size = [
    124,
    196,
]
frame_offset = [
    3,
    53,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_38]
pos = [
    127,
    0,
]
size = [
    124,
    197,
]
frame_offset = [
    4,
    52,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_39]
pos = [
    0,
    0,
]
size = [
    125,
    173,
]
frame_offset = [
    0,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_40]
pos = [
    525,
    946,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_41]
pos = [
    107,
    963,
]
size = [
    100,
    58,
]
frame_offset = [
    14,
    191,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_42]
pos = [
    738,
    733,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_43]
pos = [
    423,
    956,
]
size = [
    100,
    62,
]
frame_offset = [
    14,
    187,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_44]
pos = [
    213,
    941,
]
size = [
    101,
    66,
]
frame_offset = [
    13,
    183,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_45]
pos = [
    428,
    646,
]
size = [
    102,
    69,
]
frame_offset = [
    12,
    183,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_46]
pos = [
    428,
    575,
]
size = [
    103,
    69,
]
frame_offset = [
    11,
    183,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_47]
pos = [
    764,
    519,
]
size = [
    100,
    65,
]
frame_offset = [
    14,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_48]
pos = [
    840,
    643,
]
size = [
    100,
    55,
]
frame_offset = [
    16,
    194,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_49]
pos = [
    866,
    519,
]
size = [
    100,
    61,
]
frame_offset = [
    16,
    188,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_50]
pos = [
    557,
    502,
]
size = [
    102,
    87,
]
frame_offset = [
    14,
    162,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_51]
pos = [
    321,
    687,
]
size = [
    102,
    114,
]
frame_offset = [
    14,
    135,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_52]
pos = [
    841,
    152,
]
size = [
    106,
    143,
]
frame_offset = [
    11,
    106,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_53]
pos = [
    107,
    469,
]
size = [
    105,
    159,
]
frame_offset = [
    11,
    90,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_54]
pos = [
    845,
    0,
]
size = [
    109,
    150,
]
frame_offset = [
    12,
    99,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_55]
pos = [
    730,
    136,
]
size = [
    109,
    142,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_56]
pos = [
    840,
    773,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_57]
pos = [
    729,
    908,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_58]
pos = [
    840,
    700,
]
size = [
    97,
    71,
]
frame_offset = [
    19,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_59]
pos = [
    238,
    329,
]
size = [
    115,
    92,
]
frame_offset = [
    5,
    163,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_6]
pos = [
    502,
    140,
]
size = [
    112,
    173,
]
frame_offset = [
    8,
    77,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_60]
pos = [
    357,
    198,
]
size = [
    115,
    110,
]
frame_offset = [
    6,
    145,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_61]
pos = [
    119,
    352,
]
size = [
    115,
    115,
]
frame_offset = [
    6,
    140,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_62]
pos = [
    616,
    262,
]
size = [
    109,
    114,
]
frame_offset = [
    12,
    141,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_63]
pos = [
    586,
    378,
]
size = [
    108,
    103,
]
frame_offset = [
    12,
    152,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_64]
pos = [
    627,
    883,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_65]
pos = [
    635,
    762,
]
size = [
    100,
    61,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_66]
pos = [
    528,
    815,
]
size = [
    100,
    66,
]
frame_offset = [
    14,
    184,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_67]
pos = [
    636,
    602,
]
size = [
    100,
    82,
]
frame_offset = [
    14,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_68]
pos = [
    214,
    757,
]
size = [
    104,
    119,
]
frame_offset = [
    10,
    131,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_69]
pos = [
    0,
    329,
]
size = [
    117,
    128,
]
frame_offset = [
    3,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_7]
pos = [
    617,
    126,
]
size = [
    111,
    134,
]
frame_offset = [
    8,
    116,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_70]
pos = [
    238,
    199,
]
size = [
    117,
    128,
]
frame_offset = [
    3,
    122,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_71]
pos = [
    617,
    0,
]
size = [
    113,
    124,
]
frame_offset = [
    7,
    126,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_72]
pos = [
    839,
    833,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_73]
pos = [
    831,
    893,
]
size = [
    97,
    58,
]
frame_offset = [
    19,
    198,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_74]
pos = [
    732,
    847,
]
size = [
    97,
    59,
]
frame_offset = [
    19,
    197,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_75]
pos = [
    627,
    940,
]
size = [
    97,
    63,
]
frame_offset = [
    19,
    193,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_76]
pos = [
    107,
    894,
]
size = [
    104,
    67,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_77]
pos = [
    451,
    502,
]
size = [
    104,
    70,
]
frame_offset = [
    12,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_78]
pos = [
    473,
    430,
]
size = [
    106,
    70,
]
frame_offset = [
    10,
    186,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_79]
pos = [
    236,
    423,
]
size = [
    106,
    71,
]
frame_offset = [
    10,
    185,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_8]
pos = [
    0,
    459,
]
size = [
    105,
    250,
]
frame_offset = [
    14,
    0,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_80]
pos = [
    737,
    790,
]
size = [
    100,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_81]
pos = [
    525,
    883,
]
size = [
    100,
    61,
]
frame_offset = [
    14,
    189,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_82]
pos = [
    636,
    686,
]
size = [
    100,
    74,
]
frame_offset = [
    14,
    182,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_83]
pos = [
    214,
    637,
]
size = [
    105,
    118,
]
frame_offset = [
    14,
    138,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_84]
pos = [
    727,
    280,
]
size = [
    106,
    120,
]
frame_offset = [
    13,
    136,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_85]
pos = [
    502,
    0,
]
size = [
    113,
    138,
]
frame_offset = [
    12,
    118,
]
frame_size = [
    128,
    256,
]

[vegetation_farming_unhealthy_01b_9]
pos = [
    107,
    837,
]
size = [
    105,
    55,
]
frame_offset = [
    14,
    195,
]
frame_size = [
    128,
    256,
]
