[location_restaurant_bar_01_10]
pos = [
    512,
    146,
]
size = [
    118,
    135,
]
frame_offset = [
    8,
    118,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_11]
pos = [
    323,
    870,
]
size = [
    73,
    137,
]
frame_offset = [
    54,
    117,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_12]
pos = [
    384,
    295,
]
size = [
    121,
    157,
]
frame_offset = [
    3,
    94,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_13]
pos = [
    258,
    0,
]
size = [
    126,
    158,
]
frame_offset = [
    0,
    94,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_14]
pos = [
    128,
    228,
]
size = [
    125,
    157,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_15]
pos = [
    255,
    307,
]
size = [
    122,
    156,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_16]
pos = [
    0,
    291,
]
size = [
    126,
    143,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_17]
pos = [
    0,
    0,
]
size = [
    128,
    143,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_18]
pos = [
    741,
    145,
]
size = [
    104,
    155,
]
frame_offset = [
    0,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_19]
pos = [
    106,
    487,
]
size = [
    103,
    143,
]
frame_offset = [
    1,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_20]
pos = [
    258,
    160,
]
size = [
    124,
    145,
]
frame_offset = [
    0,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_21]
pos = [
    754,
    0,
]
size = [
    106,
    143,
]
frame_offset = [
    18,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_22]
pos = [
    512,
    283,
]
size = [
    105,
    154,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_23]
pos = [
    0,
    436,
]
size = [
    104,
    143,
]
frame_offset = [
    22,
    112,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_25]
pos = [
    639,
    881,
]
size = [
    50,
    84,
]
frame_offset = [
    40,
    155,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_26]
pos = [
    969,
    0,
]
size = [
    45,
    78,
]
frame_offset = [
    42,
    157,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_29]
pos = [
    408,
    454,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_30]
pos = [
    507,
    439,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_31]
pos = [
    292,
    668,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_32]
pos = [
    470,
    959,
]
size = [
    44,
    43,
]
frame_offset = [
    31,
    92,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_33]
pos = [
    516,
    959,
]
size = [
    44,
    43,
]
frame_offset = [
    51,
    92,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_34]
pos = [
    969,
    80,
]
size = [
    44,
    60,
]
frame_offset = [
    53,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_35]
pos = [
    198,
    938,
]
size = [
    44,
    60,
]
frame_offset = [
    29,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_37]
pos = [
    0,
    726,
]
size = [
    91,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_38]
pos = [
    106,
    632,
]
size = [
    91,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_39]
pos = [
    693,
    450,
]
size = [
    89,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_4]
pos = [
    386,
    148,
]
size = [
    124,
    145,
]
frame_offset = [
    0,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_40]
pos = [
    953,
    214,
]
size = [
    60,
    57,
]
frame_offset = [
    64,
    67,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_41]
pos = [
    66,
    937,
]
size = [
    64,
    59,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_42]
pos = [
    132,
    938,
]
size = [
    64,
    58,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_43]
pos = [
    0,
    929,
]
size = [
    64,
    60,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_44]
pos = [
    662,
    653,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_45]
pos = [
    927,
    459,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_46]
pos = [
    130,
    0,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_47]
pos = [
    995,
    451,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_5]
pos = [
    633,
    136,
]
size = [
    106,
    143,
]
frame_offset = [
    18,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_51]
pos = [
    953,
    156,
]
size = [
    61,
    56,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_52]
pos = [
    730,
    659,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_53]
pos = [
    798,
    661,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_54]
pos = [
    866,
    687,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_55]
pos = [
    934,
    687,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_56]
pos = [
    0,
    145,
]
size = [
    126,
    144,
]
frame_offset = [
    1,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_57]
pos = [
    512,
    0,
]
size = [
    119,
    144,
]
frame_offset = [
    1,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_58]
pos = [
    619,
    283,
]
size = [
    104,
    155,
]
frame_offset = [
    1,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_59]
pos = [
    725,
    302,
]
size = [
    104,
    146,
]
frame_offset = [
    1,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_6]
pos = [
    862,
    0,
]
size = [
    105,
    154,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_60]
pos = [
    386,
    0,
]
size = [
    124,
    146,
]
frame_offset = [
    1,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_61]
pos = [
    211,
    487,
]
size = [
    102,
    144,
]
frame_offset = [
    23,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_62]
pos = [
    847,
    156,
]
size = [
    104,
    155,
]
frame_offset = [
    23,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_63]
pos = [
    831,
    313,
]
size = [
    104,
    144,
]
frame_offset = [
    23,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_64]
pos = [
    385,
    668,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_65]
pos = [
    600,
    440,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_66]
pos = [
    478,
    656,
]
size = [
    91,
    200,
]
frame_offset = [
    33,
    38,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_68]
pos = [
    784,
    459,
]
size = [
    71,
    198,
]
frame_offset = [
    53,
    21,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_69]
pos = [
    857,
    459,
]
size = [
    68,
    200,
]
frame_offset = [
    60,
    19,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_7]
pos = [
    0,
    581,
]
size = [
    104,
    143,
]
frame_offset = [
    22,
    112,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_70]
pos = [
    106,
    436,
]
size = [
    2,
    4,
]
frame_offset = [
    0,
    90,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_72]
pos = [
    315,
    465,
]
size = [
    91,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_73]
pos = [
    199,
    633,
]
size = [
    91,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_74]
pos = [
    571,
    642,
]
size = [
    89,
    201,
]
frame_offset = [
    2,
    36,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_76]
pos = [
    93,
    835,
]
size = [
    75,
    100,
]
frame_offset = [
    1,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_77]
pos = [
    170,
    836,
]
size = [
    75,
    100,
]
frame_offset = [
    50,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_78]
pos = [
    128,
    387,
]
size = [
    124,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_79]
pos = [
    93,
    726,
]
size = [
    6,
    67,
]
frame_offset = [
    60,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_8]
pos = [
    937,
    313,
]
size = [
    73,
    136,
]
frame_offset = [
    0,
    119,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_83]
pos = [
    546,
    858,
]
size = [
    5,
    93,
]
frame_offset = [
    123,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_84]
pos = [
    398,
    870,
]
size = [
    70,
    129,
]
frame_offset = [
    0,
    98,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_85]
pos = [
    247,
    870,
]
size = [
    74,
    129,
]
frame_offset = [
    54,
    98,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_86]
pos = [
    501,
    454,
]
size = [
    4,
    87,
]
frame_offset = [
    0,
    131,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_88]
pos = [
    478,
    858,
]
size = [
    66,
    99,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_89]
pos = [
    571,
    845,
]
size = [
    66,
    163,
]
frame_offset = [
    0,
    63,
]
frame_size = [
    128,
    256,
]

[location_restaurant_bar_01_9]
pos = [
    633,
    0,
]
size = [
    119,
    134,
]
frame_offset = [
    0,
    120,
]
frame_size = [
    128,
    256,
]
