[walls_exterior_roofs_30_11_66]
pos = [
    957,
    688,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_67]
pos = [
    823,
    656,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_68]
pos = [
    611,
    692,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_69]
pos = [
    689,
    428,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_72]
pos = [
    138,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_73]
pos = [
    414,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_74]
pos = [
    345,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_75]
pos = [
    483,
    164,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_76]
pos = [
    759,
    0,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_77]
pos = [
    138,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_80]
pos = [
    204,
    888,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_81]
pos = [
    136,
    920,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_82]
pos = [
    204,
    788,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_83]
pos = [
    483,
    432,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_84]
pos = [
    272,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_85]
pos = [
    0,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_88]
pos = [
    414,
    460,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_89]
pos = [
    552,
    296,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_90]
pos = [
    483,
    296,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_91]
pos = [
    345,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_92]
pos = [
    483,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_11_93]
pos = [
    69,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_0]
pos = [
    68,
    952,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_1]
pos = [
    68,
    852,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_10]
pos = [
    895,
    424,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_11]
pos = [
    204,
    924,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_12]
pos = [
    407,
    928,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_13]
pos = [
    136,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_16]
pos = [
    609,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_17]
pos = [
    887,
    820,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_18]
pos = [
    677,
    920,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_19]
pos = [
    610,
    856,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_2]
pos = [
    340,
    492,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_20]
pos = [
    272,
    856,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_21]
pos = [
    544,
    564,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_24]
pos = [
    0,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_25]
pos = [
    276,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_26]
pos = [
    207,
    228,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_27]
pos = [
    621,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_28]
pos = [
    207,
    392,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_29]
pos = [
    0,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_3]
pos = [
    0,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_32]
pos = [
    0,
    984,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_33]
pos = [
    476,
    564,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_34]
pos = [
    136,
    820,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_35]
pos = [
    204,
    656,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_36]
pos = [
    136,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_37]
pos = [
    621,
    300,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_4]
pos = [
    690,
    232,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_40]
pos = [
    759,
    100,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_41]
pos = [
    69,
    424,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_42]
pos = [
    621,
    132,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_43]
pos = [
    276,
    360,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_44]
pos = [
    276,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_45]
pos = [
    345,
    0,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_48]
pos = [
    551,
    496,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_49]
pos = [
    340,
    624,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_5]
pos = [
    828,
    68,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_50]
pos = [
    408,
    496,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_51]
pos = [
    68,
    688,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_52]
pos = [
    896,
    228,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_53]
pos = [
    759,
    136,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_56]
pos = [
    619,
    496,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_57]
pos = [
    475,
    828,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_58]
pos = [
    753,
    724,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_59]
pos = [
    820,
    788,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_60]
pos = [
    879,
    888,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_61]
pos = [
    879,
    956,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_64]
pos = [
    946,
    924,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_65]
pos = [
    954,
    856,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_66]
pos = [
    812,
    888,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_67]
pos = [
    890,
    688,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_68]
pos = [
    686,
    624,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_69]
pos = [
    758,
    364,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_72]
pos = [
    207,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_73]
pos = [
    0,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_74]
pos = [
    414,
    196,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_75]
pos = [
    690,
    0,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_76]
pos = [
    414,
    360,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_77]
pos = [
    828,
    0,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_8]
pos = [
    340,
    792,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_80]
pos = [
    408,
    696,
]
size = [
    66,
    34,
]
frame_offset = [
    0,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_81]
pos = [
    340,
    724,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_82]
pos = [
    272,
    756,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_83]
pos = [
    552,
    364,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_84]
pos = [
    136,
    656,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_85]
pos = [
    68,
    492,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_88]
pos = [
    483,
    396,
]
size = [
    67,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_89]
pos = [
    621,
    232,
]
size = [
    67,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_9]
pos = [
    756,
    560,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_90]
pos = [
    690,
    132,
]
size = [
    67,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_91]
pos = [
    552,
    164,
]
size = [
    67,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_92]
pos = [
    552,
    0,
]
size = [
    67,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_12_93]
pos = [
    138,
    228,
]
size = [
    67,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_0]
pos = [
    408,
    628,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_1]
pos = [
    272,
    656,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_10]
pos = [
    892,
    556,
]
size = [
    65,
    130,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_11]
pos = [
    542,
    924,
]
size = [
    65,
    98,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_12]
pos = [
    744,
    956,
]
size = [
    65,
    66,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_13]
pos = [
    339,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_16]
pos = [
    811,
    988,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_17]
pos = [
    957,
    788,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_18]
pos = [
    745,
    856,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_19]
pos = [
    678,
    788,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_2]
pos = [
    0,
    852,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_20]
pos = [
    543,
    760,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_21]
pos = [
    476,
    632,
]
size = [
    65,
    194,
]
frame_offset = [
    60,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_24]
pos = [
    69,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_3]
pos = [
    204,
    492,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_4]
pos = [
    827,
    296,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_5]
pos = [
    897,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_8]
pos = [
    408,
    732,
]
size = [
    65,
    194,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_exterior_roofs_30_13_9]
pos = [
    825,
    492,
]
size = [
    65,
    162,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]
