[location_entertainment_gallery_02_53]
pos = [
    749,
    0,
]
size = [
    117,
    218,
]
frame_offset = [
    5,
    36,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_54]
pos = [
    383,
    0,
]
size = [
    122,
    240,
]
frame_offset = [
    1,
    15,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_55]
pos = [
    393,
    937,
]
size = [
    64,
    75,
]
frame_offset = [
    34,
    165,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_56]
pos = [
    504,
    242,
]
size = [
    118,
    183,
]
frame_offset = [
    5,
    70,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_57]
pos = [
    248,
    256,
]
size = [
    121,
    176,
]
frame_offset = [
    5,
    80,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_58]
pos = [
    0,
    215,
]
size = [
    122,
    152,
]
frame_offset = [
    4,
    101,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_59]
pos = [
    124,
    413,
]
size = [
    117,
    95,
]
frame_offset = [
    8,
    76,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_60]
pos = [
    746,
    220,
]
size = [
    112,
    144,
]
frame_offset = [
    10,
    111,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_61]
pos = [
    0,
    674,
]
size = [
    104,
    173,
]
frame_offset = [
    11,
    79,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_62]
pos = [
    319,
    614,
]
size = [
    102,
    118,
]
frame_offset = [
    12,
    132,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_64]
pos = [
    914,
    879,
]
size = [
    58,
    83,
]
frame_offset = [
    70,
    148,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_65]
pos = [
    731,
    509,
]
size = [
    75,
    173,
]
frame_offset = [
    51,
    63,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_66]
pos = [
    311,
    854,
]
size = [
    80,
    134,
]
frame_offset = [
    45,
    88,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_67]
pos = [
    970,
    217,
]
size = [
    49,
    109,
]
frame_offset = [
    36,
    108,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_69]
pos = [
    248,
    219,
]
size = [
    3,
    2,
]
frame_offset = [
    69,
    1,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_72]
pos = [
    383,
    242,
]
size = [
    119,
    242,
]
frame_offset = [
    7,
    11,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_73]
pos = [
    628,
    210,
]
size = [
    116,
    180,
]
frame_offset = [
    5,
    73,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_74]
pos = [
    507,
    0,
]
size = [
    119,
    237,
]
frame_offset = [
    7,
    15,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_75]
pos = [
    631,
    509,
]
size = [
    98,
    78,
]
frame_offset = [
    21,
    68,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_76]
pos = [
    504,
    427,
]
size = [
    112,
    64,
]
frame_offset = [
    16,
    83,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_77]
pos = [
    525,
    629,
]
size = [
    93,
    165,
]
frame_offset = [
    16,
    91,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_78]
pos = [
    248,
    214,
]
size = [
    4,
    3,
]
frame_offset = [
    50,
    90,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_80]
pos = [
    0,
    982,
]
size = [
    80,
    30,
]
frame_offset = [
    46,
    197,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_81]
pos = [
    124,
    337,
]
size = [
    120,
    74,
]
frame_offset = [
    6,
    178,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_82]
pos = [
    128,
    134,
]
size = [
    126,
    78,
]
frame_offset = [
    2,
    173,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_83]
pos = [
    868,
    0,
]
size = [
    116,
    97,
]
frame_offset = [
    0,
    148,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_85]
pos = [
    986,
    0,
]
size = [
    32,
    154,
]
frame_offset = [
    31,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_88]
pos = [
    108,
    510,
]
size = [
    104,
    203,
]
frame_offset = [
    21,
    50,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_89]
pos = [
    628,
    0,
]
size = [
    119,
    208,
]
frame_offset = [
    7,
    41,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_90]
pos = [
    0,
    0,
]
size = [
    126,
    213,
]
frame_offset = [
    0,
    40,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_91]
pos = [
    860,
    220,
]
size = [
    108,
    203,
]
frame_offset = [
    6,
    42,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_92]
pos = [
    0,
    600,
]
size = [
    106,
    72,
]
frame_offset = [
    20,
    53,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_93]
pos = [
    243,
    434,
]
size = [
    116,
    57,
]
frame_offset = [
    6,
    59,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_94]
pos = [
    214,
    510,
]
size = [
    104,
    72,
]
frame_offset = [
    22,
    48,
]
frame_size = [
    128,
    256,
]

[location_entertainment_gallery_02_95]
pos = [
    417,
    749,
]
size = [
    87,
    186,
]
frame_offset = [
    13,
    62,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_0]
pos = [
    0,
    458,
]
size = [
    106,
    140,
]
frame_offset = [
    0,
    116,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_1]
pos = [
    746,
    366,
]
size = [
    107,
    132,
]
frame_offset = [
    16,
    116,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_10]
pos = [
    214,
    584,
]
size = [
    103,
    131,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_11]
pos = [
    211,
    717,
]
size = [
    102,
    120,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_12]
pos = [
    124,
    215,
]
size = [
    122,
    120,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_13]
pos = [
    425,
    493,
]
size = [
    102,
    121,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_14]
pos = [
    0,
    849,
]
size = [
    102,
    131,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_15]
pos = [
    106,
    715,
]
size = [
    103,
    120,
]
frame_offset = [
    23,
    136,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_16]
pos = [
    128,
    0,
]
size = [
    126,
    132,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_17]
pos = [
    423,
    616,
]
size = [
    100,
    131,
]
frame_offset = [
    12,
    47,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_18]
pos = [
    248,
    223,
]
size = [
    1,
    1,
]
frame_offset = [
    62,
    1,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_2]
pos = [
    868,
    99,
]
size = [
    114,
    116,
]
frame_offset = [
    14,
    140,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_20]
pos = [
    940,
    699,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_21]
pos = [
    848,
    829,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_22]
pos = [
    0,
    369,
]
size = [
    122,
    87,
]
frame_offset = [
    2,
    139,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_23]
pos = [
    371,
    256,
]
size = [
    6,
    194,
]
frame_offset = [
    60,
    2,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_24]
pos = [
    506,
    796,
]
size = [
    70,
    159,
]
frame_offset = [
    50,
    24,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_25]
pos = [
    929,
    425,
]
size = [
    70,
    159,
]
frame_offset = [
    4,
    24,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_26]
pos = [
    578,
    796,
]
size = [
    70,
    159,
]
frame_offset = [
    10,
    4,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_27]
pos = [
    709,
    684,
]
size = [
    70,
    159,
]
frame_offset = [
    44,
    4,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_28]
pos = [
    631,
    589,
]
size = [
    76,
    170,
]
frame_offset = [
    52,
    83,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_29]
pos = [
    855,
    425,
]
size = [
    72,
    171,
]
frame_offset = [
    0,
    82,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_3]
pos = [
    624,
    392,
]
size = [
    108,
    115,
]
frame_offset = [
    0,
    140,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_30]
pos = [
    914,
    789,
]
size = [
    64,
    88,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_31]
pos = [
    848,
    919,
]
size = [
    64,
    88,
]
frame_offset = [
    60,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_4]
pos = [
    209,
    839,
]
size = [
    100,
    118,
]
frame_offset = [
    0,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_40]
pos = [
    104,
    957,
]
size = [
    32,
    51,
]
frame_offset = [
    34,
    128,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_41]
pos = [
    716,
    845,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_42]
pos = [
    940,
    586,
]
size = [
    64,
    111,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_43]
pos = [
    808,
    598,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    94,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_44]
pos = [
    874,
    598,
]
size = [
    64,
    127,
]
frame_offset = [
    2,
    113,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_45]
pos = [
    782,
    844,
]
size = [
    64,
    98,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_46]
pos = [
    650,
    845,
]
size = [
    64,
    110,
]
frame_offset = [
    2,
    113,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_47]
pos = [
    970,
    328,
]
size = [
    26,
    76,
]
frame_offset = [
    2,
    147,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_48]
pos = [
    138,
    957,
]
size = [
    24,
    46,
]
frame_offset = [
    100,
    146,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_49]
pos = [
    847,
    728,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    117,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_5]
pos = [
    315,
    734,
]
size = [
    100,
    118,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_50]
pos = [
    781,
    728,
]
size = [
    64,
    114,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_6]
pos = [
    106,
    837,
]
size = [
    101,
    118,
]
frame_offset = [
    23,
    126,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_7]
pos = [
    529,
    509,
]
size = [
    100,
    118,
]
frame_offset = [
    26,
    138,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_8]
pos = [
    256,
    0,
]
size = [
    125,
    254,
]
frame_offset = [
    1,
    0,
]
frame_size = [
    128,
    256,
]

[location_entertainment_theatre_01_9]
pos = [
    320,
    493,
]
size = [
    103,
    119,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]
