[walls_commercial_01_100]
pos = [
    552,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_101]
pos = [
    345,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_102]
pos = [
    130,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_103]
pos = [
    975,
    229,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_106]
pos = [
    768,
    229,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_107]
pos = [
    837,
    229,
]
size = [
    67,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_108]
pos = [
    957,
    687,
]
size = [
    64,
    83,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_109]
pos = [
    957,
    772,
]
size = [
    64,
    62,
]
frame_offset = [
    60,
    165,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_110]
pos = [
    898,
    0,
]
size = [
    124,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_112]
pos = [
    906,
    229,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_113]
pos = [
    620,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_114]
pos = [
    258,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_115]
pos = [
    984,
    229,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_116]
pos = [
    0,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_117]
pos = [
    413,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_118]
pos = [
    0,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_119]
pos = [
    993,
    229,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_120]
pos = [
    69,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_121]
pos = [
    688,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_122]
pos = [
    128,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_123]
pos = [
    1002,
    229,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_59]
pos = [
    889,
    687,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_60]
pos = [
    481,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_61]
pos = [
    756,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_62]
pos = [
    256,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_64]
pos = [
    138,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_65]
pos = [
    207,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_66]
pos = [
    384,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_67]
pos = [
    984,
    427,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_68]
pos = [
    0,
    687,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_69]
pos = [
    276,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_70]
pos = [
    386,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_74]
pos = [
    69,
    687,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_75]
pos = [
    345,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_76]
pos = [
    138,
    687,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_77]
pos = [
    414,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_78]
pos = [
    514,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_80]
pos = [
    207,
    687,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_81]
pos = [
    549,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_82]
pos = [
    642,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_83]
pos = [
    1011,
    229,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_84]
pos = [
    483,
    458,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_85]
pos = [
    824,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_86]
pos = [
    512,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_90]
pos = [
    617,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_91]
pos = [
    892,
    458,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_92]
pos = [
    276,
    687,
]
size = [
    67,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_93]
pos = [
    685,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_94]
pos = [
    770,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_96]
pos = [
    753,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_97]
pos = [
    821,
    687,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_98]
pos = [
    640,
    229,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_01_99]
pos = [
    975,
    427,
]
size = [
    7,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_commercial_02_0]
pos = [
    0,
    0,
]
size = [
    128,
    227,
]
