[signs_one-off_07_on_104]
pos = [
    926,
    574,
]
size = [
    54,
    135,
]
frame_offset = [
    12,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_105]
pos = [
    0,
    433,
]
size = [
    64,
    163,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_106]
pos = [
    66,
    516,
]
size = [
    64,
    162,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_107]
pos = [
    729,
    627,
]
size = [
    60,
    146,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_108]
pos = [
    965,
    0,
]
size = [
    57,
    94,
]
frame_offset = [
    9,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_109]
pos = [
    531,
    637,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_110]
pos = [
    663,
    496,
]
size = [
    64,
    102,
]
frame_offset = [
    2,
    93,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_111]
pos = [
    264,
    929,
]
size = [
    64,
    93,
]
frame_offset = [
    2,
    100,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_112]
pos = [
    528,
    824,
]
size = [
    60,
    164,
]
frame_offset = [
    6,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_113]
pos = [
    795,
    182,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_114]
pos = [
    861,
    182,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_115]
pos = [
    927,
    180,
]
size = [
    64,
    174,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_116]
pos = [
    729,
    182,
]
size = [
    64,
    175,
]
frame_offset = [
    2,
    31,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_117]
pos = [
    861,
    452,
]
size = [
    63,
    165,
]
frame_offset = [
    2,
    41,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_118]
pos = [
    531,
    738,
]
size = [
    64,
    84,
]
frame_offset = [
    2,
    102,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_119]
pos = [
    989,
    441,
]
size = [
    33,
    67,
]
frame_offset = [
    2,
    119,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_128]
pos = [
    894,
    888,
]
size = [
    41,
    130,
]
frame_offset = [
    31,
    9,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_129]
pos = [
    66,
    346,
]
size = [
    64,
    168,
]
frame_offset = [
    8,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_130]
pos = [
    713,
    859,
]
size = [
    47,
    133,
]
frame_offset = [
    8,
    41,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_144]
pos = [
    663,
    687,
]
size = [
    62,
    85,
]
frame_offset = [
    4,
    73,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_145]
pos = [
    330,
    682,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    62,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_146]
pos = [
    791,
    718,
]
size = [
    50,
    107,
]
frame_offset = [
    2,
    88,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_152]
pos = [
    462,
    863,
]
size = [
    62,
    144,
]
frame_offset = [
    4,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_153]
pos = [
    132,
    511,
]
size = [
    64,
    151,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_154]
pos = [
    333,
    389,
]
size = [
    64,
    149,
]
frame_offset = [
    2,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_155]
pos = [
    264,
    393,
]
size = [
    64,
    150,
]
frame_offset = [
    2,
    51,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_156]
pos = [
    66,
    680,
]
size = [
    64,
    148,
]
frame_offset = [
    2,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_157]
pos = [
    330,
    920,
]
size = [
    64,
    89,
]
frame_offset = [
    2,
    113,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_158]
pos = [
    927,
    356,
]
size = [
    64,
    83,
]
frame_offset = [
    2,
    117,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_159]
pos = [
    396,
    898,
]
size = [
    64,
    81,
]
frame_offset = [
    2,
    112,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_160]
pos = [
    659,
    774,
]
size = [
    59,
    71,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_161]
pos = [
    860,
    619,
]
size = [
    57,
    87,
]
frame_offset = [
    9,
    111,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_162]
pos = [
    795,
    466,
]
size = [
    64,
    86,
]
frame_offset = [
    2,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_163]
pos = [
    597,
    608,
]
size = [
    64,
    95,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_164]
pos = [
    462,
    769,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_165]
pos = [
    0,
    145,
]
size = [
    67,
    85,
]
frame_offset = [
    2,
    114,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_184]
pos = [
    927,
    441,
]
size = [
    60,
    131,
]
frame_offset = [
    64,
    80,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_185]
pos = [
    132,
    346,
]
size = [
    64,
    163,
]
frame_offset = [
    60,
    48,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_186]
pos = [
    899,
    0,
]
size = [
    64,
    178,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_187]
pos = [
    795,
    554,
]
size = [
    63,
    162,
]
frame_offset = [
    60,
    45,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_61]
pos = [
    0,
    0,
]
size = [
    77,
    143,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_62]
pos = [
    79,
    0,
]
size = [
    75,
    143,
]
frame_offset = [
    22,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_63]
pos = [
    156,
    0,
]
size = [
    74,
    130,
]
frame_offset = [
    21,
    101,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_64]
pos = [
    198,
    694,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_65]
pos = [
    465,
    386,
]
size = [
    64,
    141,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_66]
pos = [
    399,
    530,
]
size = [
    64,
    138,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_67]
pos = [
    132,
    807,
]
size = [
    64,
    134,
]
frame_offset = [
    60,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_68]
pos = [
    66,
    830,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    65,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_69]
pos = [
    531,
    367,
]
size = [
    64,
    139,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_70]
pos = [
    330,
    812,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_71]
pos = [
    132,
    943,
]
size = [
    64,
    79,
]
frame_offset = [
    60,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_72]
pos = [
    597,
    765,
]
size = [
    60,
    143,
]
frame_offset = [
    6,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_73]
pos = [
    0,
    598,
]
size = [
    64,
    153,
]
frame_offset = [
    2,
    55,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_74]
pos = [
    330,
    540,
]
size = [
    64,
    140,
]
frame_offset = [
    2,
    68,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_75]
pos = [
    264,
    688,
]
size = [
    64,
    131,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_76]
pos = [
    465,
    529,
]
size = [
    64,
    130,
]
frame_offset = [
    2,
    67,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_77]
pos = [
    597,
    367,
]
size = [
    64,
    131,
]
frame_offset = [
    2,
    66,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_78]
pos = [
    0,
    897,
]
size = [
    64,
    123,
]
frame_offset = [
    2,
    71,
]
frame_size = [
    128,
    256,
]

[signs_one-off_07_on_79]
pos = [
    531,
    508,
]
size = [
    64,
    127,
]
frame_offset = [
    2,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_0]
pos = [
    232,
    0,
]
size = [
    71,
    202,
]
frame_offset = [
    53,
    22,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_1]
pos = [
    135,
    145,
]
size = [
    64,
    198,
]
frame_offset = [
    60,
    26,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_10]
pos = [
    264,
    821,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_11]
pos = [
    729,
    359,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_12]
pos = [
    597,
    500,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_13]
pos = [
    465,
    661,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_14]
pos = [
    993,
    338,
]
size = [
    22,
    85,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_15]
pos = [
    861,
    358,
]
size = [
    64,
    92,
]
frame_offset = [
    60,
    61,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_16]
pos = [
    1001,
    713,
]
size = [
    13,
    158,
]
frame_offset = [
    111,
    28,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_17]
pos = [
    399,
    201,
]
size = [
    64,
    183,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_18]
pos = [
    503,
    0,
]
size = [
    64,
    183,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_19]
pos = [
    569,
    0,
]
size = [
    64,
    183,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_2]
pos = [
    305,
    0,
]
size = [
    64,
    199,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_20]
pos = [
    635,
    0,
]
size = [
    64,
    183,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_21]
pos = [
    465,
    201,
]
size = [
    64,
    183,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_22]
pos = [
    993,
    176,
]
size = [
    22,
    160,
]
frame_offset = [
    60,
    3,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_23]
pos = [
    663,
    600,
]
size = [
    64,
    85,
]
frame_offset = [
    60,
    69,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_24]
pos = [
    822,
    898,
]
size = [
    42,
    115,
]
frame_offset = [
    82,
    46,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_25]
pos = [
    663,
    366,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_26]
pos = [
    198,
    835,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_27]
pos = [
    396,
    670,
]
size = [
    64,
    126,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_28]
pos = [
    775,
    827,
]
size = [
    45,
    117,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_29]
pos = [
    729,
    467,
]
size = [
    64,
    96,
]
frame_offset = [
    60,
    57,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_3]
pos = [
    371,
    0,
]
size = [
    64,
    199,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_30]
pos = [
    965,
    96,
]
size = [
    54,
    78,
]
frame_offset = [
    60,
    70,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_31]
pos = [
    985,
    713,
]
size = [
    14,
    151,
]
frame_offset = [
    110,
    62,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_32]
pos = [
    590,
    910,
]
size = [
    51,
    91,
]
frame_offset = [
    73,
    135,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_33]
pos = [
    396,
    798,
]
size = [
    64,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_34]
pos = [
    663,
    185,
]
size = [
    64,
    179,
]
frame_offset = [
    60,
    47,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_35]
pos = [
    198,
    393,
]
size = [
    64,
    155,
]
frame_offset = [
    60,
    71,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_36]
pos = [
    720,
    775,
]
size = [
    53,
    82,
]
frame_offset = [
    60,
    129,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_37]
pos = [
    701,
    0,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_38]
pos = [
    531,
    185,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_39]
pos = [
    767,
    0,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_4]
pos = [
    437,
    0,
]
size = [
    64,
    199,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_40]
pos = [
    989,
    510,
]
size = [
    31,
    44,
]
frame_offset = [
    93,
    19,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_41]
pos = [
    198,
    965,
]
size = [
    64,
    56,
]
frame_offset = [
    60,
    5,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_42]
pos = [
    597,
    705,
]
size = [
    64,
    58,
]
frame_offset = [
    60,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_43]
pos = [
    729,
    565,
]
size = [
    64,
    60,
]
frame_offset = [
    60,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_44]
pos = [
    66,
    971,
]
size = [
    34,
    46,
]
frame_offset = [
    60,
    4,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_45]
pos = [
    597,
    185,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_46]
pos = [
    833,
    0,
]
size = [
    64,
    180,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_47]
pos = [
    989,
    556,
]
size = [
    22,
    155,
]
frame_offset = [
    60,
    33,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_48]
pos = [
    941,
    711,
]
size = [
    42,
    127,
]
frame_offset = [
    82,
    63,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_49]
pos = [
    132,
    664,
]
size = [
    64,
    141,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_5]
pos = [
    69,
    145,
]
size = [
    64,
    199,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_50]
pos = [
    264,
    545,
]
size = [
    64,
    141,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_51]
pos = [
    198,
    550,
]
size = [
    64,
    142,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_52]
pos = [
    0,
    753,
]
size = [
    64,
    142,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_53]
pos = [
    399,
    386,
]
size = [
    64,
    142,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_54]
pos = [
    941,
    840,
]
size = [
    42,
    127,
]
frame_offset = [
    60,
    49,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_55]
pos = [
    201,
    132,
]
size = [
    14,
    47,
]
frame_offset = [
    110,
    94,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_56]
pos = [
    894,
    711,
]
size = [
    45,
    175,
]
frame_offset = [
    79,
    50,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_57]
pos = [
    267,
    204,
]
size = [
    64,
    186,
]
frame_offset = [
    60,
    39,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_58]
pos = [
    333,
    201,
]
size = [
    64,
    186,
]
frame_offset = [
    60,
    39,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_59]
pos = [
    201,
    204,
]
size = [
    64,
    187,
]
frame_offset = [
    60,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_6]
pos = [
    0,
    232,
]
size = [
    64,
    199,
]
frame_offset = [
    60,
    25,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_60]
pos = [
    843,
    718,
]
size = [
    49,
    178,
]
frame_offset = [
    60,
    38,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_7]
pos = [
    659,
    847,
]
size = [
    52,
    73,
]
frame_offset = [
    72,
    81,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_8]
pos = [
    643,
    910,
]
size = [
    13,
    79,
]
frame_offset = [
    111,
    147,
]
frame_size = [
    128,
    256,
]

[signs_one-off_08_9]
pos = [
    795,
    358,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    120,
]
frame_size = [
    128,
    256,
]
