[furniture_bedding_01_52]
pos = [
    483,
    575,
]
size = [
    116,
    114,
]
frame_offset = [
    10,
    140,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_53]
pos = [
    0,
    960,
]
size = [
    108,
    53,
]
frame_offset = [
    12,
    149,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_54]
pos = [
    256,
    233,
]
size = [
    122,
    114,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_55]
pos = [
    245,
    484,
]
size = [
    118,
    112,
]
frame_offset = [
    0,
    141,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_56]
pos = [
    125,
    360,
]
size = [
    123,
    110,
]
frame_offset = [
    3,
    144,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_57]
pos = [
    0,
    512,
]
size = [
    119,
    110,
]
frame_offset = [
    6,
    145,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_58]
pos = [
    124,
    472,
]
size = [
    119,
    110,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_59]
pos = [
    384,
    218,
]
size = [
    122,
    110,
]
frame_offset = [
    0,
    144,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_60]
pos = [
    631,
    335,
]
size = [
    121,
    103,
]
frame_offset = [
    3,
    152,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_61]
pos = [
    130,
    128,
]
size = [
    124,
    109,
]
frame_offset = [
    0,
    147,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_62]
pos = [
    258,
    122,
]
size = [
    124,
    109,
]
frame_offset = [
    2,
    147,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_63]
pos = [
    754,
    224,
]
size = [
    121,
    103,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_64]
pos = [
    757,
    117,
]
size = [
    121,
    105,
]
frame_offset = [
    5,
    148,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_65]
pos = [
    757,
    0,
]
size = [
    121,
    115,
]
frame_offset = [
    2,
    140,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_66]
pos = [
    631,
    218,
]
size = [
    121,
    115,
]
frame_offset = [
    3,
    140,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_67]
pos = [
    880,
    0,
]
size = [
    121,
    105,
]
frame_offset = [
    0,
    148,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_68]
pos = [
    0,
    0,
]
size = [
    128,
    124,
]
frame_offset = [
    0,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_69]
pos = [
    380,
    330,
]
size = [
    121,
    132,
]
frame_offset = [
    2,
    123,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_70]
pos = [
    255,
    349,
]
size = [
    121,
    133,
]
frame_offset = [
    3,
    122,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_71]
pos = [
    130,
    0,
]
size = [
    126,
    126,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_72]
pos = [
    361,
    699,
]
size = [
    114,
    122,
]
frame_offset = [
    12,
    132,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_73]
pos = [
    120,
    942,
]
size = [
    113,
    76,
]
frame_offset = [
    9,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_74]
pos = [
    754,
    329,
]
size = [
    120,
    121,
]
frame_offset = [
    2,
    130,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_75]
pos = [
    121,
    584,
]
size = [
    118,
    129,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_76]
pos = [
    0,
    126,
]
size = [
    128,
    119,
]
frame_offset = [
    0,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_77]
pos = [
    503,
    342,
]
size = [
    121,
    111,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_78]
pos = [
    0,
    247,
]
size = [
    123,
    158,
]
frame_offset = [
    1,
    97,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_79]
pos = [
    508,
    218,
]
size = [
    121,
    122,
]
frame_offset = [
    0,
    132,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_80]
pos = [
    241,
    710,
]
size = [
    116,
    128,
]
frame_offset = [
    10,
    125,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_81]
pos = [
    258,
    0,
]
size = [
    126,
    120,
]
frame_offset = [
    2,
    132,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_82]
pos = [
    483,
    691,
]
size = [
    112,
    74,
]
frame_offset = [
    4,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_83]
pos = [
    365,
    575,
]
size = [
    116,
    122,
]
frame_offset = [
    0,
    133,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_84]
pos = [
    386,
    0,
]
size = [
    123,
    216,
]
frame_offset = [
    5,
    37,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_85]
pos = [
    880,
    107,
]
size = [
    120,
    216,
]
frame_offset = [
    3,
    39,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_86]
pos = [
    511,
    0,
]
size = [
    121,
    216,
]
frame_offset = [
    3,
    39,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_87]
pos = [
    634,
    0,
]
size = [
    121,
    216,
]
frame_offset = [
    0,
    37,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_88]
pos = [
    925,
    697,
]
size = [
    95,
    140,
]
frame_offset = [
    25,
    113,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_89]
pos = [
    692,
    809,
]
size = [
    99,
    133,
]
frame_offset = [
    4,
    112,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_90]
pos = [
    588,
    799,
]
size = [
    102,
    131,
]
frame_offset = [
    22,
    114,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_91]
pos = [
    825,
    557,
]
size = [
    104,
    138,
]
frame_offset = [
    6,
    116,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_92]
pos = [
    894,
    839,
]
size = [
    94,
    140,
]
frame_offset = [
    25,
    113,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_93]
pos = [
    793,
    830,
]
size = [
    99,
    133,
]
frame_offset = [
    4,
    112,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_94]
pos = [
    821,
    697,
]
size = [
    102,
    131,
]
frame_offset = [
    22,
    114,
]
frame_size = [
    128,
    256,
]

[furniture_bedding_01_95]
pos = [
    714,
    669,
]
size = [
    105,
    138,
]
frame_offset = [
    5,
    116,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_0]
pos = [
    472,
    874,
]
size = [
    107,
    105,
]
frame_offset = [
    17,
    148,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_1]
pos = [
    239,
    840,
]
size = [
    112,
    113,
]
frame_offset = [
    2,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_10]
pos = [
    0,
    624,
]
size = [
    119,
    105,
]
frame_offset = [
    6,
    148,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_11]
pos = [
    877,
    325,
]
size = [
    120,
    106,
]
frame_offset = [
    0,
    147,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_12]
pos = [
    241,
    598,
]
size = [
    118,
    110,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_13]
pos = [
    121,
    715,
]
size = [
    118,
    111,
]
frame_offset = [
    6,
    143,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_14]
pos = [
    0,
    850,
]
size = [
    118,
    108,
]
frame_offset = [
    7,
    146,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_15]
pos = [
    378,
    464,
]
size = [
    118,
    109,
]
frame_offset = [
    0,
    145,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_16]
pos = [
    626,
    440,
]
size = [
    112,
    122,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_17]
pos = [
    359,
    823,
]
size = [
    111,
    115,
]
frame_offset = [
    10,
    139,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_18]
pos = [
    601,
    574,
]
size = [
    111,
    122,
]
frame_offset = [
    13,
    126,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_19]
pos = [
    503,
    455,
]
size = [
    116,
    117,
]
frame_offset = [
    2,
    138,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_2]
pos = [
    120,
    828,
]
size = [
    117,
    112,
]
frame_offset = [
    11,
    135,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_20]
pos = [
    0,
    407,
]
size = [
    122,
    103,
]
frame_offset = [
    6,
    153,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_3]
pos = [
    477,
    767,
]
size = [
    109,
    105,
]
frame_offset = [
    0,
    147,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_4]
pos = [
    740,
    452,
]
size = [
    110,
    99,
]
frame_offset = [
    16,
    150,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_5]
pos = [
    852,
    452,
]
size = [
    108,
    103,
]
frame_offset = [
    4,
    152,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_6]
pos = [
    714,
    564,
]
size = [
    109,
    103,
]
frame_offset = [
    13,
    152,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_7]
pos = [
    597,
    698,
]
size = [
    109,
    99,
]
frame_offset = [
    0,
    149,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_8]
pos = [
    130,
    239,
]
size = [
    123,
    119,
]
frame_offset = [
    5,
    134,
]
frame_size = [
    128,
    256,
]

[furniture_seating_indoor_01_9]
pos = [
    0,
    731,
]
size = [
    118,
    117,
]
frame_offset = [
    2,
    136,
]
frame_size = [
    128,
    256,
]
