[location_restaurant_pizzawhirled_01_18]
pos = [
    673,
    252,
]
size = [
    102,
    146,
]
frame_offset = [
    8,
    104,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_19]
pos = [
    336,
    499,
]
size = [
    80,
    88,
]
frame_offset = [
    44,
    124,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_20]
pos = [
    305,
    817,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    133,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_21]
pos = [
    502,
    414,
]
size = [
    64,
    145,
]
frame_offset = [
    60,
    103,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_22]
pos = [
    404,
    717,
]
size = [
    64,
    123,
]
frame_offset = [
    60,
    94,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_23]
pos = [
    805,
    485,
]
size = [
    62,
    89,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_24]
pos = [
    927,
    0,
]
size = [
    66,
    192,
]
frame_offset = [
    58,
    12,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_26]
pos = [
    624,
    634,
]
size = [
    63,
    86,
]
frame_offset = [
    3,
    119,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_27]
pos = [
    805,
    389,
]
size = [
    64,
    94,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_28]
pos = [
    173,
    798,
]
size = [
    64,
    139,
]
frame_offset = [
    2,
    85,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_29]
pos = [
    492,
    561,
]
size = [
    64,
    136,
]
frame_offset = [
    2,
    110,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_30]
pos = [
    157,
    939,
]
size = [
    64,
    79,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_31]
pos = [
    336,
    416,
]
size = [
    81,
    81,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_32]
pos = [
    0,
    123,
]
size = [
    126,
    120,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_33]
pos = [
    822,
    134,
]
size = [
    103,
    120,
]
frame_offset = [
    1,
    136,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_34]
pos = [
    822,
    0,
]
size = [
    103,
    132,
]
frame_offset = [
    2,
    124,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_35]
pos = [
    568,
    249,
]
size = [
    103,
    122,
]
frame_offset = [
    1,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_36]
pos = [
    0,
    0,
]
size = [
    127,
    121,
]
frame_offset = [
    1,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_37]
pos = [
    568,
    373,
]
size = [
    103,
    121,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_38]
pos = [
    777,
    256,
]
size = [
    102,
    131,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_39]
pos = [
    607,
    127,
]
size = [
    104,
    120,
]
frame_offset = [
    23,
    136,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_40]
pos = [
    499,
    0,
]
size = [
    106,
    245,
]
frame_offset = [
    15,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_41]
pos = [
    715,
    0,
]
size = [
    105,
    250,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_42]
pos = [
    0,
    507,
]
size = [
    100,
    250,
]
frame_offset = [
    26,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_43]
pos = [
    673,
    400,
]
size = [
    64,
    126,
]
frame_offset = [
    50,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_44]
pos = [
    462,
    268,
]
size = [
    104,
    144,
]
frame_offset = [
    21,
    105,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_45]
pos = [
    356,
    268,
]
size = [
    104,
    146,
]
frame_offset = [
    7,
    99,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_46]
pos = [
    536,
    732,
]
size = [
    62,
    256,
]
frame_offset = [
    11,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_47]
pos = [
    235,
    403,
]
size = [
    99,
    250,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_48]
pos = [
    253,
    0,
]
size = [
    122,
    131,
]
frame_offset = [
    6,
    118,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_49]
pos = [
    128,
    221,
]
size = [
    117,
    131,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_50]
pos = [
    0,
    245,
]
size = [
    119,
    131,
]
frame_offset = [
    9,
    124,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_51]
pos = [
    377,
    0,
]
size = [
    120,
    130,
]
frame_offset = [
    0,
    119,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_52]
pos = [
    869,
    485,
]
size = [
    61,
    107,
]
frame_offset = [
    5,
    15,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_53]
pos = [
    305,
    925,
]
size = [
    63,
    96,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_54]
pos = [
    634,
    528,
]
size = [
    64,
    96,
]
frame_offset = [
    60,
    28,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_55]
pos = [
    663,
    722,
]
size = [
    60,
    108,
]
frame_offset = [
    60,
    14,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_56]
pos = [
    816,
    594,
]
size = [
    57,
    179,
]
frame_offset = [
    8,
    44,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_57]
pos = [
    895,
    778,
]
size = [
    51,
    179,
]
frame_offset = [
    68,
    44,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_58]
pos = [
    725,
    733,
]
size = [
    56,
    181,
]
frame_offset = [
    54,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_59]
pos = [
    875,
    594,
]
size = [
    56,
    182,
]
frame_offset = [
    18,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_60]
pos = [
    783,
    775,
]
size = [
    54,
    180,
]
frame_offset = [
    7,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_61]
pos = [
    839,
    778,
]
size = [
    54,
    180,
]
frame_offset = [
    65,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_62]
pos = [
    933,
    590,
]
size = [
    55,
    181,
]
frame_offset = [
    54,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_63]
pos = [
    663,
    832,
]
size = [
    56,
    181,
]
frame_offset = [
    18,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_64]
pos = [
    253,
    133,
]
size = [
    113,
    133,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_65]
pos = [
    247,
    268,
]
size = [
    107,
    133,
]
frame_offset = [
    8,
    117,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_66]
pos = [
    368,
    133,
]
size = [
    108,
    133,
]
frame_offset = [
    11,
    118,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_67]
pos = [
    121,
    354,
]
size = [
    112,
    138,
]
frame_offset = [
    6,
    118,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_68]
pos = [
    607,
    0,
]
size = [
    106,
    125,
]
frame_offset = [
    10,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_69]
pos = [
    102,
    650,
]
size = [
    93,
    127,
]
frame_offset = [
    23,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_70]
pos = [
    0,
    759,
]
size = [
    89,
    125,
]
frame_offset = [
    11,
    127,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_71]
pos = [
    0,
    378,
]
size = [
    109,
    127,
]
frame_offset = [
    8,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_72]
pos = [
    418,
    499,
]
size = [
    72,
    216,
]
frame_offset = [
    56,
    25,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_73]
pos = [
    129,
    0,
]
size = [
    122,
    219,
]
frame_offset = [
    0,
    3,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_74]
pos = [
    277,
    655,
]
size = [
    55,
    119,
]
frame_offset = [
    35,
    5,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_75]
pos = [
    881,
    256,
]
size = [
    101,
    222,
]
frame_offset = [
    15,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_76]
pos = [
    600,
    848,
]
size = [
    52,
    114,
]
frame_offset = [
    51,
    5,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_77]
pos = [
    994,
    406,
]
size = [
    15,
    197,
]
frame_offset = [
    59,
    25,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_78]
pos = [
    600,
    732,
]
size = [
    61,
    114,
]
frame_offset = [
    19,
    30,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_19]
pos = [
    91,
    779,
]
size = [
    80,
    88,
]
frame_offset = [
    44,
    124,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_20]
pos = [
    470,
    717,
]
size = [
    64,
    106,
]
frame_offset = [
    60,
    133,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_21]
pos = [
    91,
    869,
]
size = [
    64,
    145,
]
frame_offset = [
    60,
    103,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_22]
pos = [
    739,
    400,
]
size = [
    64,
    123,
]
frame_offset = [
    60,
    94,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_23]
pos = [
    689,
    626,
]
size = [
    62,
    89,
]
frame_offset = [
    60,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_24]
pos = [
    0,
    886,
]
size = [
    66,
    65,
]
frame_offset = [
    58,
    139,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_26]
pos = [
    436,
    842,
]
size = [
    63,
    86,
]
frame_offset = [
    3,
    119,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_27]
pos = [
    700,
    528,
]
size = [
    64,
    94,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_28]
pos = [
    239,
    798,
]
size = [
    64,
    139,
]
frame_offset = [
    2,
    85,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_29]
pos = [
    568,
    496,
]
size = [
    64,
    136,
]
frame_offset = [
    2,
    110,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_30]
pos = [
    223,
    939,
]
size = [
    64,
    79,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_31]
pos = [
    419,
    416,
]
size = [
    81,
    81,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_52]
pos = [
    753,
    624,
]
size = [
    61,
    107,
]
frame_offset = [
    5,
    15,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_53]
pos = [
    371,
    842,
]
size = [
    63,
    96,
]
frame_offset = [
    2,
    28,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_54]
pos = [
    558,
    634,
]
size = [
    64,
    96,
]
frame_offset = [
    60,
    28,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_55]
pos = [
    932,
    480,
]
size = [
    60,
    108,
]
frame_offset = [
    60,
    14,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_72]
pos = [
    121,
    245,
]
size = [
    1,
    15,
]
frame_offset = [
    127,
    44,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_73]
pos = [
    102,
    507,
]
size = [
    100,
    141,
]
frame_offset = [
    0,
    15,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_74]
pos = [
    984,
    194,
]
size = [
    33,
    107,
]
frame_offset = [
    35,
    17,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_75]
pos = [
    197,
    655,
]
size = [
    78,
    141,
]
frame_offset = [
    38,
    11,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_76]
pos = [
    204,
    494,
]
size = [
    28,
    101,
]
frame_offset = [
    75,
    18,
]
frame_size = [
    128,
    256,
]

[location_restaurant_pizzawhirled_01_on_78]
pos = [
    984,
    303,
]
size = [
    30,
    101,
]
frame_offset = [
    50,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_seahorse_01_0]
pos = [
    336,
    589,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]
