[location_restaurant_spiffos_01_63]
pos = [
    703,
    0,
]
size = [
    103,
    129,
]
frame_offset = [
    23,
    127,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_64]
pos = [
    136,
    477,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_65]
pos = [
    808,
    0,
]
size = [
    92,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_66]
pos = [
    679,
    148,
]
size = [
    92,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_67]
pos = [
    213,
    447,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_68]
pos = [
    0,
    721,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_69]
pos = [
    281,
    447,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_70]
pos = [
    68,
    721,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_71]
pos = [
    902,
    0,
]
size = [
    91,
    226,
]
frame_offset = [
    35,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_72]
pos = [
    349,
    486,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_73]
pos = [
    0,
    492,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_74]
pos = [
    68,
    492,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_75]
pos = [
    861,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_76]
pos = [
    136,
    705,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_77]
pos = [
    204,
    675,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_78]
pos = [
    272,
    675,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_01_79]
pos = [
    930,
    228,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_0]
pos = [
    773,
    228,
]
size = [
    86,
    141,
]
frame_offset = [
    38,
    69,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_1]
pos = [
    340,
    801,
]
size = [
    64,
    137,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_10]
pos = [
    485,
    609,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_11]
pos = [
    408,
    714,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_12]
pos = [
    621,
    475,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_13]
pos = [
    577,
    278,
]
size = [
    92,
    145,
]
frame_offset = [
    2,
    69,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_16]
pos = [
    363,
    130,
]
size = [
    106,
    146,
]
frame_offset = [
    15,
    99,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_17]
pos = [
    490,
    0,
]
size = [
    105,
    145,
]
frame_offset = [
    0,
    105,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_18]
pos = [
    577,
    148,
]
size = [
    100,
    128,
]
frame_offset = [
    26,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_19]
pos = [
    406,
    854,
]
size = [
    64,
    126,
]
frame_offset = [
    50,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_2]
pos = [
    553,
    606,
]
size = [
    64,
    137,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_20]
pos = [
    471,
    147,
]
size = [
    104,
    144,
]
frame_offset = [
    21,
    105,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_21]
pos = [
    597,
    0,
]
size = [
    104,
    146,
]
frame_offset = [
    7,
    99,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_22]
pos = [
    819,
    557,
]
size = [
    62,
    127,
]
frame_offset = [
    11,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_23]
pos = [
    462,
    293,
]
size = [
    99,
    129,
]
frame_offset = [
    0,
    121,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_24]
pos = [
    731,
    887,
]
size = [
    49,
    113,
]
frame_offset = [
    40,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_25]
pos = [
    666,
    899,
]
size = [
    51,
    114,
]
frame_offset = [
    36,
    120,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_26]
pos = [
    877,
    691,
]
size = [
    51,
    96,
]
frame_offset = [
    35,
    139,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_27]
pos = [
    943,
    596,
]
size = [
    53,
    96,
]
frame_offset = [
    36,
    139,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_28]
pos = [
    417,
    509,
]
size = [
    66,
    100,
]
frame_offset = [
    58,
    47,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_29]
pos = [
    340,
    714,
]
size = [
    66,
    85,
]
frame_offset = [
    60,
    45,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_3]
pos = [
    687,
    475,
]
size = [
    64,
    136,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_30]
pos = [
    672,
    807,
]
size = [
    57,
    90,
]
frame_offset = [
    9,
    43,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_31]
pos = [
    462,
    424,
]
size = [
    74,
    83,
]
frame_offset = [
    2,
    62,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_32]
pos = [
    250,
    0,
]
size = [
    118,
    128,
]
frame_offset = [
    7,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_33]
pos = [
    243,
    130,
]
size = [
    118,
    121,
]
frame_offset = [
    0,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_34]
pos = [
    128,
    0,
]
size = [
    120,
    122,
]
frame_offset = [
    8,
    129,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_35]
pos = [
    123,
    124,
]
size = [
    118,
    129,
]
frame_offset = [
    1,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_36]
pos = [
    0,
    100,
]
size = [
    121,
    127,
]
frame_offset = [
    6,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_37]
pos = [
    119,
    255,
]
size = [
    116,
    129,
]
frame_offset = [
    2,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_38]
pos = [
    237,
    255,
]
size = [
    116,
    129,
]
frame_offset = [
    8,
    126,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_39]
pos = [
    370,
    0,
]
size = [
    118,
    127,
]
frame_offset = [
    0,
    122,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_4]
pos = [
    474,
    749,
]
size = [
    64,
    136,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_40]
pos = [
    789,
    827,
]
size = [
    48,
    89,
]
frame_offset = [
    74,
    32,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_41]
pos = [
    270,
    903,
]
size = [
    64,
    105,
]
frame_offset = [
    58,
    16,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_42]
pos = [
    753,
    516,
]
size = [
    64,
    104,
]
frame_offset = [
    58,
    15,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_43]
pos = [
    540,
    749,
]
size = [
    64,
    101,
]
frame_offset = [
    4,
    19,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_44]
pos = [
    204,
    903,
]
size = [
    64,
    107,
]
frame_offset = [
    4,
    15,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_45]
pos = [
    782,
    918,
]
size = [
    47,
    95,
]
frame_offset = [
    4,
    27,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_46]
pos = [
    957,
    456,
]
size = [
    59,
    138,
]
frame_offset = [
    65,
    92,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_47]
pos = [
    877,
    789,
]
size = [
    47,
    138,
]
frame_offset = [
    60,
    77,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_48]
pos = [
    995,
    0,
]
size = [
    23,
    214,
]
frame_offset = [
    52,
    22,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_49]
pos = [
    355,
    278,
]
size = [
    105,
    206,
]
frame_offset = [
    16,
    13,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_5]
pos = [
    619,
    615,
]
size = [
    64,
    134,
]
frame_offset = [
    60,
    73,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_50]
pos = [
    305,
    386,
]
size = [
    31,
    46,
]
frame_offset = [
    57,
    53,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_51]
pos = [
    0,
    229,
]
size = [
    117,
    200,
]
frame_offset = [
    3,
    19,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_52]
pos = [
    92,
    431,
]
size = [
    20,
    52,
]
frame_offset = [
    56,
    57,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_53]
pos = [
    999,
    216,
]
size = [
    15,
    197,
]
frame_offset = [
    55,
    22,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_54]
pos = [
    819,
    686,
]
size = [
    56,
    139,
]
frame_offset = [
    10,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_55]
pos = [
    930,
    694,
]
size = [
    48,
    140,
]
frame_offset = [
    2,
    91,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_56]
pos = [
    540,
    852,
]
size = [
    60,
    91,
]
frame_offset = [
    38,
    135,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_57]
pos = [
    685,
    714,
]
size = [
    60,
    91,
]
frame_offset = [
    28,
    137,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_58]
pos = [
    753,
    700,
]
size = [
    58,
    89,
]
frame_offset = [
    30,
    137,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_59]
pos = [
    606,
    845,
]
size = [
    58,
    90,
]
frame_offset = [
    36,
    139,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_6]
pos = [
    0,
    431,
]
size = [
    90,
    59,
]
frame_offset = [
    32,
    34,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_60]
pos = [
    485,
    509,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_61]
pos = [
    417,
    611,
]
size = [
    66,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_62]
pos = [
    0,
    0,
]
size = [
    126,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_63]
pos = [
    204,
    477,
]
size = [
    6,
    68,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_7]
pos = [
    213,
    386,
]
size = [
    90,
    59,
]
frame_offset = [
    4,
    34,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_8]
pos = [
    883,
    557,
]
size = [
    58,
    132,
]
frame_offset = [
    8,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_9]
pos = [
    759,
    376,
]
size = [
    64,
    138,
]
frame_offset = [
    2,
    75,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_0]
pos = [
    671,
    376,
]
size = [
    86,
    97,
]
frame_offset = [
    38,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_1]
pos = [
    687,
    613,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    104,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_10]
pos = [
    336,
    940,
]
size = [
    64,
    81,
]
frame_offset = [
    2,
    117,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_11]
pos = [
    753,
    622,
]
size = [
    64,
    76,
]
frame_offset = [
    2,
    123,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_12]
pos = [
    891,
    456,
]
size = [
    64,
    94,
]
frame_offset = [
    2,
    105,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_13]
pos = [
    119,
    386,
]
size = [
    92,
    89,
]
frame_offset = [
    2,
    111,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_2]
pos = [
    136,
    933,
]
size = [
    64,
    87,
]
frame_offset = [
    60,
    105,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_28]
pos = [
    553,
    507,
]
size = [
    66,
    97,
]
frame_offset = [
    58,
    50,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_29]
pos = [
    731,
    807,
]
size = [
    56,
    78,
]
frame_offset = [
    60,
    52,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_3]
pos = [
    472,
    887,
]
size = [
    64,
    94,
]
frame_offset = [
    60,
    104,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_30]
pos = [
    602,
    937,
]
size = [
    49,
    82,
]
frame_offset = [
    17,
    51,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_31]
pos = [
    538,
    425,
]
size = [
    74,
    80,
]
frame_offset = [
    2,
    65,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_4]
pos = [
    825,
    456,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    99,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_5]
pos = [
    538,
    945,
]
size = [
    47,
    77,
]
frame_offset = [
    60,
    100,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_8]
pos = [
    0,
    949,
]
size = [
    42,
    61,
]
frame_offset = [
    24,
    121,
]
frame_size = [
    128,
    256,
]

[location_restaurant_spiffos_02_on_9]
pos = [
    606,
    751,
]
size = [
    64,
    92,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]
