[vegetation_ornamental_01_39]
pos = [
    389,
    100,
]
size = [
    126,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_44]
pos = [
    0,
    164,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_45]
pos = [
    129,
    164,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_46]
pos = [
    0,
    254,
]
size = [
    127,
    88,
]
frame_offset = [
    0,
    168,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_48]
pos = [
    941,
    798,
]
size = [
    60,
    90,
]
frame_offset = [
    45,
    146,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_49]
pos = [
    204,
    482,
]
size = [
    47,
    90,
]
frame_offset = [
    38,
    146,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_50]
pos = [
    935,
    890,
]
size = [
    58,
    102,
]
frame_offset = [
    33,
    136,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_51]
pos = [
    875,
    864,
]
size = [
    58,
    103,
]
frame_offset = [
    31,
    135,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_56]
pos = [
    527,
    296,
]
size = [
    43,
    89,
]
frame_offset = [
    41,
    147,
]
frame_size = [
    128,
    256,
]

[vegetation_ornamental_01_57]
pos = [
    458,
    190,
]
size = [
    49,
    86,
]
frame_offset = [
    38,
    150,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_0]
pos = [
    586,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_1]
pos = [
    862,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_10]
pos = [
    863,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_11]
pos = [
    654,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_12]
pos = [
    931,
    0,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_13]
pos = [
    722,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_14]
pos = [
    794,
    181,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_15]
pos = [
    389,
    190,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_2]
pos = [
    129,
    254,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_3]
pos = [
    999,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_4]
pos = [
    656,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_5]
pos = [
    725,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_6]
pos = [
    258,
    198,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_7]
pos = [
    1007,
    0,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_8]
pos = [
    136,
    482,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_01_9]
pos = [
    257,
    426,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_0]
pos = [
    260,
    0,
]
size = [
    127,
    97,
]
frame_offset = [
    1,
    129,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_1]
pos = [
    0,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_10]
pos = [
    611,
    639,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_11]
pos = [
    543,
    767,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_12]
pos = [
    407,
    893,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_13]
pos = [
    0,
    444,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_14]
pos = [
    461,
    477,
]
size = [
    66,
    114,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_15]
pos = [
    732,
    555,
]
size = [
    65,
    49,
]
frame_offset = [
    1,
    177,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_16]
pos = [
    325,
    426,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_17]
pos = [
    794,
    0,
]
size = [
    67,
    179,
]
frame_offset = [
    60,
    47,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_18]
pos = [
    68,
    920,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_19]
pos = [
    408,
    609,
]
size = [
    66,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_2]
pos = [
    0,
    512,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_20]
pos = [
    0,
    344,
]
size = [
    126,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_21]
pos = [
    509,
    190,
]
size = [
    6,
    68,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_24]
pos = [
    260,
    99,
]
size = [
    127,
    97,
]
frame_offset = [
    1,
    129,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_25]
pos = [
    130,
    0,
]
size = [
    128,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_26]
pos = [
    930,
    228,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_27]
pos = [
    517,
    68,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_28]
pos = [
    136,
    710,
]
size = [
    66,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_29]
pos = [
    597,
    456,
]
size = [
    66,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_3]
pos = [
    587,
    0,
]
size = [
    67,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_30]
pos = [
    340,
    609,
]
size = [
    66,
    114,
]
frame_offset = [
    60,
    112,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_31]
pos = [
    408,
    709,
]
size = [
    66,
    50,
]
frame_offset = [
    60,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_32]
pos = [
    875,
    746,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_33]
pos = [
    800,
    523,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_34]
pos = [
    677,
    639,
]
size = [
    64,
    192,
]
frame_offset = [
    2,
    34,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_35]
pos = [
    867,
    456,
]
size = [
    64,
    192,
]
frame_offset = [
    60,
    34,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_36]
pos = [
    475,
    856,
]
size = [
    64,
    128,
]
frame_offset = [
    60,
    98,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_37]
pos = [
    517,
    0,
]
size = [
    68,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_38]
pos = [
    529,
    456,
]
size = [
    66,
    114,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_39]
pos = [
    541,
    961,
]
size = [
    64,
    49,
]
frame_offset = [
    2,
    177,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_4]
pos = [
    272,
    654,
]
size = [
    66,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_40]
pos = [
    68,
    740,
]
size = [
    66,
    178,
]
frame_offset = [
    0,
    48,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_41]
pos = [
    458,
    296,
]
size = [
    67,
    179,
]
frame_offset = [
    60,
    47,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_42]
pos = [
    340,
    725,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_43]
pos = [
    476,
    593,
]
size = [
    66,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_44]
pos = [
    389,
    0,
]
size = [
    126,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_45]
pos = [
    204,
    574,
]
size = [
    6,
    68,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_48]
pos = [
    675,
    833,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_49]
pos = [
    609,
    833,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_5]
pos = [
    272,
    818,
]
size = [
    66,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_50]
pos = [
    743,
    653,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_51]
pos = [
    933,
    586,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_52]
pos = [
    675,
    917,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_53]
pos = [
    741,
    931,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_54]
pos = [
    941,
    746,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_55]
pos = [
    741,
    855,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_6]
pos = [
    136,
    874,
]
size = [
    66,
    114,
]
frame_offset = [
    60,
    112,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_7]
pos = [
    665,
    456,
]
size = [
    66,
    50,
]
frame_offset = [
    60,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_72]
pos = [
    609,
    934,
]
size = [
    64,
    82,
]
frame_offset = [
    2,
    144,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_73]
pos = [
    809,
    653,
]
size = [
    64,
    99,
]
frame_offset = [
    2,
    127,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_74]
pos = [
    743,
    754,
]
size = [
    64,
    99,
]
frame_offset = [
    60,
    127,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_75]
pos = [
    809,
    754,
]
size = [
    64,
    82,
]
frame_offset = [
    60,
    144,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_76]
pos = [
    875,
    670,
]
size = [
    64,
    74,
]
frame_offset = [
    2,
    152,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_77]
pos = [
    875,
    812,
]
size = [
    62,
    50,
]
frame_offset = [
    2,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_78]
pos = [
    807,
    904,
]
size = [
    62,
    50,
]
frame_offset = [
    62,
    176,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_79]
pos = [
    941,
    670,
]
size = [
    64,
    74,
]
frame_offset = [
    60,
    152,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_8]
pos = [
    809,
    838,
]
size = [
    64,
    64,
]
frame_offset = [
    2,
    162,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_01_9]
pos = [
    933,
    456,
]
size = [
    64,
    128,
]
frame_offset = [
    2,
    98,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_0]
pos = [
    0,
    936,
]
size = [
    66,
    66,
]
frame_offset = [
    0,
    160,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_1]
pos = [
    204,
    818,
]
size = [
    66,
    98,
]
frame_offset = [
    0,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_10]
pos = [
    665,
    508,
]
size = [
    65,
    129,
]
frame_offset = [
    1,
    96,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_11]
pos = [
    733,
    456,
]
size = [
    65,
    97,
]
frame_offset = [
    1,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_12]
pos = [
    800,
    456,
]
size = [
    65,
    65,
]
frame_offset = [
    1,
    160,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_13]
pos = [
    271,
    986,
]
size = [
    65,
    33,
]
frame_offset = [
    1,
    192,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_16]
pos = [
    790,
    409,
]
size = [
    65,
    34,
]
frame_offset = [
    60,
    192,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_17]
pos = [
    271,
    918,
]
size = [
    65,
    66,
]
frame_offset = [
    60,
    160,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_18]
pos = [
    204,
    918,
]
size = [
    65,
    98,
]
frame_offset = [
    60,
    128,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_19]
pos = [
    408,
    761,
]
size = [
    65,
    130,
]
frame_offset = [
    60,
    96,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_2]
pos = [
    393,
    477,
]
size = [
    66,
    130,
]
frame_offset = [
    0,
    96,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_20]
pos = [
    340,
    825,
]
size = [
    65,
    162,
]
frame_offset = [
    60,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_3]
pos = [
    204,
    654,
]
size = [
    66,
    162,
]
frame_offset = [
    0,
    64,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_4]
pos = [
    0,
    740,
]
size = [
    66,
    194,
]
frame_offset = [
    0,
    32,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_5]
pos = [
    68,
    512,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_8]
pos = [
    544,
    572,
]
size = [
    65,
    193,
]
frame_offset = [
    1,
    32,
]
frame_size = [
    128,
    256,
]

[walls_burnt_roofs_30_01_9]
pos = [
    476,
    693,
]
size = [
    65,
    161,
]
frame_offset = [
    1,
    64,
]
frame_size = [
    128,
    256,
]
