[location_hospitality_sunstarmotel_01_24]
pos = [
    435,
    712,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_25]
pos = [
    503,
    712,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_26]
pos = [
    390,
    198,
]
size = [
    126,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_27]
pos = [
    993,
    606,
]
size = [
    6,
    196,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_28]
pos = [
    210,
    913,
]
size = [
    52,
    97,
]
frame_offset = [
    14,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_29]
pos = [
    693,
    886,
]
size = [
    50,
    97,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_30]
pos = [
    769,
    848,
]
size = [
    50,
    97,
]
frame_offset = [
    74,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_31]
pos = [
    863,
    641,
]
size = [
    52,
    97,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_32]
pos = [
    730,
    497,
]
size = [
    66,
    226,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_33]
pos = [
    571,
    713,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_34]
pos = [
    279,
    703,
]
size = [
    66,
    256,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_35]
pos = [
    944,
    378,
]
size = [
    66,
    226,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_36]
pos = [
    639,
    881,
]
size = [
    52,
    97,
]
frame_offset = [
    14,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_37]
pos = [
    877,
    740,
]
size = [
    50,
    97,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_38]
pos = [
    929,
    705,
]
size = [
    50,
    97,
]
frame_offset = [
    74,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_39]
pos = [
    769,
    749,
]
size = [
    52,
    97,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_40]
pos = [
    260,
    0,
]
size = [
    128,
    178,
]
frame_offset = [
    0,
    78,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_41]
pos = [
    0,
    0,
]
size = [
    128,
    225,
]
frame_offset = [
    0,
    28,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_42]
pos = [
    130,
    213,
]
size = [
    128,
    149,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_43]
pos = [
    986,
    120,
]
size = [
    28,
    207,
]
frame_offset = [
    4,
    20,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_48]
pos = [
    260,
    180,
]
size = [
    128,
    146,
]
frame_offset = [
    0,
    110,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_49]
pos = [
    130,
    0,
]
size = [
    128,
    211,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_50]
pos = [
    0,
    227,
]
size = [
    128,
    150,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_51]
pos = [
    647,
    144,
]
size = [
    123,
    207,
]
frame_offset = [
    0,
    23,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_52]
pos = [
    458,
    426,
]
size = [
    36,
    19,
]
frame_offset = [
    20,
    228,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_58]
pos = [
    798,
    499,
]
size = [
    66,
    107,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_59]
pos = [
    141,
    752,
]
size = [
    67,
    196,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_60]
pos = [
    388,
    426,
]
size = [
    68,
    196,
]
frame_offset = [
    59,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_61]
pos = [
    0,
    889,
]
size = [
    68,
    107,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_62]
pos = [
    390,
    0,
]
size = [
    127,
    196,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_64]
pos = [
    931,
    606,
]
size = [
    52,
    97,
]
frame_offset = [
    14,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_65]
pos = [
    821,
    848,
]
size = [
    50,
    97,
]
frame_offset = [
    2,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_66]
pos = [
    877,
    839,
]
size = [
    50,
    97,
]
frame_offset = [
    74,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_01_67]
pos = [
    823,
    749,
]
size = [
    52,
    97,
]
frame_offset = [
    60,
    46,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_0]
pos = [
    347,
    703,
]
size = [
    12,
    139,
]
frame_offset = [
    68,
    93,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_1]
pos = [
    367,
    474,
]
size = [
    12,
    143,
]
frame_offset = [
    68,
    89,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_10]
pos = [
    519,
    0,
]
size = [
    126,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_11]
pos = [
    985,
    606,
]
size = [
    6,
    197,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_12]
pos = [
    732,
    376,
]
size = [
    104,
    119,
]
frame_offset = [
    0,
    136,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_13]
pos = [
    626,
    362,
]
size = [
    104,
    120,
]
frame_offset = [
    2,
    125,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_14]
pos = [
    0,
    491,
]
size = [
    103,
    121,
]
frame_offset = [
    21,
    125,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_15]
pos = [
    772,
    254,
]
size = [
    104,
    120,
]
frame_offset = [
    23,
    136,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_17]
pos = [
    458,
    483,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_18]
pos = [
    526,
    483,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_19]
pos = [
    297,
    474,
]
size = [
    68,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_2]
pos = [
    706,
    725,
]
size = [
    61,
    159,
]
frame_offset = [
    51,
    68,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_20]
pos = [
    880,
    121,
]
size = [
    104,
    255,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_21]
pos = [
    838,
    378,
]
size = [
    104,
    119,
]
frame_offset = [
    1,
    125,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_22]
pos = [
    899,
    0,
]
size = [
    105,
    118,
]
frame_offset = [
    22,
    125,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_23]
pos = [
    518,
    362,
]
size = [
    106,
    119,
]
frame_offset = [
    22,
    136,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_24]
pos = [
    929,
    804,
]
size = [
    40,
    199,
]
frame_offset = [
    56,
    1,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_25]
pos = [
    367,
    624,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_26]
pos = [
    183,
    595,
]
size = [
    19,
    30,
]
frame_offset = [
    61,
    174,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_27]
pos = [
    71,
    717,
]
size = [
    19,
    30,
]
frame_offset = [
    46,
    174,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_28]
pos = [
    183,
    634,
]
size = [
    68,
    109,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_29]
pos = [
    71,
    752,
]
size = [
    68,
    109,
]
frame_offset = [
    60,
    113,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_3]
pos = [
    866,
    499,
]
size = [
    63,
    140,
]
frame_offset = [
    48,
    55,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_30]
pos = [
    0,
    379,
]
size = [
    128,
    110,
]
frame_offset = [
    0,
    112,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_31]
pos = [
    259,
    474,
]
size = [
    8,
    6,
]
frame_offset = [
    59,
    114,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_32]
pos = [
    210,
    745,
]
size = [
    67,
    166,
]
frame_offset = [
    61,
    41,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_33]
pos = [
    647,
    0,
]
size = [
    124,
    142,
]
frame_offset = [
    0,
    5,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_34]
pos = [
    253,
    634,
]
size = [
    36,
    65,
]
frame_offset = [
    85,
    14,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_35]
pos = [
    71,
    863,
]
size = [
    66,
    108,
]
frame_offset = [
    58,
    116,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_36]
pos = [
    347,
    853,
]
size = [
    66,
    108,
]
frame_offset = [
    2,
    116,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_37]
pos = [
    415,
    940,
]
size = [
    36,
    65,
]
frame_offset = [
    5,
    14,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_38]
pos = [
    260,
    328,
]
size = [
    126,
    144,
]
frame_offset = [
    2,
    5,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_39]
pos = [
    639,
    713,
]
size = [
    65,
    166,
]
frame_offset = [
    0,
    41,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_4]
pos = [
    798,
    608,
]
size = [
    63,
    139,
]
frame_offset = [
    47,
    55,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_40]
pos = [
    130,
    364,
]
size = [
    127,
    119,
]
frame_offset = [
    0,
    136,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_41]
pos = [
    773,
    121,
]
size = [
    105,
    131,
]
frame_offset = [
    0,
    124,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_42]
pos = [
    773,
    0,
]
size = [
    124,
    119,
]
frame_offset = [
    0,
    126,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_43]
pos = [
    518,
    229,
]
size = [
    124,
    131,
]
frame_offset = [
    0,
    125,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_44]
pos = [
    0,
    614,
]
size = [
    101,
    101,
]
frame_offset = [
    25,
    14,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_45]
pos = [
    105,
    491,
]
size = [
    102,
    102,
]
frame_offset = [
    0,
    14,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_5]
pos = [
    0,
    717,
]
size = [
    69,
    170,
]
frame_offset = [
    45,
    53,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_6]
pos = [
    105,
    595,
]
size = [
    76,
    155,
]
frame_offset = [
    27,
    90,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_7]
pos = [
    209,
    485,
]
size = [
    86,
    147,
]
frame_offset = [
    22,
    90,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_8]
pos = [
    594,
    484,
]
size = [
    66,
    227,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[location_hospitality_sunstarmotel_02_9]
pos = [
    662,
    484,
]
size = [
    66,
    227,
]
frame_offset = [
    60,
    0,
]
frame_size = [
    128,
    256,
]
