[camping_03_13]
pos = [
    255,
    285,
]
size = [
    122,
    137,
]
frame_offset = [
    6,
    114,
]
frame_size = [
    128,
    256,
]

[camping_03_14]
pos = [
    509,
    244,
]
size = [
    119,
    136,
]
frame_offset = [
    0,
    114,
]
frame_size = [
    128,
    256,
]

[camping_03_15]
pos = [
    379,
    297,
]
size = [
    122,
    118,
]
frame_offset = [
    6,
    136,
]
frame_size = [
    128,
    256,
]

[camping_03_16]
pos = [
    468,
    649,
]
size = [
    102,
    125,
]
frame_offset = [
    11,
    126,
]
frame_size = [
    128,
    256,
]

[camping_03_17]
pos = [
    620,
    479,
]
size = [
    102,
    251,
]
frame_offset = [
    11,
    0,
]
frame_size = [
    128,
    256,
]

[camping_03_18]
pos = [
    350,
    815,
]
size = [
    102,
    125,
]
frame_offset = [
    11,
    126,
]
frame_size = [
    128,
    256,
]

[camping_03_19]
pos = [
    724,
    479,
]
size = [
    97,
    84,
]
frame_offset = [
    17,
    164,
]
frame_size = [
    128,
    256,
]

[camping_03_20]
pos = [
    458,
    776,
]
size = [
    97,
    84,
]
frame_offset = [
    17,
    164,
]
frame_size = [
    128,
    256,
]

[camping_03_21]
pos = [
    724,
    565,
]
size = [
    97,
    84,
]
frame_offset = [
    17,
    164,
]
frame_size = [
    128,
    256,
]

[camping_03_24]
pos = [
    130,
    0,
]
size = [
    127,
    255,
]
frame_offset = [
    0,
    0,
]
frame_size = [
    128,
    256,
]

[camping_03_25]
pos = [
    823,
    479,
]
size = [
    90,
    255,
]
frame_offset = [
    33,
    0,
]
frame_size = [
    128,
    256,
]

[camping_03_26]
pos = [
    0,
    154,
]
size = [
    127,
    255,
]
frame_offset = [
    1,
    0,
]
frame_size = [
    128,
    256,
]

[camping_03_27]
pos = [
    259,
    0,
]
size = [
    125,
    128,
]
frame_offset = [
    0,
    127,
]
frame_size = [
    128,
    256,
]

[camping_03_28]
pos = [
    0,
    940,
]
size = [
    32,
    44,
]
frame_offset = [
    47,
    154,
]
frame_size = [
    128,
    256,
]

[camping_03_33]
pos = [
    255,
    257,
]
size = [
    2,
    9,
]
frame_offset = [
    42,
    14,
]
frame_size = [
    128,
    256,
]

[camping_03_40]
pos = [
    757,
    0,
]
size = [
    117,
    173,
]
frame_offset = [
    1,
    80,
]
frame_size = [
    128,
    256,
]

[camping_03_41]
pos = [
    0,
    0,
]
size = [
    128,
    152,
]
frame_offset = [
    0,
    104,
]
frame_size = [
    128,
    256,
]

[camping_03_42]
pos = [
    259,
    130,
]
size = [
    123,
    153,
]
frame_offset = [
    0,
    103,
]
frame_size = [
    128,
    256,
]

[camping_03_43]
pos = [
    635,
    0,
]
size = [
    120,
    175,
]
frame_offset = [
    7,
    80,
]
frame_size = [
    128,
    256,
]

[camping_03_44]
pos = [
    384,
    150,
]
size = [
    123,
    145,
]
frame_offset = [
    0,
    109,
]
frame_size = [
    128,
    256,
]

[camping_03_45]
pos = [
    512,
    0,
]
size = [
    121,
    122,
]
frame_offset = [
    7,
    133,
]
frame_size = [
    128,
    256,
]

[camping_03_46]
pos = [
    512,
    124,
]
size = [
    120,
    118,
]
frame_offset = [
    0,
    134,
]
frame_size = [
    128,
    256,
]

[camping_03_47]
pos = [
    129,
    257,
]
size = [
    124,
    146,
]
frame_offset = [
    4,
    110,
]
frame_size = [
    128,
    256,
]

[camping_04_0]
pos = [
    724,
    651,
]
size = [
    64,
    88,
]
frame_offset = [
    64,
    138,
]
frame_size = [
    128,
    256,
]

[camping_04_12]
pos = [
    351,
    703,
]
size = [
    105,
    110,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[camping_04_13]
pos = [
    634,
    177,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_14]
pos = [
    752,
    177,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_15]
pos = [
    915,
    479,
]
size = [
    62,
    125,
]
frame_offset = [
    2,
    131,
]
frame_size = [
    128,
    256,
]

[camping_04_19]
pos = [
    893,
    862,
]
size = [
    59,
    81,
]
frame_offset = [
    6,
    143,
]
frame_size = [
    128,
    256,
]

[camping_04_20]
pos = [
    520,
    871,
]
size = [
    62,
    123,
]
frame_offset = [
    66,
    132,
]
frame_size = [
    128,
    256,
]

[camping_04_21]
pos = [
    386,
    0,
]
size = [
    124,
    148,
]
frame_offset = [
    4,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_22]
pos = [
    234,
    575,
]
size = [
    115,
    148,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_23]
pos = [
    234,
    725,
]
size = [
    114,
    125,
]
frame_offset = [
    12,
    98,
]
frame_size = [
    128,
    256,
]

[camping_04_27]
pos = [
    815,
    736,
]
size = [
    59,
    124,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[camping_04_28]
pos = [
    648,
    865,
]
size = [
    60,
    123,
]
frame_offset = [
    68,
    133,
]
frame_size = [
    128,
    256,
]

[camping_04_29]
pos = [
    117,
    713,
]
size = [
    115,
    148,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_30]
pos = [
    503,
    382,
]
size = [
    115,
    148,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_31]
pos = [
    234,
    852,
]
size = [
    105,
    110,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[camping_04_32]
pos = [
    557,
    776,
]
size = [
    64,
    93,
]
frame_offset = [
    64,
    138,
]
frame_size = [
    128,
    256,
]

[camping_04_36]
pos = [
    0,
    562,
]
size = [
    115,
    225,
]
frame_offset = [
    2,
    0,
]
frame_size = [
    128,
    256,
]

[camping_04_37]
pos = [
    630,
    328,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_38]
pos = [
    870,
    175,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_39]
pos = [
    710,
    865,
]
size = [
    59,
    124,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[camping_04_4]
pos = [
    351,
    575,
]
size = [
    115,
    126,
]
frame_offset = [
    2,
    99,
]
frame_size = [
    128,
    256,
]

[camping_04_40]
pos = [
    584,
    871,
]
size = [
    62,
    122,
]
frame_offset = [
    66,
    133,
]
frame_size = [
    128,
    256,
]

[camping_04_44]
pos = [
    876,
    0,
]
size = [
    105,
    115,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[camping_04_45]
pos = [
    748,
    328,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_46]
pos = [
    866,
    328,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_47]
pos = [
    623,
    732,
]
size = [
    62,
    125,
]
frame_offset = [
    2,
    131,
]
frame_size = [
    128,
    256,
]

[camping_04_5]
pos = [
    0,
    411,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_51]
pos = [
    832,
    862,
]
size = [
    59,
    86,
]
frame_offset = [
    6,
    143,
]
frame_size = [
    128,
    256,
]

[camping_04_52]
pos = [
    687,
    741,
]
size = [
    62,
    122,
]
frame_offset = [
    66,
    133,
]
frame_size = [
    128,
    256,
]

[camping_04_53]
pos = [
    236,
    424,
]
size = [
    115,
    149,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_54]
pos = [
    117,
    562,
]
size = [
    115,
    149,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_55]
pos = [
    117,
    863,
]
size = [
    114,
    125,
]
frame_offset = [
    12,
    98,
]
frame_size = [
    128,
    256,
]

[camping_04_59]
pos = [
    876,
    736,
]
size = [
    59,
    124,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[camping_04_6]
pos = [
    118,
    411,
]
size = [
    116,
    149,
]
frame_offset = [
    2,
    104,
]
frame_size = [
    128,
    256,
]

[camping_04_60]
pos = [
    915,
    606,
]
size = [
    60,
    123,
]
frame_offset = [
    68,
    133,
]
frame_size = [
    128,
    256,
]

[camping_04_61]
pos = [
    353,
    424,
]
size = [
    115,
    149,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_62]
pos = [
    0,
    789,
]
size = [
    115,
    149,
]
frame_offset = [
    13,
    106,
]
frame_size = [
    128,
    256,
]

[camping_04_63]
pos = [
    470,
    532,
]
size = [
    105,
    115,
]
frame_offset = [
    12,
    107,
]
frame_size = [
    128,
    256,
]

[camping_04_64]
pos = [
    454,
    862,
]
size = [
    64,
    95,
]
frame_offset = [
    64,
    136,
]
frame_size = [
    128,
    256,
]

[camping_04_7]
pos = [
    771,
    865,
]
size = [
    59,
    124,
]
frame_offset = [
    1,
    130,
]
frame_size = [
    128,
    256,
]

[camping_04_8]
pos = [
    751,
    741,
]
size = [
    62,
    122,
]
frame_offset = [
    66,
    133,
]
frame_size = [
    128,
    256,
]

[camping_04_9]
pos = [
    255,
    268,
]
size = [
    1,
    1,
]
frame_offset = [
    5,
    142,
]
frame_size = [
    128,
    256,
]
